// Code generated by ent, DO NOT EDIT.

package he

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the he type in the database.
	Label = "he"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "ma_he"
	// FieldTenHe holds the string denoting the ten_he field in the database.
	FieldTenHe = "ten_he"
	// FieldMoTa holds the string denoting the mo_ta field in the database.
	FieldMoTa = "mo_ta"
	// EdgeVuKhi holds the string denoting the vu_khi edge name in mutations.
	EdgeVuKhi = "vu_khi"
	// VuKhiFieldID holds the string denoting the ID field of the VuKhi.
	VuKhiFieldID = "ma_vu_khi"
	// Table holds the table name of the he in the database.
	Table = "hes"
	// VuKhiTable is the table that holds the vu_khi relation/edge.
	VuKhiTable = "vu_khis"
	// VuKhiInverseTable is the table name for the VuKhi entity.
	// It exists in this package in order to avoid circular dependency with the "vukhi" package.
	VuKhiInverseTable = "vu_khis"
	// VuKhiColumn is the table column denoting the vu_khi relation/edge.
	VuKhiColumn = "ma_he"
)

// Columns holds all SQL columns for he fields.
var Columns = []string{
	FieldID,
	FieldTenHe,
	FieldMoTa,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenHeValidator is a validator for the "ten_he" field. It is called by the builders before save.
	TenHeValidator func(string) error
	// MoTaValidator is a validator for the "mo_ta" field. It is called by the builders before save.
	MoTaValidator func(string) error
)

// OrderOption defines the ordering options for the He queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenHe orders the results by the ten_he field.
func ByTenHe(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenHe, opts...).ToFunc()
}

// ByMoTa orders the results by the mo_ta field.
func ByMoTa(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMoTa, opts...).ToFunc()
}

// ByVuKhiCount orders the results by vu_khi count.
func ByVuKhiCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVuKhiStep(), opts...)
	}
}

// ByVuKhi orders the results by vu_khi terms.
func ByVuKhi(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVuKhiStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVuKhiStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VuKhiInverseTable, VuKhiFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VuKhiTable, VuKhiColumn),
	)
}
