// Code generated by ent, DO NOT EDIT.

package he

import (
	"game/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.He {
	return predicate.He(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.He {
	return predicate.He(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.He {
	return predicate.He(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.He {
	return predicate.He(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.He {
	return predicate.He(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.He {
	return predicate.He(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.He {
	return predicate.He(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.He {
	return predicate.He(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.He {
	return predicate.He(sql.FieldLTE(FieldID, id))
}

// TenHe applies equality check predicate on the "ten_he" field. It's identical to TenHeEQ.
func TenHe(v string) predicate.He {
	return predicate.He(sql.FieldEQ(FieldTenHe, v))
}

// MoTa applies equality check predicate on the "mo_ta" field. It's identical to MoTaEQ.
func MoTa(v string) predicate.He {
	return predicate.He(sql.FieldEQ(FieldMoTa, v))
}

// TenHeEQ applies the EQ predicate on the "ten_he" field.
func TenHeEQ(v string) predicate.He {
	return predicate.He(sql.FieldEQ(FieldTenHe, v))
}

// TenHeNEQ applies the NEQ predicate on the "ten_he" field.
func TenHeNEQ(v string) predicate.He {
	return predicate.He(sql.FieldNEQ(FieldTenHe, v))
}

// TenHeIn applies the In predicate on the "ten_he" field.
func TenHeIn(vs ...string) predicate.He {
	return predicate.He(sql.FieldIn(FieldTenHe, vs...))
}

// TenHeNotIn applies the NotIn predicate on the "ten_he" field.
func TenHeNotIn(vs ...string) predicate.He {
	return predicate.He(sql.FieldNotIn(FieldTenHe, vs...))
}

// TenHeGT applies the GT predicate on the "ten_he" field.
func TenHeGT(v string) predicate.He {
	return predicate.He(sql.FieldGT(FieldTenHe, v))
}

// TenHeGTE applies the GTE predicate on the "ten_he" field.
func TenHeGTE(v string) predicate.He {
	return predicate.He(sql.FieldGTE(FieldTenHe, v))
}

// TenHeLT applies the LT predicate on the "ten_he" field.
func TenHeLT(v string) predicate.He {
	return predicate.He(sql.FieldLT(FieldTenHe, v))
}

// TenHeLTE applies the LTE predicate on the "ten_he" field.
func TenHeLTE(v string) predicate.He {
	return predicate.He(sql.FieldLTE(FieldTenHe, v))
}

// TenHeContains applies the Contains predicate on the "ten_he" field.
func TenHeContains(v string) predicate.He {
	return predicate.He(sql.FieldContains(FieldTenHe, v))
}

// TenHeHasPrefix applies the HasPrefix predicate on the "ten_he" field.
func TenHeHasPrefix(v string) predicate.He {
	return predicate.He(sql.FieldHasPrefix(FieldTenHe, v))
}

// TenHeHasSuffix applies the HasSuffix predicate on the "ten_he" field.
func TenHeHasSuffix(v string) predicate.He {
	return predicate.He(sql.FieldHasSuffix(FieldTenHe, v))
}

// TenHeEqualFold applies the EqualFold predicate on the "ten_he" field.
func TenHeEqualFold(v string) predicate.He {
	return predicate.He(sql.FieldEqualFold(FieldTenHe, v))
}

// TenHeContainsFold applies the ContainsFold predicate on the "ten_he" field.
func TenHeContainsFold(v string) predicate.He {
	return predicate.He(sql.FieldContainsFold(FieldTenHe, v))
}

// MoTaEQ applies the EQ predicate on the "mo_ta" field.
func MoTaEQ(v string) predicate.He {
	return predicate.He(sql.FieldEQ(FieldMoTa, v))
}

// MoTaNEQ applies the NEQ predicate on the "mo_ta" field.
func MoTaNEQ(v string) predicate.He {
	return predicate.He(sql.FieldNEQ(FieldMoTa, v))
}

// MoTaIn applies the In predicate on the "mo_ta" field.
func MoTaIn(vs ...string) predicate.He {
	return predicate.He(sql.FieldIn(FieldMoTa, vs...))
}

// MoTaNotIn applies the NotIn predicate on the "mo_ta" field.
func MoTaNotIn(vs ...string) predicate.He {
	return predicate.He(sql.FieldNotIn(FieldMoTa, vs...))
}

// MoTaGT applies the GT predicate on the "mo_ta" field.
func MoTaGT(v string) predicate.He {
	return predicate.He(sql.FieldGT(FieldMoTa, v))
}

// MoTaGTE applies the GTE predicate on the "mo_ta" field.
func MoTaGTE(v string) predicate.He {
	return predicate.He(sql.FieldGTE(FieldMoTa, v))
}

// MoTaLT applies the LT predicate on the "mo_ta" field.
func MoTaLT(v string) predicate.He {
	return predicate.He(sql.FieldLT(FieldMoTa, v))
}

// MoTaLTE applies the LTE predicate on the "mo_ta" field.
func MoTaLTE(v string) predicate.He {
	return predicate.He(sql.FieldLTE(FieldMoTa, v))
}

// MoTaContains applies the Contains predicate on the "mo_ta" field.
func MoTaContains(v string) predicate.He {
	return predicate.He(sql.FieldContains(FieldMoTa, v))
}

// MoTaHasPrefix applies the HasPrefix predicate on the "mo_ta" field.
func MoTaHasPrefix(v string) predicate.He {
	return predicate.He(sql.FieldHasPrefix(FieldMoTa, v))
}

// MoTaHasSuffix applies the HasSuffix predicate on the "mo_ta" field.
func MoTaHasSuffix(v string) predicate.He {
	return predicate.He(sql.FieldHasSuffix(FieldMoTa, v))
}

// MoTaIsNil applies the IsNil predicate on the "mo_ta" field.
func MoTaIsNil() predicate.He {
	return predicate.He(sql.FieldIsNull(FieldMoTa))
}

// MoTaNotNil applies the NotNil predicate on the "mo_ta" field.
func MoTaNotNil() predicate.He {
	return predicate.He(sql.FieldNotNull(FieldMoTa))
}

// MoTaEqualFold applies the EqualFold predicate on the "mo_ta" field.
func MoTaEqualFold(v string) predicate.He {
	return predicate.He(sql.FieldEqualFold(FieldMoTa, v))
}

// MoTaContainsFold applies the ContainsFold predicate on the "mo_ta" field.
func MoTaContainsFold(v string) predicate.He {
	return predicate.He(sql.FieldContainsFold(FieldMoTa, v))
}

// HasVuKhi applies the HasEdge predicate on the "vu_khi" edge.
func HasVuKhi() predicate.He {
	return predicate.He(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VuKhiTable, VuKhiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVuKhiWith applies the HasEdge predicate on the "vu_khi" edge with a given conditions (other predicates).
func HasVuKhiWith(preds ...predicate.VuKhi) predicate.He {
	return predicate.He(func(s *sql.Selector) {
		step := newVuKhiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.He) predicate.He {
	return predicate.He(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.He) predicate.He {
	return predicate.He(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.He) predicate.He {
	return predicate.He(sql.NotPredicates(p))
}
