// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: v1/dohiem.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoHiem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaDoHiem       int32                  `protobuf:"varint,1,opt,name=ma_do_hiem,json=maDoHiem,proto3" json:"ma_do_hiem,omitempty"`
	TenDoHiem      string                 `protobuf:"bytes,2,opt,name=ten_do_hiem,json=tenDoHiem,proto3" json:"ten_do_hiem,omitempty"`
	SoLuong        int32                  `protobuf:"varint,3,opt,name=so_luong,json=soLuong,proto3" json:"so_luong,omitempty"`
	MauSac         string                 `protobuf:"bytes,4,opt,name=mau_sac,json=mauSac,proto3" json:"mau_sac,omitempty"`
	SatThuongBonus float64                `protobuf:"fixed64,5,opt,name=sat_thuong_bonus,json=satThuongBonus,proto3" json:"sat_thuong_bonus,omitempty"`
	TocDoDanhBonus float64                `protobuf:"fixed64,6,opt,name=toc_do_danh_bonus,json=tocDoDanhBonus,proto3" json:"toc_do_danh_bonus,omitempty"`
	CapBac         int32                  `protobuf:"varint,7,opt,name=cap_bac,json=capBac,proto3" json:"cap_bac,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DoHiem) Reset() {
	*x = DoHiem{}
	mi := &file_v1_dohiem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoHiem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoHiem) ProtoMessage() {}

func (x *DoHiem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoHiem.ProtoReflect.Descriptor instead.
func (*DoHiem) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{0}
}

func (x *DoHiem) GetMaDoHiem() int32 {
	if x != nil {
		return x.MaDoHiem
	}
	return 0
}

func (x *DoHiem) GetTenDoHiem() string {
	if x != nil {
		return x.TenDoHiem
	}
	return ""
}

func (x *DoHiem) GetSoLuong() int32 {
	if x != nil {
		return x.SoLuong
	}
	return 0
}

func (x *DoHiem) GetMauSac() string {
	if x != nil {
		return x.MauSac
	}
	return ""
}

func (x *DoHiem) GetSatThuongBonus() float64 {
	if x != nil {
		return x.SatThuongBonus
	}
	return 0
}

func (x *DoHiem) GetTocDoDanhBonus() float64 {
	if x != nil {
		return x.TocDoDanhBonus
	}
	return 0
}

func (x *DoHiem) GetCapBac() int32 {
	if x != nil {
		return x.CapBac
	}
	return 0
}

type TaoDoHiemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaDoHiem       int32                  `protobuf:"varint,1,opt,name=ma_do_hiem,json=maDoHiem,proto3" json:"ma_do_hiem,omitempty"`
	TenDoHiem      string                 `protobuf:"bytes,2,opt,name=ten_do_hiem,json=tenDoHiem,proto3" json:"ten_do_hiem,omitempty"`
	SoLuong        int32                  `protobuf:"varint,3,opt,name=so_luong,json=soLuong,proto3" json:"so_luong,omitempty"`
	MauSac         string                 `protobuf:"bytes,4,opt,name=mau_sac,json=mauSac,proto3" json:"mau_sac,omitempty"`
	SatThuongBonus float64                `protobuf:"fixed64,5,opt,name=sat_thuong_bonus,json=satThuongBonus,proto3" json:"sat_thuong_bonus,omitempty"`
	TocDoDanhBonus float64                `protobuf:"fixed64,6,opt,name=toc_do_danh_bonus,json=tocDoDanhBonus,proto3" json:"toc_do_danh_bonus,omitempty"`
	CapBac         int32                  `protobuf:"varint,7,opt,name=cap_bac,json=capBac,proto3" json:"cap_bac,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaoDoHiemRequest) Reset() {
	*x = TaoDoHiemRequest{}
	mi := &file_v1_dohiem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaoDoHiemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoDoHiemRequest) ProtoMessage() {}

func (x *TaoDoHiemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoDoHiemRequest.ProtoReflect.Descriptor instead.
func (*TaoDoHiemRequest) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{1}
}

func (x *TaoDoHiemRequest) GetMaDoHiem() int32 {
	if x != nil {
		return x.MaDoHiem
	}
	return 0
}

func (x *TaoDoHiemRequest) GetTenDoHiem() string {
	if x != nil {
		return x.TenDoHiem
	}
	return ""
}

func (x *TaoDoHiemRequest) GetSoLuong() int32 {
	if x != nil {
		return x.SoLuong
	}
	return 0
}

func (x *TaoDoHiemRequest) GetMauSac() string {
	if x != nil {
		return x.MauSac
	}
	return ""
}

func (x *TaoDoHiemRequest) GetSatThuongBonus() float64 {
	if x != nil {
		return x.SatThuongBonus
	}
	return 0
}

func (x *TaoDoHiemRequest) GetTocDoDanhBonus() float64 {
	if x != nil {
		return x.TocDoDanhBonus
	}
	return 0
}

func (x *TaoDoHiemRequest) GetCapBac() int32 {
	if x != nil {
		return x.CapBac
	}
	return 0
}

type CapNhatTheoTenDoHiemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TenDoHiem      string                 `protobuf:"bytes,2,opt,name=ten_do_hiem,json=tenDoHiem,proto3" json:"ten_do_hiem,omitempty"`
	SoLuong        int32                  `protobuf:"varint,3,opt,name=so_luong,json=soLuong,proto3" json:"so_luong,omitempty"`
	MauSac         string                 `protobuf:"bytes,4,opt,name=mau_sac,json=mauSac,proto3" json:"mau_sac,omitempty"`
	SatThuongBonus float64                `protobuf:"fixed64,5,opt,name=sat_thuong_bonus,json=satThuongBonus,proto3" json:"sat_thuong_bonus,omitempty"`
	TocDoDanhBonus float64                `protobuf:"fixed64,6,opt,name=toc_do_danh_bonus,json=tocDoDanhBonus,proto3" json:"toc_do_danh_bonus,omitempty"`
	CapBac         int32                  `protobuf:"varint,7,opt,name=cap_bac,json=capBac,proto3" json:"cap_bac,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CapNhatTheoTenDoHiemRequest) Reset() {
	*x = CapNhatTheoTenDoHiemRequest{}
	mi := &file_v1_dohiem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapNhatTheoTenDoHiemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapNhatTheoTenDoHiemRequest) ProtoMessage() {}

func (x *CapNhatTheoTenDoHiemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapNhatTheoTenDoHiemRequest.ProtoReflect.Descriptor instead.
func (*CapNhatTheoTenDoHiemRequest) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{2}
}

func (x *CapNhatTheoTenDoHiemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapNhatTheoTenDoHiemRequest) GetTenDoHiem() string {
	if x != nil {
		return x.TenDoHiem
	}
	return ""
}

func (x *CapNhatTheoTenDoHiemRequest) GetSoLuong() int32 {
	if x != nil {
		return x.SoLuong
	}
	return 0
}

func (x *CapNhatTheoTenDoHiemRequest) GetMauSac() string {
	if x != nil {
		return x.MauSac
	}
	return ""
}

func (x *CapNhatTheoTenDoHiemRequest) GetSatThuongBonus() float64 {
	if x != nil {
		return x.SatThuongBonus
	}
	return 0
}

func (x *CapNhatTheoTenDoHiemRequest) GetTocDoDanhBonus() float64 {
	if x != nil {
		return x.TocDoDanhBonus
	}
	return 0
}

func (x *CapNhatTheoTenDoHiemRequest) GetCapBac() int32 {
	if x != nil {
		return x.CapBac
	}
	return 0
}

type XoaTheoTenDoHiemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XoaTheoTenDoHiemRequest) Reset() {
	*x = XoaTheoTenDoHiemRequest{}
	mi := &file_v1_dohiem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XoaTheoTenDoHiemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XoaTheoTenDoHiemRequest) ProtoMessage() {}

func (x *XoaTheoTenDoHiemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XoaTheoTenDoHiemRequest.ProtoReflect.Descriptor instead.
func (*XoaTheoTenDoHiemRequest) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{3}
}

func (x *XoaTheoTenDoHiemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type XoaTheoTenDoHiemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedName   string                 `protobuf:"bytes,1,opt,name=deleted_name,json=deletedName,proto3" json:"deleted_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XoaTheoTenDoHiemResponse) Reset() {
	*x = XoaTheoTenDoHiemResponse{}
	mi := &file_v1_dohiem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XoaTheoTenDoHiemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XoaTheoTenDoHiemResponse) ProtoMessage() {}

func (x *XoaTheoTenDoHiemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XoaTheoTenDoHiemResponse.ProtoReflect.Descriptor instead.
func (*XoaTheoTenDoHiemResponse) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{4}
}

func (x *XoaTheoTenDoHiemResponse) GetDeletedName() string {
	if x != nil {
		return x.DeletedName
	}
	return ""
}

type LayTatCaDoHiemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayTatCaDoHiemRequest) Reset() {
	*x = LayTatCaDoHiemRequest{}
	mi := &file_v1_dohiem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayTatCaDoHiemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayTatCaDoHiemRequest) ProtoMessage() {}

func (x *LayTatCaDoHiemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayTatCaDoHiemRequest.ProtoReflect.Descriptor instead.
func (*LayTatCaDoHiemRequest) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{5}
}

func (x *LayTatCaDoHiemRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type DanhSachDoHiem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*DoHiem              `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanhSachDoHiem) Reset() {
	*x = DanhSachDoHiem{}
	mi := &file_v1_dohiem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanhSachDoHiem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanhSachDoHiem) ProtoMessage() {}

func (x *DanhSachDoHiem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanhSachDoHiem.ProtoReflect.Descriptor instead.
func (*DanhSachDoHiem) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{6}
}

func (x *DanhSachDoHiem) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DanhSachDoHiem) GetItems() []*DoHiem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DanhSachIntDoHiem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []int32                `protobuf:"varint,2,rep,packed,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanhSachIntDoHiem) Reset() {
	*x = DanhSachIntDoHiem{}
	mi := &file_v1_dohiem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanhSachIntDoHiem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanhSachIntDoHiem) ProtoMessage() {}

func (x *DanhSachIntDoHiem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanhSachIntDoHiem.ProtoReflect.Descriptor instead.
func (*DanhSachIntDoHiem) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{7}
}

func (x *DanhSachIntDoHiem) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DanhSachIntDoHiem) GetItems() []int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type DanhSachStringDoHiem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanhSachStringDoHiem) Reset() {
	*x = DanhSachStringDoHiem{}
	mi := &file_v1_dohiem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanhSachStringDoHiem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanhSachStringDoHiem) ProtoMessage() {}

func (x *DanhSachStringDoHiem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanhSachStringDoHiem.ProtoReflect.Descriptor instead.
func (*DanhSachStringDoHiem) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{8}
}

func (x *DanhSachStringDoHiem) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DanhSachStringDoHiem) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type DanhSachDoubleDoHiem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []float64              `protobuf:"fixed64,2,rep,packed,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanhSachDoubleDoHiem) Reset() {
	*x = DanhSachDoubleDoHiem{}
	mi := &file_v1_dohiem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanhSachDoubleDoHiem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanhSachDoubleDoHiem) ProtoMessage() {}

func (x *DanhSachDoubleDoHiem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanhSachDoubleDoHiem.ProtoReflect.Descriptor instead.
func (*DanhSachDoubleDoHiem) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{9}
}

func (x *DanhSachDoubleDoHiem) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DanhSachDoubleDoHiem) GetItems() []float64 {
	if x != nil {
		return x.Items
	}
	return nil
}

type TimKiemDoHiemRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MaDoHiem  *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=ma_do_hiem,json=maDoHiem,proto3" json:"ma_do_hiem,omitempty"`
	TenDoHiem string                 `protobuf:"bytes,2,opt,name=ten_do_hiem,json=tenDoHiem,proto3" json:"ten_do_hiem,omitempty"`
	MauSac    string                 `protobuf:"bytes,3,opt,name=mau_sac,json=mauSac,proto3" json:"mau_sac,omitempty"`
	// không cần số liên tiếp vì sau thay đổi sẽ bị phá vỡ nguyên tắc để số như này dễ mở rộng
	// so_luong: bằng / hoặc theo range
	SoLuong    *wrapperspb.Int32Value `protobuf:"bytes,10,opt,name=so_luong,json=soLuong,proto3" json:"so_luong,omitempty"`
	MinSoLuong *wrapperspb.Int32Value `protobuf:"bytes,11,opt,name=min_so_luong,json=minSoLuong,proto3" json:"min_so_luong,omitempty"`
	MaxSoLuong *wrapperspb.Int32Value `protobuf:"bytes,12,opt,name=max_so_luong,json=maxSoLuong,proto3" json:"max_so_luong,omitempty"`
	// sat_thuong_bonus: bằng / hoặc theo range
	SatThuongBonus    *wrapperspb.DoubleValue `protobuf:"bytes,20,opt,name=sat_thuong_bonus,json=satThuongBonus,proto3" json:"sat_thuong_bonus,omitempty"`
	MinSatThuongBonus *wrapperspb.DoubleValue `protobuf:"bytes,21,opt,name=min_sat_thuong_bonus,json=minSatThuongBonus,proto3" json:"min_sat_thuong_bonus,omitempty"`
	MaxSatThuongBonus *wrapperspb.DoubleValue `protobuf:"bytes,22,opt,name=max_sat_thuong_bonus,json=maxSatThuongBonus,proto3" json:"max_sat_thuong_bonus,omitempty"`
	// toc_do_danh_bonus: bằng / hoặc theo range
	TocDoDanhBonus    *wrapperspb.DoubleValue `protobuf:"bytes,30,opt,name=toc_do_danh_bonus,json=tocDoDanhBonus,proto3" json:"toc_do_danh_bonus,omitempty"`
	MinTocDoDanhBonus *wrapperspb.DoubleValue `protobuf:"bytes,31,opt,name=min_toc_do_danh_bonus,json=minTocDoDanhBonus,proto3" json:"min_toc_do_danh_bonus,omitempty"`
	MaxTocDoDanhBonus *wrapperspb.DoubleValue `protobuf:"bytes,32,opt,name=max_toc_do_danh_bonus,json=maxTocDoDanhBonus,proto3" json:"max_toc_do_danh_bonus,omitempty"`
	// NEW: lọc theo cấp (không giới hạn range)
	CapBac        *wrapperspb.Int32Value `protobuf:"bytes,50,opt,name=cap_bac,json=capBac,proto3" json:"cap_bac,omitempty"`
	MinCapBac     *wrapperspb.Int32Value `protobuf:"bytes,51,opt,name=min_cap_bac,json=minCapBac,proto3" json:"min_cap_bac,omitempty"`
	MaxCapBac     *wrapperspb.Int32Value `protobuf:"bytes,52,opt,name=max_cap_bac,json=maxCapBac,proto3" json:"max_cap_bac,omitempty"`
	DsCapBac      []int32                `protobuf:"varint,53,rep,packed,name=ds_cap_bac,json=dsCapBac,proto3" json:"ds_cap_bac,omitempty"`
	Q             string                 `protobuf:"bytes,40,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimKiemDoHiemRequest) Reset() {
	*x = TimKiemDoHiemRequest{}
	mi := &file_v1_dohiem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimKiemDoHiemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimKiemDoHiemRequest) ProtoMessage() {}

func (x *TimKiemDoHiemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dohiem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimKiemDoHiemRequest.ProtoReflect.Descriptor instead.
func (*TimKiemDoHiemRequest) Descriptor() ([]byte, []int) {
	return file_v1_dohiem_proto_rawDescGZIP(), []int{10}
}

func (x *TimKiemDoHiemRequest) GetMaDoHiem() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaDoHiem
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetTenDoHiem() string {
	if x != nil {
		return x.TenDoHiem
	}
	return ""
}

func (x *TimKiemDoHiemRequest) GetMauSac() string {
	if x != nil {
		return x.MauSac
	}
	return ""
}

func (x *TimKiemDoHiemRequest) GetSoLuong() *wrapperspb.Int32Value {
	if x != nil {
		return x.SoLuong
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetMinSoLuong() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinSoLuong
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetMaxSoLuong() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxSoLuong
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetSatThuongBonus() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SatThuongBonus
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetMinSatThuongBonus() *wrapperspb.DoubleValue {
	if x != nil {
		return x.MinSatThuongBonus
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetMaxSatThuongBonus() *wrapperspb.DoubleValue {
	if x != nil {
		return x.MaxSatThuongBonus
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetTocDoDanhBonus() *wrapperspb.DoubleValue {
	if x != nil {
		return x.TocDoDanhBonus
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetMinTocDoDanhBonus() *wrapperspb.DoubleValue {
	if x != nil {
		return x.MinTocDoDanhBonus
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetMaxTocDoDanhBonus() *wrapperspb.DoubleValue {
	if x != nil {
		return x.MaxTocDoDanhBonus
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetCapBac() *wrapperspb.Int32Value {
	if x != nil {
		return x.CapBac
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetMinCapBac() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinCapBac
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetMaxCapBac() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxCapBac
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetDsCapBac() []int32 {
	if x != nil {
		return x.DsCapBac
	}
	return nil
}

func (x *TimKiemDoHiemRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

var File_v1_dohiem_proto protoreflect.FileDescriptor

const file_v1_dohiem_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/dohiem.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xe8\x01\n" +
	"\x06DoHiem\x12\x1c\n" +
	"\n" +
	"ma_do_hiem\x18\x01 \x01(\x05R\bmaDoHiem\x12\x1e\n" +
	"\vten_do_hiem\x18\x02 \x01(\tR\ttenDoHiem\x12\x19\n" +
	"\bso_luong\x18\x03 \x01(\x05R\asoLuong\x12\x17\n" +
	"\amau_sac\x18\x04 \x01(\tR\x06mauSac\x12(\n" +
	"\x10sat_thuong_bonus\x18\x05 \x01(\x01R\x0esatThuongBonus\x12)\n" +
	"\x11toc_do_danh_bonus\x18\x06 \x01(\x01R\x0etocDoDanhBonus\x12\x17\n" +
	"\acap_bac\x18\a \x01(\x05R\x06capBac\"\xf2\x01\n" +
	"\x10TaoDoHiemRequest\x12\x1c\n" +
	"\n" +
	"ma_do_hiem\x18\x01 \x01(\x05R\bmaDoHiem\x12\x1e\n" +
	"\vten_do_hiem\x18\x02 \x01(\tR\ttenDoHiem\x12\x19\n" +
	"\bso_luong\x18\x03 \x01(\x05R\asoLuong\x12\x17\n" +
	"\amau_sac\x18\x04 \x01(\tR\x06mauSac\x12(\n" +
	"\x10sat_thuong_bonus\x18\x05 \x01(\x01R\x0esatThuongBonus\x12)\n" +
	"\x11toc_do_danh_bonus\x18\x06 \x01(\x01R\x0etocDoDanhBonus\x12\x17\n" +
	"\acap_bac\x18\a \x01(\x05R\x06capBac\"\xf3\x01\n" +
	"\x1bCapNhatTheoTenDoHiemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\vten_do_hiem\x18\x02 \x01(\tR\ttenDoHiem\x12\x19\n" +
	"\bso_luong\x18\x03 \x01(\x05R\asoLuong\x12\x17\n" +
	"\amau_sac\x18\x04 \x01(\tR\x06mauSac\x12(\n" +
	"\x10sat_thuong_bonus\x18\x05 \x01(\x01R\x0esatThuongBonus\x12)\n" +
	"\x11toc_do_danh_bonus\x18\x06 \x01(\x01R\x0etocDoDanhBonus\x12\x17\n" +
	"\acap_bac\x18\a \x01(\x05R\x06capBac\"-\n" +
	"\x17XoaTheoTenDoHiemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"=\n" +
	"\x18XoaTheoTenDoHiemResponse\x12!\n" +
	"\fdeleted_name\x18\x01 \x01(\tR\vdeletedName\"%\n" +
	"\x15LayTatCaDoHiemRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\"H\n" +
	"\x0eDanhSachDoHiem\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12 \n" +
	"\x05items\x18\x02 \x03(\v2\n" +
	".v1.DoHiemR\x05items\"?\n" +
	"\x11DanhSachIntDoHiem\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05items\x18\x02 \x03(\x05R\x05items\"B\n" +
	"\x14DanhSachStringDoHiem\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\"B\n" +
	"\x14DanhSachDoubleDoHiem\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05items\x18\x02 \x03(\x01R\x05items\"\xeb\a\n" +
	"\x14TimKiemDoHiemRequest\x129\n" +
	"\n" +
	"ma_do_hiem\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\bmaDoHiem\x12\x1e\n" +
	"\vten_do_hiem\x18\x02 \x01(\tR\ttenDoHiem\x12\x17\n" +
	"\amau_sac\x18\x03 \x01(\tR\x06mauSac\x126\n" +
	"\bso_luong\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int32ValueR\asoLuong\x12=\n" +
	"\fmin_so_luong\x18\v \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"minSoLuong\x12=\n" +
	"\fmax_so_luong\x18\f \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"maxSoLuong\x12F\n" +
	"\x10sat_thuong_bonus\x18\x14 \x01(\v2\x1c.google.protobuf.DoubleValueR\x0esatThuongBonus\x12M\n" +
	"\x14min_sat_thuong_bonus\x18\x15 \x01(\v2\x1c.google.protobuf.DoubleValueR\x11minSatThuongBonus\x12M\n" +
	"\x14max_sat_thuong_bonus\x18\x16 \x01(\v2\x1c.google.protobuf.DoubleValueR\x11maxSatThuongBonus\x12G\n" +
	"\x11toc_do_danh_bonus\x18\x1e \x01(\v2\x1c.google.protobuf.DoubleValueR\x0etocDoDanhBonus\x12N\n" +
	"\x15min_toc_do_danh_bonus\x18\x1f \x01(\v2\x1c.google.protobuf.DoubleValueR\x11minTocDoDanhBonus\x12N\n" +
	"\x15max_toc_do_danh_bonus\x18  \x01(\v2\x1c.google.protobuf.DoubleValueR\x11maxTocDoDanhBonus\x124\n" +
	"\acap_bac\x182 \x01(\v2\x1b.google.protobuf.Int32ValueR\x06capBac\x12;\n" +
	"\vmin_cap_bac\x183 \x01(\v2\x1b.google.protobuf.Int32ValueR\tminCapBac\x12;\n" +
	"\vmax_cap_bac\x184 \x01(\v2\x1b.google.protobuf.Int32ValueR\tmaxCapBac\x12\x1c\n" +
	"\n" +
	"ds_cap_bac\x185 \x03(\x05R\bdsCapBac\x12\f\n" +
	"\x01q\x18( \x01(\tR\x01q2\xf1\a\n" +
	"\rDoHiemService\x12M\n" +
	"\fCreateDoHiem\x12\x14.v1.TaoDoHiemRequest\x1a\n" +
	".v1.DoHiem\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/dohiem/ent/post\x12l\n" +
	"\x12UpdateByNameDoHiem\x12\x1f.v1.CapNhatTheoTenDoHiemRequest\x1a\n" +
	".v1.DoHiem\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/dohiem/ent/put-by-name/{name}\x12z\n" +
	"\x12DeleteByNameDoHiem\x12\x1b.v1.XoaTheoTenDoHiemRequest\x1a\x1c.v1.XoaTheoTenDoHiemResponse\")\x82\xd3\xe4\x93\x02#*!/dohiem/ent/delete-by-name/{name}\x12Y\n" +
	"\fGetAllDoHiem\x12\x19.v1.LayTatCaDoHiemRequest\x1a\x12.v1.DanhSachDoHiem\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/dohiem/ent/getall\x12\\\n" +
	"\x0fGetAllTenDoHiem\x12\x16.google.protobuf.Empty\x1a\x18.v1.DanhSachStringDoHiem\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/dohiem/ent/ten\x12a\n" +
	"\x13GetAllSoLuongDoHiem\x12\x16.google.protobuf.Empty\x1a\x15.v1.DanhSachIntDoHiem\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/dohiem/ent/soluong\x12b\n" +
	"\x12GetAllMauSacDoHiem\x12\x16.google.protobuf.Empty\x1a\x18.v1.DanhSachStringDoHiem\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/dohiem/ent/mausac\x12h\n" +
	"\x15GetAllSatThuongDoHiem\x12\x16.google.protobuf.Empty\x1a\x18.v1.DanhSachDoubleDoHiem\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/dohiem/ent/satthuong\x12`\n" +
	"\x11GetAllTocDoDoHiem\x12\x16.google.protobuf.Empty\x1a\x18.v1.DanhSachDoubleDoHiem\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/dohiem/ent/tocdo\x12[\n" +
	"\fSearchDoHiem\x12\x18.v1.TimKiemDoHiemRequest\x1a\x12.v1.DanhSachDoHiem\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/dohiem/ent/searchB\fZ\n" +
	"game/v1;v1b\x06proto3"

var (
	file_v1_dohiem_proto_rawDescOnce sync.Once
	file_v1_dohiem_proto_rawDescData []byte
)

func file_v1_dohiem_proto_rawDescGZIP() []byte {
	file_v1_dohiem_proto_rawDescOnce.Do(func() {
		file_v1_dohiem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_dohiem_proto_rawDesc), len(file_v1_dohiem_proto_rawDesc)))
	})
	return file_v1_dohiem_proto_rawDescData
}

var file_v1_dohiem_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_dohiem_proto_goTypes = []any{
	(*DoHiem)(nil),                      // 0: v1.DoHiem
	(*TaoDoHiemRequest)(nil),            // 1: v1.TaoDoHiemRequest
	(*CapNhatTheoTenDoHiemRequest)(nil), // 2: v1.CapNhatTheoTenDoHiemRequest
	(*XoaTheoTenDoHiemRequest)(nil),     // 3: v1.XoaTheoTenDoHiemRequest
	(*XoaTheoTenDoHiemResponse)(nil),    // 4: v1.XoaTheoTenDoHiemResponse
	(*LayTatCaDoHiemRequest)(nil),       // 5: v1.LayTatCaDoHiemRequest
	(*DanhSachDoHiem)(nil),              // 6: v1.DanhSachDoHiem
	(*DanhSachIntDoHiem)(nil),           // 7: v1.DanhSachIntDoHiem
	(*DanhSachStringDoHiem)(nil),        // 8: v1.DanhSachStringDoHiem
	(*DanhSachDoubleDoHiem)(nil),        // 9: v1.DanhSachDoubleDoHiem
	(*TimKiemDoHiemRequest)(nil),        // 10: v1.TimKiemDoHiemRequest
	(*wrapperspb.Int32Value)(nil),       // 11: google.protobuf.Int32Value
	(*wrapperspb.DoubleValue)(nil),      // 12: google.protobuf.DoubleValue
	(*emptypb.Empty)(nil),               // 13: google.protobuf.Empty
}
var file_v1_dohiem_proto_depIdxs = []int32{
	0,  // 0: v1.DanhSachDoHiem.items:type_name -> v1.DoHiem
	11, // 1: v1.TimKiemDoHiemRequest.ma_do_hiem:type_name -> google.protobuf.Int32Value
	11, // 2: v1.TimKiemDoHiemRequest.so_luong:type_name -> google.protobuf.Int32Value
	11, // 3: v1.TimKiemDoHiemRequest.min_so_luong:type_name -> google.protobuf.Int32Value
	11, // 4: v1.TimKiemDoHiemRequest.max_so_luong:type_name -> google.protobuf.Int32Value
	12, // 5: v1.TimKiemDoHiemRequest.sat_thuong_bonus:type_name -> google.protobuf.DoubleValue
	12, // 6: v1.TimKiemDoHiemRequest.min_sat_thuong_bonus:type_name -> google.protobuf.DoubleValue
	12, // 7: v1.TimKiemDoHiemRequest.max_sat_thuong_bonus:type_name -> google.protobuf.DoubleValue
	12, // 8: v1.TimKiemDoHiemRequest.toc_do_danh_bonus:type_name -> google.protobuf.DoubleValue
	12, // 9: v1.TimKiemDoHiemRequest.min_toc_do_danh_bonus:type_name -> google.protobuf.DoubleValue
	12, // 10: v1.TimKiemDoHiemRequest.max_toc_do_danh_bonus:type_name -> google.protobuf.DoubleValue
	11, // 11: v1.TimKiemDoHiemRequest.cap_bac:type_name -> google.protobuf.Int32Value
	11, // 12: v1.TimKiemDoHiemRequest.min_cap_bac:type_name -> google.protobuf.Int32Value
	11, // 13: v1.TimKiemDoHiemRequest.max_cap_bac:type_name -> google.protobuf.Int32Value
	1,  // 14: v1.DoHiemService.CreateDoHiem:input_type -> v1.TaoDoHiemRequest
	2,  // 15: v1.DoHiemService.UpdateByNameDoHiem:input_type -> v1.CapNhatTheoTenDoHiemRequest
	3,  // 16: v1.DoHiemService.DeleteByNameDoHiem:input_type -> v1.XoaTheoTenDoHiemRequest
	5,  // 17: v1.DoHiemService.GetAllDoHiem:input_type -> v1.LayTatCaDoHiemRequest
	13, // 18: v1.DoHiemService.GetAllTenDoHiem:input_type -> google.protobuf.Empty
	13, // 19: v1.DoHiemService.GetAllSoLuongDoHiem:input_type -> google.protobuf.Empty
	13, // 20: v1.DoHiemService.GetAllMauSacDoHiem:input_type -> google.protobuf.Empty
	13, // 21: v1.DoHiemService.GetAllSatThuongDoHiem:input_type -> google.protobuf.Empty
	13, // 22: v1.DoHiemService.GetAllTocDoDoHiem:input_type -> google.protobuf.Empty
	10, // 23: v1.DoHiemService.SearchDoHiem:input_type -> v1.TimKiemDoHiemRequest
	0,  // 24: v1.DoHiemService.CreateDoHiem:output_type -> v1.DoHiem
	0,  // 25: v1.DoHiemService.UpdateByNameDoHiem:output_type -> v1.DoHiem
	4,  // 26: v1.DoHiemService.DeleteByNameDoHiem:output_type -> v1.XoaTheoTenDoHiemResponse
	6,  // 27: v1.DoHiemService.GetAllDoHiem:output_type -> v1.DanhSachDoHiem
	8,  // 28: v1.DoHiemService.GetAllTenDoHiem:output_type -> v1.DanhSachStringDoHiem
	7,  // 29: v1.DoHiemService.GetAllSoLuongDoHiem:output_type -> v1.DanhSachIntDoHiem
	8,  // 30: v1.DoHiemService.GetAllMauSacDoHiem:output_type -> v1.DanhSachStringDoHiem
	9,  // 31: v1.DoHiemService.GetAllSatThuongDoHiem:output_type -> v1.DanhSachDoubleDoHiem
	9,  // 32: v1.DoHiemService.GetAllTocDoDoHiem:output_type -> v1.DanhSachDoubleDoHiem
	6,  // 33: v1.DoHiemService.SearchDoHiem:output_type -> v1.DanhSachDoHiem
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_dohiem_proto_init() }
func file_v1_dohiem_proto_init() {
	if File_v1_dohiem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_dohiem_proto_rawDesc), len(file_v1_dohiem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_dohiem_proto_goTypes,
		DependencyIndexes: file_v1_dohiem_proto_depIdxs,
		MessageInfos:      file_v1_dohiem_proto_msgTypes,
	}.Build()
	File_v1_dohiem_proto = out.File
	file_v1_dohiem_proto_goTypes = nil
	file_v1_dohiem_proto_depIdxs = nil
}
