// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: v1/loaivukhi.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoaiVuKhiService_CreateLoaiVuKhi_FullMethodName       = "/v1.LoaiVuKhiService/CreateLoaiVuKhi"
	LoaiVuKhiService_UpdateByNameLoaiVuKhi_FullMethodName = "/v1.LoaiVuKhiService/UpdateByNameLoaiVuKhi"
	LoaiVuKhiService_DeleteByNameLoaiVuKhi_FullMethodName = "/v1.LoaiVuKhiService/DeleteByNameLoaiVuKhi"
	LoaiVuKhiService_GetAllLoaiVuKhi_FullMethodName       = "/v1.LoaiVuKhiService/GetAllLoaiVuKhi"
	LoaiVuKhiService_GetAllTenLoaiVuKhi_FullMethodName    = "/v1.LoaiVuKhiService/GetAllTenLoaiVuKhi"
	LoaiVuKhiService_GetAllMoTaLoaiVuKhi_FullMethodName   = "/v1.LoaiVuKhiService/GetAllMoTaLoaiVuKhi"
	LoaiVuKhiService_SearchLoaiVuKhi_FullMethodName       = "/v1.LoaiVuKhiService/SearchLoaiVuKhi"
)

// LoaiVuKhiServiceClient is the client API for LoaiVuKhiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoaiVuKhiServiceClient interface {
	// POST /loaivukhi/ent/post
	CreateLoaiVuKhi(ctx context.Context, in *TaoLoaiVuKhiRequest, opts ...grpc.CallOption) (*LoaiVuKhi, error)
	// PUT /loaivukhi/ent/put-by-name/{name}
	UpdateByNameLoaiVuKhi(ctx context.Context, in *CapNhatTheoTenLoaiVuKhiRequest, opts ...grpc.CallOption) (*LoaiVuKhi, error)
	// DELETE /loaivukhi/ent/delete-by-name/{name}
	DeleteByNameLoaiVuKhi(ctx context.Context, in *XoaTheoTenLoaiVuKhiRequest, opts ...grpc.CallOption) (*XoaTheoTenLoaiVuKhiResponse, error)
	// GET /loaivukhi/ent/getall
	GetAllLoaiVuKhi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachLoaiVuKhi, error)
	// GET /loaivukhi/ent/ten
	GetAllTenLoaiVuKhi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachStringLoaiVuKhi, error)
	// GET /loaivukhi/ent/mota
	GetAllMoTaLoaiVuKhi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachStringLoaiVuKhi, error)
	// POST /loaivukhi/ent/search
	SearchLoaiVuKhi(ctx context.Context, in *TimKiemLoaiVuKhiRequest, opts ...grpc.CallOption) (*DanhSachLoaiVuKhi, error)
}

type loaiVuKhiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoaiVuKhiServiceClient(cc grpc.ClientConnInterface) LoaiVuKhiServiceClient {
	return &loaiVuKhiServiceClient{cc}
}

func (c *loaiVuKhiServiceClient) CreateLoaiVuKhi(ctx context.Context, in *TaoLoaiVuKhiRequest, opts ...grpc.CallOption) (*LoaiVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoaiVuKhi)
	err := c.cc.Invoke(ctx, LoaiVuKhiService_CreateLoaiVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaiVuKhiServiceClient) UpdateByNameLoaiVuKhi(ctx context.Context, in *CapNhatTheoTenLoaiVuKhiRequest, opts ...grpc.CallOption) (*LoaiVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoaiVuKhi)
	err := c.cc.Invoke(ctx, LoaiVuKhiService_UpdateByNameLoaiVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaiVuKhiServiceClient) DeleteByNameLoaiVuKhi(ctx context.Context, in *XoaTheoTenLoaiVuKhiRequest, opts ...grpc.CallOption) (*XoaTheoTenLoaiVuKhiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XoaTheoTenLoaiVuKhiResponse)
	err := c.cc.Invoke(ctx, LoaiVuKhiService_DeleteByNameLoaiVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaiVuKhiServiceClient) GetAllLoaiVuKhi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachLoaiVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachLoaiVuKhi)
	err := c.cc.Invoke(ctx, LoaiVuKhiService_GetAllLoaiVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaiVuKhiServiceClient) GetAllTenLoaiVuKhi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachStringLoaiVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachStringLoaiVuKhi)
	err := c.cc.Invoke(ctx, LoaiVuKhiService_GetAllTenLoaiVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaiVuKhiServiceClient) GetAllMoTaLoaiVuKhi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachStringLoaiVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachStringLoaiVuKhi)
	err := c.cc.Invoke(ctx, LoaiVuKhiService_GetAllMoTaLoaiVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaiVuKhiServiceClient) SearchLoaiVuKhi(ctx context.Context, in *TimKiemLoaiVuKhiRequest, opts ...grpc.CallOption) (*DanhSachLoaiVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachLoaiVuKhi)
	err := c.cc.Invoke(ctx, LoaiVuKhiService_SearchLoaiVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoaiVuKhiServiceServer is the server API for LoaiVuKhiService service.
// All implementations must embed UnimplementedLoaiVuKhiServiceServer
// for forward compatibility.
type LoaiVuKhiServiceServer interface {
	// POST /loaivukhi/ent/post
	CreateLoaiVuKhi(context.Context, *TaoLoaiVuKhiRequest) (*LoaiVuKhi, error)
	// PUT /loaivukhi/ent/put-by-name/{name}
	UpdateByNameLoaiVuKhi(context.Context, *CapNhatTheoTenLoaiVuKhiRequest) (*LoaiVuKhi, error)
	// DELETE /loaivukhi/ent/delete-by-name/{name}
	DeleteByNameLoaiVuKhi(context.Context, *XoaTheoTenLoaiVuKhiRequest) (*XoaTheoTenLoaiVuKhiResponse, error)
	// GET /loaivukhi/ent/getall
	GetAllLoaiVuKhi(context.Context, *emptypb.Empty) (*DanhSachLoaiVuKhi, error)
	// GET /loaivukhi/ent/ten
	GetAllTenLoaiVuKhi(context.Context, *emptypb.Empty) (*DanhSachStringLoaiVuKhi, error)
	// GET /loaivukhi/ent/mota
	GetAllMoTaLoaiVuKhi(context.Context, *emptypb.Empty) (*DanhSachStringLoaiVuKhi, error)
	// POST /loaivukhi/ent/search
	SearchLoaiVuKhi(context.Context, *TimKiemLoaiVuKhiRequest) (*DanhSachLoaiVuKhi, error)
	mustEmbedUnimplementedLoaiVuKhiServiceServer()
}

// UnimplementedLoaiVuKhiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoaiVuKhiServiceServer struct{}

func (UnimplementedLoaiVuKhiServiceServer) CreateLoaiVuKhi(context.Context, *TaoLoaiVuKhiRequest) (*LoaiVuKhi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoaiVuKhi not implemented")
}
func (UnimplementedLoaiVuKhiServiceServer) UpdateByNameLoaiVuKhi(context.Context, *CapNhatTheoTenLoaiVuKhiRequest) (*LoaiVuKhi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateByNameLoaiVuKhi not implemented")
}
func (UnimplementedLoaiVuKhiServiceServer) DeleteByNameLoaiVuKhi(context.Context, *XoaTheoTenLoaiVuKhiRequest) (*XoaTheoTenLoaiVuKhiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByNameLoaiVuKhi not implemented")
}
func (UnimplementedLoaiVuKhiServiceServer) GetAllLoaiVuKhi(context.Context, *emptypb.Empty) (*DanhSachLoaiVuKhi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllLoaiVuKhi not implemented")
}
func (UnimplementedLoaiVuKhiServiceServer) GetAllTenLoaiVuKhi(context.Context, *emptypb.Empty) (*DanhSachStringLoaiVuKhi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTenLoaiVuKhi not implemented")
}
func (UnimplementedLoaiVuKhiServiceServer) GetAllMoTaLoaiVuKhi(context.Context, *emptypb.Empty) (*DanhSachStringLoaiVuKhi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMoTaLoaiVuKhi not implemented")
}
func (UnimplementedLoaiVuKhiServiceServer) SearchLoaiVuKhi(context.Context, *TimKiemLoaiVuKhiRequest) (*DanhSachLoaiVuKhi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLoaiVuKhi not implemented")
}
func (UnimplementedLoaiVuKhiServiceServer) mustEmbedUnimplementedLoaiVuKhiServiceServer() {}
func (UnimplementedLoaiVuKhiServiceServer) testEmbeddedByValue()                          {}

// UnsafeLoaiVuKhiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoaiVuKhiServiceServer will
// result in compilation errors.
type UnsafeLoaiVuKhiServiceServer interface {
	mustEmbedUnimplementedLoaiVuKhiServiceServer()
}

func RegisterLoaiVuKhiServiceServer(s grpc.ServiceRegistrar, srv LoaiVuKhiServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoaiVuKhiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoaiVuKhiService_ServiceDesc, srv)
}

func _LoaiVuKhiService_CreateLoaiVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaoLoaiVuKhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaiVuKhiServiceServer).CreateLoaiVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoaiVuKhiService_CreateLoaiVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaiVuKhiServiceServer).CreateLoaiVuKhi(ctx, req.(*TaoLoaiVuKhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoaiVuKhiService_UpdateByNameLoaiVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapNhatTheoTenLoaiVuKhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaiVuKhiServiceServer).UpdateByNameLoaiVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoaiVuKhiService_UpdateByNameLoaiVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaiVuKhiServiceServer).UpdateByNameLoaiVuKhi(ctx, req.(*CapNhatTheoTenLoaiVuKhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoaiVuKhiService_DeleteByNameLoaiVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XoaTheoTenLoaiVuKhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaiVuKhiServiceServer).DeleteByNameLoaiVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoaiVuKhiService_DeleteByNameLoaiVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaiVuKhiServiceServer).DeleteByNameLoaiVuKhi(ctx, req.(*XoaTheoTenLoaiVuKhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoaiVuKhiService_GetAllLoaiVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaiVuKhiServiceServer).GetAllLoaiVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoaiVuKhiService_GetAllLoaiVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaiVuKhiServiceServer).GetAllLoaiVuKhi(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoaiVuKhiService_GetAllTenLoaiVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaiVuKhiServiceServer).GetAllTenLoaiVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoaiVuKhiService_GetAllTenLoaiVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaiVuKhiServiceServer).GetAllTenLoaiVuKhi(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoaiVuKhiService_GetAllMoTaLoaiVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaiVuKhiServiceServer).GetAllMoTaLoaiVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoaiVuKhiService_GetAllMoTaLoaiVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaiVuKhiServiceServer).GetAllMoTaLoaiVuKhi(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoaiVuKhiService_SearchLoaiVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimKiemLoaiVuKhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaiVuKhiServiceServer).SearchLoaiVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoaiVuKhiService_SearchLoaiVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaiVuKhiServiceServer).SearchLoaiVuKhi(ctx, req.(*TimKiemLoaiVuKhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoaiVuKhiService_ServiceDesc is the grpc.ServiceDesc for LoaiVuKhiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoaiVuKhiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.LoaiVuKhiService",
	HandlerType: (*LoaiVuKhiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoaiVuKhi",
			Handler:    _LoaiVuKhiService_CreateLoaiVuKhi_Handler,
		},
		{
			MethodName: "UpdateByNameLoaiVuKhi",
			Handler:    _LoaiVuKhiService_UpdateByNameLoaiVuKhi_Handler,
		},
		{
			MethodName: "DeleteByNameLoaiVuKhi",
			Handler:    _LoaiVuKhiService_DeleteByNameLoaiVuKhi_Handler,
		},
		{
			MethodName: "GetAllLoaiVuKhi",
			Handler:    _LoaiVuKhiService_GetAllLoaiVuKhi_Handler,
		},
		{
			MethodName: "GetAllTenLoaiVuKhi",
			Handler:    _LoaiVuKhiService_GetAllTenLoaiVuKhi_Handler,
		},
		{
			MethodName: "GetAllMoTaLoaiVuKhi",
			Handler:    _LoaiVuKhiService_GetAllMoTaLoaiVuKhi_Handler,
		},
		{
			MethodName: "SearchLoaiVuKhi",
			Handler:    _LoaiVuKhiService_SearchLoaiVuKhi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/loaivukhi.proto",
}
