// Code generated by ent, DO NOT EDIT.

package dohiem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dohiem type in the database.
	Label = "do_hiem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "ma_do_hiem"
	// FieldTenDoHiem holds the string denoting the ten_do_hiem field in the database.
	FieldTenDoHiem = "ten_do_hiem"
	// FieldSoLuong holds the string denoting the so_luong field in the database.
	FieldSoLuong = "so_luong"
	// FieldMauSac holds the string denoting the mau_sac field in the database.
	FieldMauSac = "mau_sac"
	// FieldSatThuongBonus holds the string denoting the sat_thuong_bonus field in the database.
	FieldSatThuongBonus = "sat_thuong_bonus"
	// FieldTocDoDanhBonus holds the string denoting the toc_do_danh_bonus field in the database.
	FieldTocDoDanhBonus = "toc_do_danh_bonus"
	// FieldCapBac holds the string denoting the cap_bac field in the database.
	FieldCapBac = "cap_bac"
	// EdgeVuKhi holds the string denoting the vu_khi edge name in mutations.
	EdgeVuKhi = "vu_khi"
	// VuKhiFieldID holds the string denoting the ID field of the VuKhi.
	VuKhiFieldID = "ma_vu_khi"
	// Table holds the table name of the dohiem in the database.
	Table = "do_hiems"
	// VuKhiTable is the table that holds the vu_khi relation/edge.
	VuKhiTable = "vu_khis"
	// VuKhiInverseTable is the table name for the VuKhi entity.
	// It exists in this package in order to avoid circular dependency with the "vukhi" package.
	VuKhiInverseTable = "vu_khis"
	// VuKhiColumn is the table column denoting the vu_khi relation/edge.
	VuKhiColumn = "ma_do_hiem"
)

// Columns holds all SQL columns for dohiem fields.
var Columns = []string{
	FieldID,
	FieldTenDoHiem,
	FieldSoLuong,
	FieldMauSac,
	FieldSatThuongBonus,
	FieldTocDoDanhBonus,
	FieldCapBac,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenDoHiemValidator is a validator for the "ten_do_hiem" field. It is called by the builders before save.
	TenDoHiemValidator func(string) error
	// DefaultSoLuong holds the default value on creation for the "so_luong" field.
	DefaultSoLuong int
	// MauSacValidator is a validator for the "mau_sac" field. It is called by the builders before save.
	MauSacValidator func(string) error
	// DefaultSatThuongBonus holds the default value on creation for the "sat_thuong_bonus" field.
	DefaultSatThuongBonus float64
	// DefaultTocDoDanhBonus holds the default value on creation for the "toc_do_danh_bonus" field.
	DefaultTocDoDanhBonus float64
)

// OrderOption defines the ordering options for the DoHiem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenDoHiem orders the results by the ten_do_hiem field.
func ByTenDoHiem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenDoHiem, opts...).ToFunc()
}

// BySoLuong orders the results by the so_luong field.
func BySoLuong(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSoLuong, opts...).ToFunc()
}

// ByMauSac orders the results by the mau_sac field.
func ByMauSac(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMauSac, opts...).ToFunc()
}

// BySatThuongBonus orders the results by the sat_thuong_bonus field.
func BySatThuongBonus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSatThuongBonus, opts...).ToFunc()
}

// ByTocDoDanhBonus orders the results by the toc_do_danh_bonus field.
func ByTocDoDanhBonus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTocDoDanhBonus, opts...).ToFunc()
}

// ByCapBac orders the results by the cap_bac field.
func ByCapBac(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapBac, opts...).ToFunc()
}

// ByVuKhiCount orders the results by vu_khi count.
func ByVuKhiCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVuKhiStep(), opts...)
	}
}

// ByVuKhi orders the results by vu_khi terms.
func ByVuKhi(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVuKhiStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVuKhiStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VuKhiInverseTable, VuKhiFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VuKhiTable, VuKhiColumn),
	)
}
