// Code generated by ent, DO NOT EDIT.

package dohiem

import (
	"game/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLTE(FieldID, id))
}

// TenDoHiem applies equality check predicate on the "ten_do_hiem" field. It's identical to TenDoHiemEQ.
func TenDoHiem(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldTenDoHiem, v))
}

// SoLuong applies equality check predicate on the "so_luong" field. It's identical to SoLuongEQ.
func SoLuong(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldSoLuong, v))
}

// MauSac applies equality check predicate on the "mau_sac" field. It's identical to MauSacEQ.
func MauSac(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldMauSac, v))
}

// SatThuongBonus applies equality check predicate on the "sat_thuong_bonus" field. It's identical to SatThuongBonusEQ.
func SatThuongBonus(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldSatThuongBonus, v))
}

// TocDoDanhBonus applies equality check predicate on the "toc_do_danh_bonus" field. It's identical to TocDoDanhBonusEQ.
func TocDoDanhBonus(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldTocDoDanhBonus, v))
}

// CapBac applies equality check predicate on the "cap_bac" field. It's identical to CapBacEQ.
func CapBac(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldCapBac, v))
}

// TenDoHiemEQ applies the EQ predicate on the "ten_do_hiem" field.
func TenDoHiemEQ(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldTenDoHiem, v))
}

// TenDoHiemNEQ applies the NEQ predicate on the "ten_do_hiem" field.
func TenDoHiemNEQ(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNEQ(FieldTenDoHiem, v))
}

// TenDoHiemIn applies the In predicate on the "ten_do_hiem" field.
func TenDoHiemIn(vs ...string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldIn(FieldTenDoHiem, vs...))
}

// TenDoHiemNotIn applies the NotIn predicate on the "ten_do_hiem" field.
func TenDoHiemNotIn(vs ...string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNotIn(FieldTenDoHiem, vs...))
}

// TenDoHiemGT applies the GT predicate on the "ten_do_hiem" field.
func TenDoHiemGT(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGT(FieldTenDoHiem, v))
}

// TenDoHiemGTE applies the GTE predicate on the "ten_do_hiem" field.
func TenDoHiemGTE(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGTE(FieldTenDoHiem, v))
}

// TenDoHiemLT applies the LT predicate on the "ten_do_hiem" field.
func TenDoHiemLT(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLT(FieldTenDoHiem, v))
}

// TenDoHiemLTE applies the LTE predicate on the "ten_do_hiem" field.
func TenDoHiemLTE(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLTE(FieldTenDoHiem, v))
}

// TenDoHiemContains applies the Contains predicate on the "ten_do_hiem" field.
func TenDoHiemContains(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldContains(FieldTenDoHiem, v))
}

// TenDoHiemHasPrefix applies the HasPrefix predicate on the "ten_do_hiem" field.
func TenDoHiemHasPrefix(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldHasPrefix(FieldTenDoHiem, v))
}

// TenDoHiemHasSuffix applies the HasSuffix predicate on the "ten_do_hiem" field.
func TenDoHiemHasSuffix(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldHasSuffix(FieldTenDoHiem, v))
}

// TenDoHiemEqualFold applies the EqualFold predicate on the "ten_do_hiem" field.
func TenDoHiemEqualFold(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEqualFold(FieldTenDoHiem, v))
}

// TenDoHiemContainsFold applies the ContainsFold predicate on the "ten_do_hiem" field.
func TenDoHiemContainsFold(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldContainsFold(FieldTenDoHiem, v))
}

// SoLuongEQ applies the EQ predicate on the "so_luong" field.
func SoLuongEQ(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldSoLuong, v))
}

// SoLuongNEQ applies the NEQ predicate on the "so_luong" field.
func SoLuongNEQ(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNEQ(FieldSoLuong, v))
}

// SoLuongIn applies the In predicate on the "so_luong" field.
func SoLuongIn(vs ...int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldIn(FieldSoLuong, vs...))
}

// SoLuongNotIn applies the NotIn predicate on the "so_luong" field.
func SoLuongNotIn(vs ...int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNotIn(FieldSoLuong, vs...))
}

// SoLuongGT applies the GT predicate on the "so_luong" field.
func SoLuongGT(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGT(FieldSoLuong, v))
}

// SoLuongGTE applies the GTE predicate on the "so_luong" field.
func SoLuongGTE(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGTE(FieldSoLuong, v))
}

// SoLuongLT applies the LT predicate on the "so_luong" field.
func SoLuongLT(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLT(FieldSoLuong, v))
}

// SoLuongLTE applies the LTE predicate on the "so_luong" field.
func SoLuongLTE(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLTE(FieldSoLuong, v))
}

// MauSacEQ applies the EQ predicate on the "mau_sac" field.
func MauSacEQ(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldMauSac, v))
}

// MauSacNEQ applies the NEQ predicate on the "mau_sac" field.
func MauSacNEQ(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNEQ(FieldMauSac, v))
}

// MauSacIn applies the In predicate on the "mau_sac" field.
func MauSacIn(vs ...string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldIn(FieldMauSac, vs...))
}

// MauSacNotIn applies the NotIn predicate on the "mau_sac" field.
func MauSacNotIn(vs ...string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNotIn(FieldMauSac, vs...))
}

// MauSacGT applies the GT predicate on the "mau_sac" field.
func MauSacGT(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGT(FieldMauSac, v))
}

// MauSacGTE applies the GTE predicate on the "mau_sac" field.
func MauSacGTE(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGTE(FieldMauSac, v))
}

// MauSacLT applies the LT predicate on the "mau_sac" field.
func MauSacLT(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLT(FieldMauSac, v))
}

// MauSacLTE applies the LTE predicate on the "mau_sac" field.
func MauSacLTE(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLTE(FieldMauSac, v))
}

// MauSacContains applies the Contains predicate on the "mau_sac" field.
func MauSacContains(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldContains(FieldMauSac, v))
}

// MauSacHasPrefix applies the HasPrefix predicate on the "mau_sac" field.
func MauSacHasPrefix(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldHasPrefix(FieldMauSac, v))
}

// MauSacHasSuffix applies the HasSuffix predicate on the "mau_sac" field.
func MauSacHasSuffix(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldHasSuffix(FieldMauSac, v))
}

// MauSacIsNil applies the IsNil predicate on the "mau_sac" field.
func MauSacIsNil() predicate.DoHiem {
	return predicate.DoHiem(sql.FieldIsNull(FieldMauSac))
}

// MauSacNotNil applies the NotNil predicate on the "mau_sac" field.
func MauSacNotNil() predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNotNull(FieldMauSac))
}

// MauSacEqualFold applies the EqualFold predicate on the "mau_sac" field.
func MauSacEqualFold(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEqualFold(FieldMauSac, v))
}

// MauSacContainsFold applies the ContainsFold predicate on the "mau_sac" field.
func MauSacContainsFold(v string) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldContainsFold(FieldMauSac, v))
}

// SatThuongBonusEQ applies the EQ predicate on the "sat_thuong_bonus" field.
func SatThuongBonusEQ(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldSatThuongBonus, v))
}

// SatThuongBonusNEQ applies the NEQ predicate on the "sat_thuong_bonus" field.
func SatThuongBonusNEQ(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNEQ(FieldSatThuongBonus, v))
}

// SatThuongBonusIn applies the In predicate on the "sat_thuong_bonus" field.
func SatThuongBonusIn(vs ...float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldIn(FieldSatThuongBonus, vs...))
}

// SatThuongBonusNotIn applies the NotIn predicate on the "sat_thuong_bonus" field.
func SatThuongBonusNotIn(vs ...float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNotIn(FieldSatThuongBonus, vs...))
}

// SatThuongBonusGT applies the GT predicate on the "sat_thuong_bonus" field.
func SatThuongBonusGT(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGT(FieldSatThuongBonus, v))
}

// SatThuongBonusGTE applies the GTE predicate on the "sat_thuong_bonus" field.
func SatThuongBonusGTE(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGTE(FieldSatThuongBonus, v))
}

// SatThuongBonusLT applies the LT predicate on the "sat_thuong_bonus" field.
func SatThuongBonusLT(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLT(FieldSatThuongBonus, v))
}

// SatThuongBonusLTE applies the LTE predicate on the "sat_thuong_bonus" field.
func SatThuongBonusLTE(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLTE(FieldSatThuongBonus, v))
}

// TocDoDanhBonusEQ applies the EQ predicate on the "toc_do_danh_bonus" field.
func TocDoDanhBonusEQ(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldTocDoDanhBonus, v))
}

// TocDoDanhBonusNEQ applies the NEQ predicate on the "toc_do_danh_bonus" field.
func TocDoDanhBonusNEQ(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNEQ(FieldTocDoDanhBonus, v))
}

// TocDoDanhBonusIn applies the In predicate on the "toc_do_danh_bonus" field.
func TocDoDanhBonusIn(vs ...float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldIn(FieldTocDoDanhBonus, vs...))
}

// TocDoDanhBonusNotIn applies the NotIn predicate on the "toc_do_danh_bonus" field.
func TocDoDanhBonusNotIn(vs ...float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNotIn(FieldTocDoDanhBonus, vs...))
}

// TocDoDanhBonusGT applies the GT predicate on the "toc_do_danh_bonus" field.
func TocDoDanhBonusGT(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGT(FieldTocDoDanhBonus, v))
}

// TocDoDanhBonusGTE applies the GTE predicate on the "toc_do_danh_bonus" field.
func TocDoDanhBonusGTE(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGTE(FieldTocDoDanhBonus, v))
}

// TocDoDanhBonusLT applies the LT predicate on the "toc_do_danh_bonus" field.
func TocDoDanhBonusLT(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLT(FieldTocDoDanhBonus, v))
}

// TocDoDanhBonusLTE applies the LTE predicate on the "toc_do_danh_bonus" field.
func TocDoDanhBonusLTE(v float64) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLTE(FieldTocDoDanhBonus, v))
}

// CapBacEQ applies the EQ predicate on the "cap_bac" field.
func CapBacEQ(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldEQ(FieldCapBac, v))
}

// CapBacNEQ applies the NEQ predicate on the "cap_bac" field.
func CapBacNEQ(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNEQ(FieldCapBac, v))
}

// CapBacIn applies the In predicate on the "cap_bac" field.
func CapBacIn(vs ...int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldIn(FieldCapBac, vs...))
}

// CapBacNotIn applies the NotIn predicate on the "cap_bac" field.
func CapBacNotIn(vs ...int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldNotIn(FieldCapBac, vs...))
}

// CapBacGT applies the GT predicate on the "cap_bac" field.
func CapBacGT(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGT(FieldCapBac, v))
}

// CapBacGTE applies the GTE predicate on the "cap_bac" field.
func CapBacGTE(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldGTE(FieldCapBac, v))
}

// CapBacLT applies the LT predicate on the "cap_bac" field.
func CapBacLT(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLT(FieldCapBac, v))
}

// CapBacLTE applies the LTE predicate on the "cap_bac" field.
func CapBacLTE(v int) predicate.DoHiem {
	return predicate.DoHiem(sql.FieldLTE(FieldCapBac, v))
}

// HasVuKhi applies the HasEdge predicate on the "vu_khi" edge.
func HasVuKhi() predicate.DoHiem {
	return predicate.DoHiem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VuKhiTable, VuKhiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVuKhiWith applies the HasEdge predicate on the "vu_khi" edge with a given conditions (other predicates).
func HasVuKhiWith(preds ...predicate.VuKhi) predicate.DoHiem {
	return predicate.DoHiem(func(s *sql.Selector) {
		step := newVuKhiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DoHiem) predicate.DoHiem {
	return predicate.DoHiem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DoHiem) predicate.DoHiem {
	return predicate.DoHiem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DoHiem) predicate.DoHiem {
	return predicate.DoHiem(sql.NotPredicates(p))
}
