// Code generated by ent, DO NOT EDIT.

package vukhi

import (
	"game/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLTE(FieldID, id))
}

// TenVuKhi applies equality check predicate on the "ten_vu_khi" field. It's identical to TenVuKhiEQ.
func TenVuKhi(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldTenVuKhi, v))
}

// SatThuongCoBan applies equality check predicate on the "sat_thuong_co_ban" field. It's identical to SatThuongCoBanEQ.
func SatThuongCoBan(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldSatThuongCoBan, v))
}

// TocDoDanh applies equality check predicate on the "toc_do_danh" field. It's identical to TocDoDanhEQ.
func TocDoDanh(v float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldTocDoDanh, v))
}

// TamDanh applies equality check predicate on the "tam_danh" field. It's identical to TamDanhEQ.
func TamDanh(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldTamDanh, v))
}

// MoTa applies equality check predicate on the "mo_ta" field. It's identical to MoTaEQ.
func MoTa(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldMoTa, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldVersion, v))
}

// MaLoaiVuKhi applies equality check predicate on the "ma_loai_vu_khi" field. It's identical to MaLoaiVuKhiEQ.
func MaLoaiVuKhi(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldMaLoaiVuKhi, v))
}

// MaDoHiem applies equality check predicate on the "ma_do_hiem" field. It's identical to MaDoHiemEQ.
func MaDoHiem(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldMaDoHiem, v))
}

// MaHe applies equality check predicate on the "ma_he" field. It's identical to MaHeEQ.
func MaHe(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldMaHe, v))
}

// TenVuKhiEQ applies the EQ predicate on the "ten_vu_khi" field.
func TenVuKhiEQ(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldTenVuKhi, v))
}

// TenVuKhiNEQ applies the NEQ predicate on the "ten_vu_khi" field.
func TenVuKhiNEQ(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldTenVuKhi, v))
}

// TenVuKhiIn applies the In predicate on the "ten_vu_khi" field.
func TenVuKhiIn(vs ...string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldTenVuKhi, vs...))
}

// TenVuKhiNotIn applies the NotIn predicate on the "ten_vu_khi" field.
func TenVuKhiNotIn(vs ...string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldTenVuKhi, vs...))
}

// TenVuKhiGT applies the GT predicate on the "ten_vu_khi" field.
func TenVuKhiGT(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGT(FieldTenVuKhi, v))
}

// TenVuKhiGTE applies the GTE predicate on the "ten_vu_khi" field.
func TenVuKhiGTE(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGTE(FieldTenVuKhi, v))
}

// TenVuKhiLT applies the LT predicate on the "ten_vu_khi" field.
func TenVuKhiLT(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLT(FieldTenVuKhi, v))
}

// TenVuKhiLTE applies the LTE predicate on the "ten_vu_khi" field.
func TenVuKhiLTE(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLTE(FieldTenVuKhi, v))
}

// TenVuKhiContains applies the Contains predicate on the "ten_vu_khi" field.
func TenVuKhiContains(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldContains(FieldTenVuKhi, v))
}

// TenVuKhiHasPrefix applies the HasPrefix predicate on the "ten_vu_khi" field.
func TenVuKhiHasPrefix(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldHasPrefix(FieldTenVuKhi, v))
}

// TenVuKhiHasSuffix applies the HasSuffix predicate on the "ten_vu_khi" field.
func TenVuKhiHasSuffix(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldHasSuffix(FieldTenVuKhi, v))
}

// TenVuKhiEqualFold applies the EqualFold predicate on the "ten_vu_khi" field.
func TenVuKhiEqualFold(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEqualFold(FieldTenVuKhi, v))
}

// TenVuKhiContainsFold applies the ContainsFold predicate on the "ten_vu_khi" field.
func TenVuKhiContainsFold(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldContainsFold(FieldTenVuKhi, v))
}

// SatThuongCoBanEQ applies the EQ predicate on the "sat_thuong_co_ban" field.
func SatThuongCoBanEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldSatThuongCoBan, v))
}

// SatThuongCoBanNEQ applies the NEQ predicate on the "sat_thuong_co_ban" field.
func SatThuongCoBanNEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldSatThuongCoBan, v))
}

// SatThuongCoBanIn applies the In predicate on the "sat_thuong_co_ban" field.
func SatThuongCoBanIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldSatThuongCoBan, vs...))
}

// SatThuongCoBanNotIn applies the NotIn predicate on the "sat_thuong_co_ban" field.
func SatThuongCoBanNotIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldSatThuongCoBan, vs...))
}

// SatThuongCoBanGT applies the GT predicate on the "sat_thuong_co_ban" field.
func SatThuongCoBanGT(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGT(FieldSatThuongCoBan, v))
}

// SatThuongCoBanGTE applies the GTE predicate on the "sat_thuong_co_ban" field.
func SatThuongCoBanGTE(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGTE(FieldSatThuongCoBan, v))
}

// SatThuongCoBanLT applies the LT predicate on the "sat_thuong_co_ban" field.
func SatThuongCoBanLT(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLT(FieldSatThuongCoBan, v))
}

// SatThuongCoBanLTE applies the LTE predicate on the "sat_thuong_co_ban" field.
func SatThuongCoBanLTE(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLTE(FieldSatThuongCoBan, v))
}

// TocDoDanhEQ applies the EQ predicate on the "toc_do_danh" field.
func TocDoDanhEQ(v float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldTocDoDanh, v))
}

// TocDoDanhNEQ applies the NEQ predicate on the "toc_do_danh" field.
func TocDoDanhNEQ(v float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldTocDoDanh, v))
}

// TocDoDanhIn applies the In predicate on the "toc_do_danh" field.
func TocDoDanhIn(vs ...float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldTocDoDanh, vs...))
}

// TocDoDanhNotIn applies the NotIn predicate on the "toc_do_danh" field.
func TocDoDanhNotIn(vs ...float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldTocDoDanh, vs...))
}

// TocDoDanhGT applies the GT predicate on the "toc_do_danh" field.
func TocDoDanhGT(v float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGT(FieldTocDoDanh, v))
}

// TocDoDanhGTE applies the GTE predicate on the "toc_do_danh" field.
func TocDoDanhGTE(v float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGTE(FieldTocDoDanh, v))
}

// TocDoDanhLT applies the LT predicate on the "toc_do_danh" field.
func TocDoDanhLT(v float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLT(FieldTocDoDanh, v))
}

// TocDoDanhLTE applies the LTE predicate on the "toc_do_danh" field.
func TocDoDanhLTE(v float64) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLTE(FieldTocDoDanh, v))
}

// TamDanhEQ applies the EQ predicate on the "tam_danh" field.
func TamDanhEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldTamDanh, v))
}

// TamDanhNEQ applies the NEQ predicate on the "tam_danh" field.
func TamDanhNEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldTamDanh, v))
}

// TamDanhIn applies the In predicate on the "tam_danh" field.
func TamDanhIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldTamDanh, vs...))
}

// TamDanhNotIn applies the NotIn predicate on the "tam_danh" field.
func TamDanhNotIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldTamDanh, vs...))
}

// TamDanhGT applies the GT predicate on the "tam_danh" field.
func TamDanhGT(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGT(FieldTamDanh, v))
}

// TamDanhGTE applies the GTE predicate on the "tam_danh" field.
func TamDanhGTE(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGTE(FieldTamDanh, v))
}

// TamDanhLT applies the LT predicate on the "tam_danh" field.
func TamDanhLT(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLT(FieldTamDanh, v))
}

// TamDanhLTE applies the LTE predicate on the "tam_danh" field.
func TamDanhLTE(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLTE(FieldTamDanh, v))
}

// MoTaEQ applies the EQ predicate on the "mo_ta" field.
func MoTaEQ(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldMoTa, v))
}

// MoTaNEQ applies the NEQ predicate on the "mo_ta" field.
func MoTaNEQ(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldMoTa, v))
}

// MoTaIn applies the In predicate on the "mo_ta" field.
func MoTaIn(vs ...string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldMoTa, vs...))
}

// MoTaNotIn applies the NotIn predicate on the "mo_ta" field.
func MoTaNotIn(vs ...string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldMoTa, vs...))
}

// MoTaGT applies the GT predicate on the "mo_ta" field.
func MoTaGT(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGT(FieldMoTa, v))
}

// MoTaGTE applies the GTE predicate on the "mo_ta" field.
func MoTaGTE(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGTE(FieldMoTa, v))
}

// MoTaLT applies the LT predicate on the "mo_ta" field.
func MoTaLT(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLT(FieldMoTa, v))
}

// MoTaLTE applies the LTE predicate on the "mo_ta" field.
func MoTaLTE(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLTE(FieldMoTa, v))
}

// MoTaContains applies the Contains predicate on the "mo_ta" field.
func MoTaContains(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldContains(FieldMoTa, v))
}

// MoTaHasPrefix applies the HasPrefix predicate on the "mo_ta" field.
func MoTaHasPrefix(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldHasPrefix(FieldMoTa, v))
}

// MoTaHasSuffix applies the HasSuffix predicate on the "mo_ta" field.
func MoTaHasSuffix(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldHasSuffix(FieldMoTa, v))
}

// MoTaIsNil applies the IsNil predicate on the "mo_ta" field.
func MoTaIsNil() predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIsNull(FieldMoTa))
}

// MoTaNotNil applies the NotNil predicate on the "mo_ta" field.
func MoTaNotNil() predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotNull(FieldMoTa))
}

// MoTaEqualFold applies the EqualFold predicate on the "mo_ta" field.
func MoTaEqualFold(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEqualFold(FieldMoTa, v))
}

// MoTaContainsFold applies the ContainsFold predicate on the "mo_ta" field.
func MoTaContainsFold(v string) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldContainsFold(FieldMoTa, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldLTE(FieldVersion, v))
}

// MaLoaiVuKhiEQ applies the EQ predicate on the "ma_loai_vu_khi" field.
func MaLoaiVuKhiEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldMaLoaiVuKhi, v))
}

// MaLoaiVuKhiNEQ applies the NEQ predicate on the "ma_loai_vu_khi" field.
func MaLoaiVuKhiNEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldMaLoaiVuKhi, v))
}

// MaLoaiVuKhiIn applies the In predicate on the "ma_loai_vu_khi" field.
func MaLoaiVuKhiIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldMaLoaiVuKhi, vs...))
}

// MaLoaiVuKhiNotIn applies the NotIn predicate on the "ma_loai_vu_khi" field.
func MaLoaiVuKhiNotIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldMaLoaiVuKhi, vs...))
}

// MaDoHiemEQ applies the EQ predicate on the "ma_do_hiem" field.
func MaDoHiemEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldMaDoHiem, v))
}

// MaDoHiemNEQ applies the NEQ predicate on the "ma_do_hiem" field.
func MaDoHiemNEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldMaDoHiem, v))
}

// MaDoHiemIn applies the In predicate on the "ma_do_hiem" field.
func MaDoHiemIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldMaDoHiem, vs...))
}

// MaDoHiemNotIn applies the NotIn predicate on the "ma_do_hiem" field.
func MaDoHiemNotIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldMaDoHiem, vs...))
}

// MaHeEQ applies the EQ predicate on the "ma_he" field.
func MaHeEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldEQ(FieldMaHe, v))
}

// MaHeNEQ applies the NEQ predicate on the "ma_he" field.
func MaHeNEQ(v int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNEQ(FieldMaHe, v))
}

// MaHeIn applies the In predicate on the "ma_he" field.
func MaHeIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldIn(FieldMaHe, vs...))
}

// MaHeNotIn applies the NotIn predicate on the "ma_he" field.
func MaHeNotIn(vs ...int) predicate.VuKhi {
	return predicate.VuKhi(sql.FieldNotIn(FieldMaHe, vs...))
}

// HasLoai applies the HasEdge predicate on the "loai" edge.
func HasLoai() predicate.VuKhi {
	return predicate.VuKhi(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LoaiTable, LoaiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLoaiWith applies the HasEdge predicate on the "loai" edge with a given conditions (other predicates).
func HasLoaiWith(preds ...predicate.LoaiVuKhi) predicate.VuKhi {
	return predicate.VuKhi(func(s *sql.Selector) {
		step := newLoaiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDoHiem applies the HasEdge predicate on the "do_hiem" edge.
func HasDoHiem() predicate.VuKhi {
	return predicate.VuKhi(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DoHiemTable, DoHiemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDoHiemWith applies the HasEdge predicate on the "do_hiem" edge with a given conditions (other predicates).
func HasDoHiemWith(preds ...predicate.DoHiem) predicate.VuKhi {
	return predicate.VuKhi(func(s *sql.Selector) {
		step := newDoHiemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHe applies the HasEdge predicate on the "he" edge.
func HasHe() predicate.VuKhi {
	return predicate.VuKhi(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HeTable, HeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHeWith applies the HasEdge predicate on the "he" edge with a given conditions (other predicates).
func HasHeWith(preds ...predicate.He) predicate.VuKhi {
	return predicate.VuKhi(func(s *sql.Selector) {
		step := newHeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VuKhi) predicate.VuKhi {
	return predicate.VuKhi(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VuKhi) predicate.VuKhi {
	return predicate.VuKhi(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VuKhi) predicate.VuKhi {
	return predicate.VuKhi(sql.NotPredicates(p))
}
