// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"game/ent/dohiem"
	"game/ent/predicate"
	"game/ent/vukhi"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DoHiemUpdate is the builder for updating DoHiem entities.
type DoHiemUpdate struct {
	config
	hooks     []Hook
	mutation  *DoHiemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DoHiemUpdate builder.
func (_u *DoHiemUpdate) Where(ps ...predicate.DoHiem) *DoHiemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenDoHiem sets the "ten_do_hiem" field.
func (_u *DoHiemUpdate) SetTenDoHiem(v string) *DoHiemUpdate {
	_u.mutation.SetTenDoHiem(v)
	return _u
}

// SetNillableTenDoHiem sets the "ten_do_hiem" field if the given value is not nil.
func (_u *DoHiemUpdate) SetNillableTenDoHiem(v *string) *DoHiemUpdate {
	if v != nil {
		_u.SetTenDoHiem(*v)
	}
	return _u
}

// SetSoLuong sets the "so_luong" field.
func (_u *DoHiemUpdate) SetSoLuong(v int) *DoHiemUpdate {
	_u.mutation.ResetSoLuong()
	_u.mutation.SetSoLuong(v)
	return _u
}

// SetNillableSoLuong sets the "so_luong" field if the given value is not nil.
func (_u *DoHiemUpdate) SetNillableSoLuong(v *int) *DoHiemUpdate {
	if v != nil {
		_u.SetSoLuong(*v)
	}
	return _u
}

// AddSoLuong adds value to the "so_luong" field.
func (_u *DoHiemUpdate) AddSoLuong(v int) *DoHiemUpdate {
	_u.mutation.AddSoLuong(v)
	return _u
}

// SetMauSac sets the "mau_sac" field.
func (_u *DoHiemUpdate) SetMauSac(v string) *DoHiemUpdate {
	_u.mutation.SetMauSac(v)
	return _u
}

// SetNillableMauSac sets the "mau_sac" field if the given value is not nil.
func (_u *DoHiemUpdate) SetNillableMauSac(v *string) *DoHiemUpdate {
	if v != nil {
		_u.SetMauSac(*v)
	}
	return _u
}

// ClearMauSac clears the value of the "mau_sac" field.
func (_u *DoHiemUpdate) ClearMauSac() *DoHiemUpdate {
	_u.mutation.ClearMauSac()
	return _u
}

// SetSatThuongBonus sets the "sat_thuong_bonus" field.
func (_u *DoHiemUpdate) SetSatThuongBonus(v float64) *DoHiemUpdate {
	_u.mutation.ResetSatThuongBonus()
	_u.mutation.SetSatThuongBonus(v)
	return _u
}

// SetNillableSatThuongBonus sets the "sat_thuong_bonus" field if the given value is not nil.
func (_u *DoHiemUpdate) SetNillableSatThuongBonus(v *float64) *DoHiemUpdate {
	if v != nil {
		_u.SetSatThuongBonus(*v)
	}
	return _u
}

// AddSatThuongBonus adds value to the "sat_thuong_bonus" field.
func (_u *DoHiemUpdate) AddSatThuongBonus(v float64) *DoHiemUpdate {
	_u.mutation.AddSatThuongBonus(v)
	return _u
}

// SetTocDoDanhBonus sets the "toc_do_danh_bonus" field.
func (_u *DoHiemUpdate) SetTocDoDanhBonus(v float64) *DoHiemUpdate {
	_u.mutation.ResetTocDoDanhBonus()
	_u.mutation.SetTocDoDanhBonus(v)
	return _u
}

// SetNillableTocDoDanhBonus sets the "toc_do_danh_bonus" field if the given value is not nil.
func (_u *DoHiemUpdate) SetNillableTocDoDanhBonus(v *float64) *DoHiemUpdate {
	if v != nil {
		_u.SetTocDoDanhBonus(*v)
	}
	return _u
}

// AddTocDoDanhBonus adds value to the "toc_do_danh_bonus" field.
func (_u *DoHiemUpdate) AddTocDoDanhBonus(v float64) *DoHiemUpdate {
	_u.mutation.AddTocDoDanhBonus(v)
	return _u
}

// SetCapBac sets the "cap_bac" field.
func (_u *DoHiemUpdate) SetCapBac(v int) *DoHiemUpdate {
	_u.mutation.ResetCapBac()
	_u.mutation.SetCapBac(v)
	return _u
}

// SetNillableCapBac sets the "cap_bac" field if the given value is not nil.
func (_u *DoHiemUpdate) SetNillableCapBac(v *int) *DoHiemUpdate {
	if v != nil {
		_u.SetCapBac(*v)
	}
	return _u
}

// AddCapBac adds value to the "cap_bac" field.
func (_u *DoHiemUpdate) AddCapBac(v int) *DoHiemUpdate {
	_u.mutation.AddCapBac(v)
	return _u
}

// AddVuKhiIDs adds the "vu_khi" edge to the VuKhi entity by IDs.
func (_u *DoHiemUpdate) AddVuKhiIDs(ids ...int) *DoHiemUpdate {
	_u.mutation.AddVuKhiIDs(ids...)
	return _u
}

// AddVuKhi adds the "vu_khi" edges to the VuKhi entity.
func (_u *DoHiemUpdate) AddVuKhi(v ...*VuKhi) *DoHiemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVuKhiIDs(ids...)
}

// Mutation returns the DoHiemMutation object of the builder.
func (_u *DoHiemUpdate) Mutation() *DoHiemMutation {
	return _u.mutation
}

// ClearVuKhi clears all "vu_khi" edges to the VuKhi entity.
func (_u *DoHiemUpdate) ClearVuKhi() *DoHiemUpdate {
	_u.mutation.ClearVuKhi()
	return _u
}

// RemoveVuKhiIDs removes the "vu_khi" edge to VuKhi entities by IDs.
func (_u *DoHiemUpdate) RemoveVuKhiIDs(ids ...int) *DoHiemUpdate {
	_u.mutation.RemoveVuKhiIDs(ids...)
	return _u
}

// RemoveVuKhi removes "vu_khi" edges to VuKhi entities.
func (_u *DoHiemUpdate) RemoveVuKhi(v ...*VuKhi) *DoHiemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVuKhiIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DoHiemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DoHiemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DoHiemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DoHiemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DoHiemUpdate) check() error {
	if v, ok := _u.mutation.TenDoHiem(); ok {
		if err := dohiem.TenDoHiemValidator(v); err != nil {
			return &ValidationError{Name: "ten_do_hiem", err: fmt.Errorf(`ent: validator failed for field "DoHiem.ten_do_hiem": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MauSac(); ok {
		if err := dohiem.MauSacValidator(v); err != nil {
			return &ValidationError{Name: "mau_sac", err: fmt.Errorf(`ent: validator failed for field "DoHiem.mau_sac": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DoHiemUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DoHiemUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DoHiemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dohiem.Table, dohiem.Columns, sqlgraph.NewFieldSpec(dohiem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenDoHiem(); ok {
		_spec.SetField(dohiem.FieldTenDoHiem, field.TypeString, value)
	}
	if value, ok := _u.mutation.SoLuong(); ok {
		_spec.SetField(dohiem.FieldSoLuong, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSoLuong(); ok {
		_spec.AddField(dohiem.FieldSoLuong, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MauSac(); ok {
		_spec.SetField(dohiem.FieldMauSac, field.TypeString, value)
	}
	if _u.mutation.MauSacCleared() {
		_spec.ClearField(dohiem.FieldMauSac, field.TypeString)
	}
	if value, ok := _u.mutation.SatThuongBonus(); ok {
		_spec.SetField(dohiem.FieldSatThuongBonus, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSatThuongBonus(); ok {
		_spec.AddField(dohiem.FieldSatThuongBonus, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TocDoDanhBonus(); ok {
		_spec.SetField(dohiem.FieldTocDoDanhBonus, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTocDoDanhBonus(); ok {
		_spec.AddField(dohiem.FieldTocDoDanhBonus, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CapBac(); ok {
		_spec.SetField(dohiem.FieldCapBac, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapBac(); ok {
		_spec.AddField(dohiem.FieldCapBac, field.TypeInt, value)
	}
	if _u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dohiem.VuKhiTable,
			Columns: []string{dohiem.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVuKhiIDs(); len(nodes) > 0 && !_u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dohiem.VuKhiTable,
			Columns: []string{dohiem.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VuKhiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dohiem.VuKhiTable,
			Columns: []string{dohiem.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dohiem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DoHiemUpdateOne is the builder for updating a single DoHiem entity.
type DoHiemUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DoHiemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTenDoHiem sets the "ten_do_hiem" field.
func (_u *DoHiemUpdateOne) SetTenDoHiem(v string) *DoHiemUpdateOne {
	_u.mutation.SetTenDoHiem(v)
	return _u
}

// SetNillableTenDoHiem sets the "ten_do_hiem" field if the given value is not nil.
func (_u *DoHiemUpdateOne) SetNillableTenDoHiem(v *string) *DoHiemUpdateOne {
	if v != nil {
		_u.SetTenDoHiem(*v)
	}
	return _u
}

// SetSoLuong sets the "so_luong" field.
func (_u *DoHiemUpdateOne) SetSoLuong(v int) *DoHiemUpdateOne {
	_u.mutation.ResetSoLuong()
	_u.mutation.SetSoLuong(v)
	return _u
}

// SetNillableSoLuong sets the "so_luong" field if the given value is not nil.
func (_u *DoHiemUpdateOne) SetNillableSoLuong(v *int) *DoHiemUpdateOne {
	if v != nil {
		_u.SetSoLuong(*v)
	}
	return _u
}

// AddSoLuong adds value to the "so_luong" field.
func (_u *DoHiemUpdateOne) AddSoLuong(v int) *DoHiemUpdateOne {
	_u.mutation.AddSoLuong(v)
	return _u
}

// SetMauSac sets the "mau_sac" field.
func (_u *DoHiemUpdateOne) SetMauSac(v string) *DoHiemUpdateOne {
	_u.mutation.SetMauSac(v)
	return _u
}

// SetNillableMauSac sets the "mau_sac" field if the given value is not nil.
func (_u *DoHiemUpdateOne) SetNillableMauSac(v *string) *DoHiemUpdateOne {
	if v != nil {
		_u.SetMauSac(*v)
	}
	return _u
}

// ClearMauSac clears the value of the "mau_sac" field.
func (_u *DoHiemUpdateOne) ClearMauSac() *DoHiemUpdateOne {
	_u.mutation.ClearMauSac()
	return _u
}

// SetSatThuongBonus sets the "sat_thuong_bonus" field.
func (_u *DoHiemUpdateOne) SetSatThuongBonus(v float64) *DoHiemUpdateOne {
	_u.mutation.ResetSatThuongBonus()
	_u.mutation.SetSatThuongBonus(v)
	return _u
}

// SetNillableSatThuongBonus sets the "sat_thuong_bonus" field if the given value is not nil.
func (_u *DoHiemUpdateOne) SetNillableSatThuongBonus(v *float64) *DoHiemUpdateOne {
	if v != nil {
		_u.SetSatThuongBonus(*v)
	}
	return _u
}

// AddSatThuongBonus adds value to the "sat_thuong_bonus" field.
func (_u *DoHiemUpdateOne) AddSatThuongBonus(v float64) *DoHiemUpdateOne {
	_u.mutation.AddSatThuongBonus(v)
	return _u
}

// SetTocDoDanhBonus sets the "toc_do_danh_bonus" field.
func (_u *DoHiemUpdateOne) SetTocDoDanhBonus(v float64) *DoHiemUpdateOne {
	_u.mutation.ResetTocDoDanhBonus()
	_u.mutation.SetTocDoDanhBonus(v)
	return _u
}

// SetNillableTocDoDanhBonus sets the "toc_do_danh_bonus" field if the given value is not nil.
func (_u *DoHiemUpdateOne) SetNillableTocDoDanhBonus(v *float64) *DoHiemUpdateOne {
	if v != nil {
		_u.SetTocDoDanhBonus(*v)
	}
	return _u
}

// AddTocDoDanhBonus adds value to the "toc_do_danh_bonus" field.
func (_u *DoHiemUpdateOne) AddTocDoDanhBonus(v float64) *DoHiemUpdateOne {
	_u.mutation.AddTocDoDanhBonus(v)
	return _u
}

// SetCapBac sets the "cap_bac" field.
func (_u *DoHiemUpdateOne) SetCapBac(v int) *DoHiemUpdateOne {
	_u.mutation.ResetCapBac()
	_u.mutation.SetCapBac(v)
	return _u
}

// SetNillableCapBac sets the "cap_bac" field if the given value is not nil.
func (_u *DoHiemUpdateOne) SetNillableCapBac(v *int) *DoHiemUpdateOne {
	if v != nil {
		_u.SetCapBac(*v)
	}
	return _u
}

// AddCapBac adds value to the "cap_bac" field.
func (_u *DoHiemUpdateOne) AddCapBac(v int) *DoHiemUpdateOne {
	_u.mutation.AddCapBac(v)
	return _u
}

// AddVuKhiIDs adds the "vu_khi" edge to the VuKhi entity by IDs.
func (_u *DoHiemUpdateOne) AddVuKhiIDs(ids ...int) *DoHiemUpdateOne {
	_u.mutation.AddVuKhiIDs(ids...)
	return _u
}

// AddVuKhi adds the "vu_khi" edges to the VuKhi entity.
func (_u *DoHiemUpdateOne) AddVuKhi(v ...*VuKhi) *DoHiemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVuKhiIDs(ids...)
}

// Mutation returns the DoHiemMutation object of the builder.
func (_u *DoHiemUpdateOne) Mutation() *DoHiemMutation {
	return _u.mutation
}

// ClearVuKhi clears all "vu_khi" edges to the VuKhi entity.
func (_u *DoHiemUpdateOne) ClearVuKhi() *DoHiemUpdateOne {
	_u.mutation.ClearVuKhi()
	return _u
}

// RemoveVuKhiIDs removes the "vu_khi" edge to VuKhi entities by IDs.
func (_u *DoHiemUpdateOne) RemoveVuKhiIDs(ids ...int) *DoHiemUpdateOne {
	_u.mutation.RemoveVuKhiIDs(ids...)
	return _u
}

// RemoveVuKhi removes "vu_khi" edges to VuKhi entities.
func (_u *DoHiemUpdateOne) RemoveVuKhi(v ...*VuKhi) *DoHiemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVuKhiIDs(ids...)
}

// Where appends a list predicates to the DoHiemUpdate builder.
func (_u *DoHiemUpdateOne) Where(ps ...predicate.DoHiem) *DoHiemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DoHiemUpdateOne) Select(field string, fields ...string) *DoHiemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DoHiem entity.
func (_u *DoHiemUpdateOne) Save(ctx context.Context) (*DoHiem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DoHiemUpdateOne) SaveX(ctx context.Context) *DoHiem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DoHiemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DoHiemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DoHiemUpdateOne) check() error {
	if v, ok := _u.mutation.TenDoHiem(); ok {
		if err := dohiem.TenDoHiemValidator(v); err != nil {
			return &ValidationError{Name: "ten_do_hiem", err: fmt.Errorf(`ent: validator failed for field "DoHiem.ten_do_hiem": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MauSac(); ok {
		if err := dohiem.MauSacValidator(v); err != nil {
			return &ValidationError{Name: "mau_sac", err: fmt.Errorf(`ent: validator failed for field "DoHiem.mau_sac": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DoHiemUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DoHiemUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DoHiemUpdateOne) sqlSave(ctx context.Context) (_node *DoHiem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dohiem.Table, dohiem.Columns, sqlgraph.NewFieldSpec(dohiem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DoHiem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dohiem.FieldID)
		for _, f := range fields {
			if !dohiem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dohiem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenDoHiem(); ok {
		_spec.SetField(dohiem.FieldTenDoHiem, field.TypeString, value)
	}
	if value, ok := _u.mutation.SoLuong(); ok {
		_spec.SetField(dohiem.FieldSoLuong, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSoLuong(); ok {
		_spec.AddField(dohiem.FieldSoLuong, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MauSac(); ok {
		_spec.SetField(dohiem.FieldMauSac, field.TypeString, value)
	}
	if _u.mutation.MauSacCleared() {
		_spec.ClearField(dohiem.FieldMauSac, field.TypeString)
	}
	if value, ok := _u.mutation.SatThuongBonus(); ok {
		_spec.SetField(dohiem.FieldSatThuongBonus, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSatThuongBonus(); ok {
		_spec.AddField(dohiem.FieldSatThuongBonus, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TocDoDanhBonus(); ok {
		_spec.SetField(dohiem.FieldTocDoDanhBonus, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTocDoDanhBonus(); ok {
		_spec.AddField(dohiem.FieldTocDoDanhBonus, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CapBac(); ok {
		_spec.SetField(dohiem.FieldCapBac, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapBac(); ok {
		_spec.AddField(dohiem.FieldCapBac, field.TypeInt, value)
	}
	if _u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dohiem.VuKhiTable,
			Columns: []string{dohiem.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVuKhiIDs(); len(nodes) > 0 && !_u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dohiem.VuKhiTable,
			Columns: []string{dohiem.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VuKhiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dohiem.VuKhiTable,
			Columns: []string{dohiem.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DoHiem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dohiem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
