// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"game/ent/dohiem"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DoHiem is the model entity for the DoHiem schema.
type DoHiem struct {
	config `json:"-"`
	// ID of the ent.
	// Mã độ hiếm
	ID int `json:"id,omitempty"`
	// Tên độ hiếm
	TenDoHiem string `json:"ten_do_hiem,omitempty"`
	// Số lượng
	SoLuong int `json:"so_luong,omitempty"`
	// Màu sắc HEX
	MauSac string `json:"mau_sac,omitempty"`
	// Damage bonus
	SatThuongBonus float64 `json:"sat_thuong_bonus,omitempty"`
	// Attack speed bonus
	TocDoDanhBonus float64 `json:"toc_do_danh_bonus,omitempty"`
	// Cấp bậc
	CapBac int `json:"cap_bac,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DoHiemQuery when eager-loading is set.
	Edges        DoHiemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DoHiemEdges holds the relations/edges for other nodes in the graph.
type DoHiemEdges struct {
	// VuKhi holds the value of the vu_khi edge.
	VuKhi []*VuKhi `json:"vu_khi,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VuKhiOrErr returns the VuKhi value or an error if the edge
// was not loaded in eager-loading.
func (e DoHiemEdges) VuKhiOrErr() ([]*VuKhi, error) {
	if e.loadedTypes[0] {
		return e.VuKhi, nil
	}
	return nil, &NotLoadedError{edge: "vu_khi"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DoHiem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dohiem.FieldSatThuongBonus, dohiem.FieldTocDoDanhBonus:
			values[i] = new(sql.NullFloat64)
		case dohiem.FieldID, dohiem.FieldSoLuong, dohiem.FieldCapBac:
			values[i] = new(sql.NullInt64)
		case dohiem.FieldTenDoHiem, dohiem.FieldMauSac:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DoHiem fields.
func (_m *DoHiem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dohiem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dohiem.FieldTenDoHiem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ten_do_hiem", values[i])
			} else if value.Valid {
				_m.TenDoHiem = value.String
			}
		case dohiem.FieldSoLuong:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field so_luong", values[i])
			} else if value.Valid {
				_m.SoLuong = int(value.Int64)
			}
		case dohiem.FieldMauSac:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mau_sac", values[i])
			} else if value.Valid {
				_m.MauSac = value.String
			}
		case dohiem.FieldSatThuongBonus:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sat_thuong_bonus", values[i])
			} else if value.Valid {
				_m.SatThuongBonus = value.Float64
			}
		case dohiem.FieldTocDoDanhBonus:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field toc_do_danh_bonus", values[i])
			} else if value.Valid {
				_m.TocDoDanhBonus = value.Float64
			}
		case dohiem.FieldCapBac:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cap_bac", values[i])
			} else if value.Valid {
				_m.CapBac = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DoHiem.
// This includes values selected through modifiers, order, etc.
func (_m *DoHiem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVuKhi queries the "vu_khi" edge of the DoHiem entity.
func (_m *DoHiem) QueryVuKhi() *VuKhiQuery {
	return NewDoHiemClient(_m.config).QueryVuKhi(_m)
}

// Update returns a builder for updating this DoHiem.
// Note that you need to call DoHiem.Unwrap() before calling this method if this DoHiem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DoHiem) Update() *DoHiemUpdateOne {
	return NewDoHiemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DoHiem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DoHiem) Unwrap() *DoHiem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DoHiem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DoHiem) String() string {
	var builder strings.Builder
	builder.WriteString("DoHiem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ten_do_hiem=")
	builder.WriteString(_m.TenDoHiem)
	builder.WriteString(", ")
	builder.WriteString("so_luong=")
	builder.WriteString(fmt.Sprintf("%v", _m.SoLuong))
	builder.WriteString(", ")
	builder.WriteString("mau_sac=")
	builder.WriteString(_m.MauSac)
	builder.WriteString(", ")
	builder.WriteString("sat_thuong_bonus=")
	builder.WriteString(fmt.Sprintf("%v", _m.SatThuongBonus))
	builder.WriteString(", ")
	builder.WriteString("toc_do_danh_bonus=")
	builder.WriteString(fmt.Sprintf("%v", _m.TocDoDanhBonus))
	builder.WriteString(", ")
	builder.WriteString("cap_bac=")
	builder.WriteString(fmt.Sprintf("%v", _m.CapBac))
	builder.WriteByte(')')
	return builder.String()
}

// DoHiems is a parsable slice of DoHiem.
type DoHiems []*DoHiem
