// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"game/ent/he"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// He is the model entity for the He schema.
type He struct {
	config `json:"-"`
	// ID of the ent.
	// Mã hệ
	ID int `json:"id,omitempty"`
	// Tên hệ
	TenHe string `json:"ten_he,omitempty"`
	// Mô tả
	MoTa string `json:"mo_ta,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HeQuery when eager-loading is set.
	Edges        HeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HeEdges holds the relations/edges for other nodes in the graph.
type HeEdges struct {
	// VuKhi holds the value of the vu_khi edge.
	VuKhi []*VuKhi `json:"vu_khi,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VuKhiOrErr returns the VuKhi value or an error if the edge
// was not loaded in eager-loading.
func (e HeEdges) VuKhiOrErr() ([]*VuKhi, error) {
	if e.loadedTypes[0] {
		return e.VuKhi, nil
	}
	return nil, &NotLoadedError{edge: "vu_khi"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*He) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case he.FieldID:
			values[i] = new(sql.NullInt64)
		case he.FieldTenHe, he.FieldMoTa:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the He fields.
func (_m *He) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case he.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case he.FieldTenHe:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ten_he", values[i])
			} else if value.Valid {
				_m.TenHe = value.String
			}
		case he.FieldMoTa:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mo_ta", values[i])
			} else if value.Valid {
				_m.MoTa = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the He.
// This includes values selected through modifiers, order, etc.
func (_m *He) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVuKhi queries the "vu_khi" edge of the He entity.
func (_m *He) QueryVuKhi() *VuKhiQuery {
	return NewHeClient(_m.config).QueryVuKhi(_m)
}

// Update returns a builder for updating this He.
// Note that you need to call He.Unwrap() before calling this method if this He
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *He) Update() *HeUpdateOne {
	return NewHeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the He entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *He) Unwrap() *He {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: He is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *He) String() string {
	var builder strings.Builder
	builder.WriteString("He(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ten_he=")
	builder.WriteString(_m.TenHe)
	builder.WriteString(", ")
	builder.WriteString("mo_ta=")
	builder.WriteString(_m.MoTa)
	builder.WriteByte(')')
	return builder.String()
}

// Hes is a parsable slice of He.
type Hes []*He
