// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"game/ent/he"
	"game/ent/predicate"
	"game/ent/vukhi"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HeUpdate is the builder for updating He entities.
type HeUpdate struct {
	config
	hooks    []Hook
	mutation *HeMutation
}

// Where appends a list predicates to the HeUpdate builder.
func (_u *HeUpdate) Where(ps ...predicate.He) *HeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenHe sets the "ten_he" field.
func (_u *HeUpdate) SetTenHe(v string) *HeUpdate {
	_u.mutation.SetTenHe(v)
	return _u
}

// SetNillableTenHe sets the "ten_he" field if the given value is not nil.
func (_u *HeUpdate) SetNillableTenHe(v *string) *HeUpdate {
	if v != nil {
		_u.SetTenHe(*v)
	}
	return _u
}

// SetMoTa sets the "mo_ta" field.
func (_u *HeUpdate) SetMoTa(v string) *HeUpdate {
	_u.mutation.SetMoTa(v)
	return _u
}

// SetNillableMoTa sets the "mo_ta" field if the given value is not nil.
func (_u *HeUpdate) SetNillableMoTa(v *string) *HeUpdate {
	if v != nil {
		_u.SetMoTa(*v)
	}
	return _u
}

// ClearMoTa clears the value of the "mo_ta" field.
func (_u *HeUpdate) ClearMoTa() *HeUpdate {
	_u.mutation.ClearMoTa()
	return _u
}

// AddVuKhiIDs adds the "vu_khi" edge to the VuKhi entity by IDs.
func (_u *HeUpdate) AddVuKhiIDs(ids ...int) *HeUpdate {
	_u.mutation.AddVuKhiIDs(ids...)
	return _u
}

// AddVuKhi adds the "vu_khi" edges to the VuKhi entity.
func (_u *HeUpdate) AddVuKhi(v ...*VuKhi) *HeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVuKhiIDs(ids...)
}

// Mutation returns the HeMutation object of the builder.
func (_u *HeUpdate) Mutation() *HeMutation {
	return _u.mutation
}

// ClearVuKhi clears all "vu_khi" edges to the VuKhi entity.
func (_u *HeUpdate) ClearVuKhi() *HeUpdate {
	_u.mutation.ClearVuKhi()
	return _u
}

// RemoveVuKhiIDs removes the "vu_khi" edge to VuKhi entities by IDs.
func (_u *HeUpdate) RemoveVuKhiIDs(ids ...int) *HeUpdate {
	_u.mutation.RemoveVuKhiIDs(ids...)
	return _u
}

// RemoveVuKhi removes "vu_khi" edges to VuKhi entities.
func (_u *HeUpdate) RemoveVuKhi(v ...*VuKhi) *HeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVuKhiIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HeUpdate) check() error {
	if v, ok := _u.mutation.TenHe(); ok {
		if err := he.TenHeValidator(v); err != nil {
			return &ValidationError{Name: "ten_he", err: fmt.Errorf(`ent: validator failed for field "He.ten_he": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MoTa(); ok {
		if err := he.MoTaValidator(v); err != nil {
			return &ValidationError{Name: "mo_ta", err: fmt.Errorf(`ent: validator failed for field "He.mo_ta": %w`, err)}
		}
	}
	return nil
}

func (_u *HeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(he.Table, he.Columns, sqlgraph.NewFieldSpec(he.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenHe(); ok {
		_spec.SetField(he.FieldTenHe, field.TypeString, value)
	}
	if value, ok := _u.mutation.MoTa(); ok {
		_spec.SetField(he.FieldMoTa, field.TypeString, value)
	}
	if _u.mutation.MoTaCleared() {
		_spec.ClearField(he.FieldMoTa, field.TypeString)
	}
	if _u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   he.VuKhiTable,
			Columns: []string{he.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVuKhiIDs(); len(nodes) > 0 && !_u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   he.VuKhiTable,
			Columns: []string{he.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VuKhiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   he.VuKhiTable,
			Columns: []string{he.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{he.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HeUpdateOne is the builder for updating a single He entity.
type HeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HeMutation
}

// SetTenHe sets the "ten_he" field.
func (_u *HeUpdateOne) SetTenHe(v string) *HeUpdateOne {
	_u.mutation.SetTenHe(v)
	return _u
}

// SetNillableTenHe sets the "ten_he" field if the given value is not nil.
func (_u *HeUpdateOne) SetNillableTenHe(v *string) *HeUpdateOne {
	if v != nil {
		_u.SetTenHe(*v)
	}
	return _u
}

// SetMoTa sets the "mo_ta" field.
func (_u *HeUpdateOne) SetMoTa(v string) *HeUpdateOne {
	_u.mutation.SetMoTa(v)
	return _u
}

// SetNillableMoTa sets the "mo_ta" field if the given value is not nil.
func (_u *HeUpdateOne) SetNillableMoTa(v *string) *HeUpdateOne {
	if v != nil {
		_u.SetMoTa(*v)
	}
	return _u
}

// ClearMoTa clears the value of the "mo_ta" field.
func (_u *HeUpdateOne) ClearMoTa() *HeUpdateOne {
	_u.mutation.ClearMoTa()
	return _u
}

// AddVuKhiIDs adds the "vu_khi" edge to the VuKhi entity by IDs.
func (_u *HeUpdateOne) AddVuKhiIDs(ids ...int) *HeUpdateOne {
	_u.mutation.AddVuKhiIDs(ids...)
	return _u
}

// AddVuKhi adds the "vu_khi" edges to the VuKhi entity.
func (_u *HeUpdateOne) AddVuKhi(v ...*VuKhi) *HeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVuKhiIDs(ids...)
}

// Mutation returns the HeMutation object of the builder.
func (_u *HeUpdateOne) Mutation() *HeMutation {
	return _u.mutation
}

// ClearVuKhi clears all "vu_khi" edges to the VuKhi entity.
func (_u *HeUpdateOne) ClearVuKhi() *HeUpdateOne {
	_u.mutation.ClearVuKhi()
	return _u
}

// RemoveVuKhiIDs removes the "vu_khi" edge to VuKhi entities by IDs.
func (_u *HeUpdateOne) RemoveVuKhiIDs(ids ...int) *HeUpdateOne {
	_u.mutation.RemoveVuKhiIDs(ids...)
	return _u
}

// RemoveVuKhi removes "vu_khi" edges to VuKhi entities.
func (_u *HeUpdateOne) RemoveVuKhi(v ...*VuKhi) *HeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVuKhiIDs(ids...)
}

// Where appends a list predicates to the HeUpdate builder.
func (_u *HeUpdateOne) Where(ps ...predicate.He) *HeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HeUpdateOne) Select(field string, fields ...string) *HeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated He entity.
func (_u *HeUpdateOne) Save(ctx context.Context) (*He, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HeUpdateOne) SaveX(ctx context.Context) *He {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HeUpdateOne) check() error {
	if v, ok := _u.mutation.TenHe(); ok {
		if err := he.TenHeValidator(v); err != nil {
			return &ValidationError{Name: "ten_he", err: fmt.Errorf(`ent: validator failed for field "He.ten_he": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MoTa(); ok {
		if err := he.MoTaValidator(v); err != nil {
			return &ValidationError{Name: "mo_ta", err: fmt.Errorf(`ent: validator failed for field "He.mo_ta": %w`, err)}
		}
	}
	return nil
}

func (_u *HeUpdateOne) sqlSave(ctx context.Context) (_node *He, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(he.Table, he.Columns, sqlgraph.NewFieldSpec(he.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "He.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, he.FieldID)
		for _, f := range fields {
			if !he.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != he.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenHe(); ok {
		_spec.SetField(he.FieldTenHe, field.TypeString, value)
	}
	if value, ok := _u.mutation.MoTa(); ok {
		_spec.SetField(he.FieldMoTa, field.TypeString, value)
	}
	if _u.mutation.MoTaCleared() {
		_spec.ClearField(he.FieldMoTa, field.TypeString)
	}
	if _u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   he.VuKhiTable,
			Columns: []string{he.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVuKhiIDs(); len(nodes) > 0 && !_u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   he.VuKhiTable,
			Columns: []string{he.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VuKhiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   he.VuKhiTable,
			Columns: []string{he.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &He{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{he.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
