// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"game/ent/loaivukhi"
	"game/ent/vukhi"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoaiVuKhiCreate is the builder for creating a LoaiVuKhi entity.
type LoaiVuKhiCreate struct {
	config
	mutation *LoaiVuKhiMutation
	hooks    []Hook
}

// SetTenLoaiVuKhi sets the "ten_loai_vu_khi" field.
func (_c *LoaiVuKhiCreate) SetTenLoaiVuKhi(v string) *LoaiVuKhiCreate {
	_c.mutation.SetTenLoaiVuKhi(v)
	return _c
}

// SetMoTa sets the "mo_ta" field.
func (_c *LoaiVuKhiCreate) SetMoTa(v string) *LoaiVuKhiCreate {
	_c.mutation.SetMoTa(v)
	return _c
}

// SetNillableMoTa sets the "mo_ta" field if the given value is not nil.
func (_c *LoaiVuKhiCreate) SetNillableMoTa(v *string) *LoaiVuKhiCreate {
	if v != nil {
		_c.SetMoTa(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LoaiVuKhiCreate) SetID(v int) *LoaiVuKhiCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddVuKhiIDs adds the "vu_khi" edge to the VuKhi entity by IDs.
func (_c *LoaiVuKhiCreate) AddVuKhiIDs(ids ...int) *LoaiVuKhiCreate {
	_c.mutation.AddVuKhiIDs(ids...)
	return _c
}

// AddVuKhi adds the "vu_khi" edges to the VuKhi entity.
func (_c *LoaiVuKhiCreate) AddVuKhi(v ...*VuKhi) *LoaiVuKhiCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVuKhiIDs(ids...)
}

// Mutation returns the LoaiVuKhiMutation object of the builder.
func (_c *LoaiVuKhiCreate) Mutation() *LoaiVuKhiMutation {
	return _c.mutation
}

// Save creates the LoaiVuKhi in the database.
func (_c *LoaiVuKhiCreate) Save(ctx context.Context) (*LoaiVuKhi, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoaiVuKhiCreate) SaveX(ctx context.Context) *LoaiVuKhi {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoaiVuKhiCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoaiVuKhiCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoaiVuKhiCreate) check() error {
	if _, ok := _c.mutation.TenLoaiVuKhi(); !ok {
		return &ValidationError{Name: "ten_loai_vu_khi", err: errors.New(`ent: missing required field "LoaiVuKhi.ten_loai_vu_khi"`)}
	}
	if v, ok := _c.mutation.TenLoaiVuKhi(); ok {
		if err := loaivukhi.TenLoaiVuKhiValidator(v); err != nil {
			return &ValidationError{Name: "ten_loai_vu_khi", err: fmt.Errorf(`ent: validator failed for field "LoaiVuKhi.ten_loai_vu_khi": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MoTa(); ok {
		if err := loaivukhi.MoTaValidator(v); err != nil {
			return &ValidationError{Name: "mo_ta", err: fmt.Errorf(`ent: validator failed for field "LoaiVuKhi.mo_ta": %w`, err)}
		}
	}
	return nil
}

func (_c *LoaiVuKhiCreate) sqlSave(ctx context.Context) (*LoaiVuKhi, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoaiVuKhiCreate) createSpec() (*LoaiVuKhi, *sqlgraph.CreateSpec) {
	var (
		_node = &LoaiVuKhi{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loaivukhi.Table, sqlgraph.NewFieldSpec(loaivukhi.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenLoaiVuKhi(); ok {
		_spec.SetField(loaivukhi.FieldTenLoaiVuKhi, field.TypeString, value)
		_node.TenLoaiVuKhi = value
	}
	if value, ok := _c.mutation.MoTa(); ok {
		_spec.SetField(loaivukhi.FieldMoTa, field.TypeString, value)
		_node.MoTa = value
	}
	if nodes := _c.mutation.VuKhiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loaivukhi.VuKhiTable,
			Columns: []string{loaivukhi.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LoaiVuKhiCreateBulk is the builder for creating many LoaiVuKhi entities in bulk.
type LoaiVuKhiCreateBulk struct {
	config
	err      error
	builders []*LoaiVuKhiCreate
}

// Save creates the LoaiVuKhi entities in the database.
func (_c *LoaiVuKhiCreateBulk) Save(ctx context.Context) ([]*LoaiVuKhi, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoaiVuKhi, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoaiVuKhiMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoaiVuKhiCreateBulk) SaveX(ctx context.Context) []*LoaiVuKhi {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoaiVuKhiCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoaiVuKhiCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
