// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"game/ent/loaivukhi"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LoaiVuKhi is the model entity for the LoaiVuKhi schema.
type LoaiVuKhi struct {
	config `json:"-"`
	// ID of the ent.
	// Mã loại vũ khí
	ID int `json:"id,omitempty"`
	// Tên loại
	TenLoai string `json:"ten_loai,omitempty"`
	// Mô tả
	MoTa string `json:"mo_ta,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoaiVuKhiQuery when eager-loading is set.
	Edges        LoaiVuKhiEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LoaiVuKhiEdges holds the relations/edges for other nodes in the graph.
type LoaiVuKhiEdges struct {
	// VuKhi holds the value of the vu_khi edge.
	VuKhi []*VuKhi `json:"vu_khi,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VuKhiOrErr returns the VuKhi value or an error if the edge
// was not loaded in eager-loading.
func (e LoaiVuKhiEdges) VuKhiOrErr() ([]*VuKhi, error) {
	if e.loadedTypes[0] {
		return e.VuKhi, nil
	}
	return nil, &NotLoadedError{edge: "vu_khi"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoaiVuKhi) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loaivukhi.FieldID:
			values[i] = new(sql.NullInt64)
		case loaivukhi.FieldTenLoai, loaivukhi.FieldMoTa:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoaiVuKhi fields.
func (_m *LoaiVuKhi) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loaivukhi.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case loaivukhi.FieldTenLoai:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ten_loai", values[i])
			} else if value.Valid {
				_m.TenLoai = value.String
			}
		case loaivukhi.FieldMoTa:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mo_ta", values[i])
			} else if value.Valid {
				_m.MoTa = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoaiVuKhi.
// This includes values selected through modifiers, order, etc.
func (_m *LoaiVuKhi) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVuKhi queries the "vu_khi" edge of the LoaiVuKhi entity.
func (_m *LoaiVuKhi) QueryVuKhi() *VuKhiQuery {
	return NewLoaiVuKhiClient(_m.config).QueryVuKhi(_m)
}

// Update returns a builder for updating this LoaiVuKhi.
// Note that you need to call LoaiVuKhi.Unwrap() before calling this method if this LoaiVuKhi
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LoaiVuKhi) Update() *LoaiVuKhiUpdateOne {
	return NewLoaiVuKhiClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LoaiVuKhi entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LoaiVuKhi) Unwrap() *LoaiVuKhi {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoaiVuKhi is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LoaiVuKhi) String() string {
	var builder strings.Builder
	builder.WriteString("LoaiVuKhi(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ten_loai=")
	builder.WriteString(_m.TenLoai)
	builder.WriteString(", ")
	builder.WriteString("mo_ta=")
	builder.WriteString(_m.MoTa)
	builder.WriteByte(')')
	return builder.String()
}

// LoaiVuKhis is a parsable slice of LoaiVuKhi.
type LoaiVuKhis []*LoaiVuKhi
