// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"game/ent/loaivukhi"
	"game/ent/predicate"
	"game/ent/vukhi"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoaiVuKhiQuery is the builder for querying LoaiVuKhi entities.
type LoaiVuKhiQuery struct {
	config
	ctx        *QueryContext
	order      []loaivukhi.OrderOption
	inters     []Interceptor
	predicates []predicate.LoaiVuKhi
	withVuKhi  *VuKhiQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LoaiVuKhiQuery builder.
func (_q *LoaiVuKhiQuery) Where(ps ...predicate.LoaiVuKhi) *LoaiVuKhiQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LoaiVuKhiQuery) Limit(limit int) *LoaiVuKhiQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LoaiVuKhiQuery) Offset(offset int) *LoaiVuKhiQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LoaiVuKhiQuery) Unique(unique bool) *LoaiVuKhiQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LoaiVuKhiQuery) Order(o ...loaivukhi.OrderOption) *LoaiVuKhiQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryVuKhi chains the current query on the "vu_khi" edge.
func (_q *LoaiVuKhiQuery) QueryVuKhi() *VuKhiQuery {
	query := (&VuKhiClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loaivukhi.Table, loaivukhi.FieldID, selector),
			sqlgraph.To(vukhi.Table, vukhi.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, loaivukhi.VuKhiTable, loaivukhi.VuKhiColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LoaiVuKhi entity from the query.
// Returns a *NotFoundError when no LoaiVuKhi was found.
func (_q *LoaiVuKhiQuery) First(ctx context.Context) (*LoaiVuKhi, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{loaivukhi.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LoaiVuKhiQuery) FirstX(ctx context.Context) *LoaiVuKhi {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LoaiVuKhi ID from the query.
// Returns a *NotFoundError when no LoaiVuKhi ID was found.
func (_q *LoaiVuKhiQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{loaivukhi.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LoaiVuKhiQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LoaiVuKhi entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LoaiVuKhi entity is found.
// Returns a *NotFoundError when no LoaiVuKhi entities are found.
func (_q *LoaiVuKhiQuery) Only(ctx context.Context) (*LoaiVuKhi, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{loaivukhi.Label}
	default:
		return nil, &NotSingularError{loaivukhi.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LoaiVuKhiQuery) OnlyX(ctx context.Context) *LoaiVuKhi {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LoaiVuKhi ID in the query.
// Returns a *NotSingularError when more than one LoaiVuKhi ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LoaiVuKhiQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{loaivukhi.Label}
	default:
		err = &NotSingularError{loaivukhi.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LoaiVuKhiQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LoaiVuKhis.
func (_q *LoaiVuKhiQuery) All(ctx context.Context) ([]*LoaiVuKhi, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LoaiVuKhi, *LoaiVuKhiQuery]()
	return withInterceptors[[]*LoaiVuKhi](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LoaiVuKhiQuery) AllX(ctx context.Context) []*LoaiVuKhi {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LoaiVuKhi IDs.
func (_q *LoaiVuKhiQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(loaivukhi.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LoaiVuKhiQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LoaiVuKhiQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LoaiVuKhiQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LoaiVuKhiQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LoaiVuKhiQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LoaiVuKhiQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LoaiVuKhiQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LoaiVuKhiQuery) Clone() *LoaiVuKhiQuery {
	if _q == nil {
		return nil
	}
	return &LoaiVuKhiQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]loaivukhi.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.LoaiVuKhi{}, _q.predicates...),
		withVuKhi:  _q.withVuKhi.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithVuKhi tells the query-builder to eager-load the nodes that are connected to
// the "vu_khi" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LoaiVuKhiQuery) WithVuKhi(opts ...func(*VuKhiQuery)) *LoaiVuKhiQuery {
	query := (&VuKhiClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVuKhi = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenLoai string `json:"ten_loai,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LoaiVuKhi.Query().
//		GroupBy(loaivukhi.FieldTenLoai).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LoaiVuKhiQuery) GroupBy(field string, fields ...string) *LoaiVuKhiGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LoaiVuKhiGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = loaivukhi.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenLoai string `json:"ten_loai,omitempty"`
//	}
//
//	client.LoaiVuKhi.Query().
//		Select(loaivukhi.FieldTenLoai).
//		Scan(ctx, &v)
func (_q *LoaiVuKhiQuery) Select(fields ...string) *LoaiVuKhiSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LoaiVuKhiSelect{LoaiVuKhiQuery: _q}
	sbuild.label = loaivukhi.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LoaiVuKhiSelect configured with the given aggregations.
func (_q *LoaiVuKhiQuery) Aggregate(fns ...AggregateFunc) *LoaiVuKhiSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LoaiVuKhiQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !loaivukhi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LoaiVuKhiQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LoaiVuKhi, error) {
	var (
		nodes       = []*LoaiVuKhi{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withVuKhi != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LoaiVuKhi).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LoaiVuKhi{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withVuKhi; query != nil {
		if err := _q.loadVuKhi(ctx, query, nodes,
			func(n *LoaiVuKhi) { n.Edges.VuKhi = []*VuKhi{} },
			func(n *LoaiVuKhi, e *VuKhi) { n.Edges.VuKhi = append(n.Edges.VuKhi, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LoaiVuKhiQuery) loadVuKhi(ctx context.Context, query *VuKhiQuery, nodes []*LoaiVuKhi, init func(*LoaiVuKhi), assign func(*LoaiVuKhi, *VuKhi)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LoaiVuKhi)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(vukhi.FieldMaLoai)
	}
	query.Where(predicate.VuKhi(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(loaivukhi.VuKhiColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MaLoai
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ma_loai" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *LoaiVuKhiQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LoaiVuKhiQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(loaivukhi.Table, loaivukhi.Columns, sqlgraph.NewFieldSpec(loaivukhi.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loaivukhi.FieldID)
		for i := range fields {
			if fields[i] != loaivukhi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LoaiVuKhiQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(loaivukhi.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = loaivukhi.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LoaiVuKhiGroupBy is the group-by builder for LoaiVuKhi entities.
type LoaiVuKhiGroupBy struct {
	selector
	build *LoaiVuKhiQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LoaiVuKhiGroupBy) Aggregate(fns ...AggregateFunc) *LoaiVuKhiGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LoaiVuKhiGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoaiVuKhiQuery, *LoaiVuKhiGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LoaiVuKhiGroupBy) sqlScan(ctx context.Context, root *LoaiVuKhiQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LoaiVuKhiSelect is the builder for selecting fields of LoaiVuKhi entities.
type LoaiVuKhiSelect struct {
	*LoaiVuKhiQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LoaiVuKhiSelect) Aggregate(fns ...AggregateFunc) *LoaiVuKhiSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LoaiVuKhiSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoaiVuKhiQuery, *LoaiVuKhiSelect](ctx, _s.LoaiVuKhiQuery, _s, _s.inters, v)
}

func (_s *LoaiVuKhiSelect) sqlScan(ctx context.Context, root *LoaiVuKhiQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
