// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"game/ent/loaivukhi"
	"game/ent/predicate"
	"game/ent/vukhi"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoaiVuKhiUpdate is the builder for updating LoaiVuKhi entities.
type LoaiVuKhiUpdate struct {
	config
	hooks    []Hook
	mutation *LoaiVuKhiMutation
}

// Where appends a list predicates to the LoaiVuKhiUpdate builder.
func (_u *LoaiVuKhiUpdate) Where(ps ...predicate.LoaiVuKhi) *LoaiVuKhiUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenLoaiVuKhi sets the "ten_loai_vu_khi" field.
func (_u *LoaiVuKhiUpdate) SetTenLoaiVuKhi(v string) *LoaiVuKhiUpdate {
	_u.mutation.SetTenLoaiVuKhi(v)
	return _u
}

// SetNillableTenLoaiVuKhi sets the "ten_loai_vu_khi" field if the given value is not nil.
func (_u *LoaiVuKhiUpdate) SetNillableTenLoaiVuKhi(v *string) *LoaiVuKhiUpdate {
	if v != nil {
		_u.SetTenLoaiVuKhi(*v)
	}
	return _u
}

// SetMoTa sets the "mo_ta" field.
func (_u *LoaiVuKhiUpdate) SetMoTa(v string) *LoaiVuKhiUpdate {
	_u.mutation.SetMoTa(v)
	return _u
}

// SetNillableMoTa sets the "mo_ta" field if the given value is not nil.
func (_u *LoaiVuKhiUpdate) SetNillableMoTa(v *string) *LoaiVuKhiUpdate {
	if v != nil {
		_u.SetMoTa(*v)
	}
	return _u
}

// ClearMoTa clears the value of the "mo_ta" field.
func (_u *LoaiVuKhiUpdate) ClearMoTa() *LoaiVuKhiUpdate {
	_u.mutation.ClearMoTa()
	return _u
}

// AddVuKhiIDs adds the "vu_khi" edge to the VuKhi entity by IDs.
func (_u *LoaiVuKhiUpdate) AddVuKhiIDs(ids ...int) *LoaiVuKhiUpdate {
	_u.mutation.AddVuKhiIDs(ids...)
	return _u
}

// AddVuKhi adds the "vu_khi" edges to the VuKhi entity.
func (_u *LoaiVuKhiUpdate) AddVuKhi(v ...*VuKhi) *LoaiVuKhiUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVuKhiIDs(ids...)
}

// Mutation returns the LoaiVuKhiMutation object of the builder.
func (_u *LoaiVuKhiUpdate) Mutation() *LoaiVuKhiMutation {
	return _u.mutation
}

// ClearVuKhi clears all "vu_khi" edges to the VuKhi entity.
func (_u *LoaiVuKhiUpdate) ClearVuKhi() *LoaiVuKhiUpdate {
	_u.mutation.ClearVuKhi()
	return _u
}

// RemoveVuKhiIDs removes the "vu_khi" edge to VuKhi entities by IDs.
func (_u *LoaiVuKhiUpdate) RemoveVuKhiIDs(ids ...int) *LoaiVuKhiUpdate {
	_u.mutation.RemoveVuKhiIDs(ids...)
	return _u
}

// RemoveVuKhi removes "vu_khi" edges to VuKhi entities.
func (_u *LoaiVuKhiUpdate) RemoveVuKhi(v ...*VuKhi) *LoaiVuKhiUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVuKhiIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoaiVuKhiUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoaiVuKhiUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoaiVuKhiUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoaiVuKhiUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoaiVuKhiUpdate) check() error {
	if v, ok := _u.mutation.TenLoaiVuKhi(); ok {
		if err := loaivukhi.TenLoaiVuKhiValidator(v); err != nil {
			return &ValidationError{Name: "ten_loai_vu_khi", err: fmt.Errorf(`ent: validator failed for field "LoaiVuKhi.ten_loai_vu_khi": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MoTa(); ok {
		if err := loaivukhi.MoTaValidator(v); err != nil {
			return &ValidationError{Name: "mo_ta", err: fmt.Errorf(`ent: validator failed for field "LoaiVuKhi.mo_ta": %w`, err)}
		}
	}
	return nil
}

func (_u *LoaiVuKhiUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loaivukhi.Table, loaivukhi.Columns, sqlgraph.NewFieldSpec(loaivukhi.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenLoaiVuKhi(); ok {
		_spec.SetField(loaivukhi.FieldTenLoaiVuKhi, field.TypeString, value)
	}
	if value, ok := _u.mutation.MoTa(); ok {
		_spec.SetField(loaivukhi.FieldMoTa, field.TypeString, value)
	}
	if _u.mutation.MoTaCleared() {
		_spec.ClearField(loaivukhi.FieldMoTa, field.TypeString)
	}
	if _u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loaivukhi.VuKhiTable,
			Columns: []string{loaivukhi.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVuKhiIDs(); len(nodes) > 0 && !_u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loaivukhi.VuKhiTable,
			Columns: []string{loaivukhi.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VuKhiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loaivukhi.VuKhiTable,
			Columns: []string{loaivukhi.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loaivukhi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoaiVuKhiUpdateOne is the builder for updating a single LoaiVuKhi entity.
type LoaiVuKhiUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoaiVuKhiMutation
}

// SetTenLoaiVuKhi sets the "ten_loai_vu_khi" field.
func (_u *LoaiVuKhiUpdateOne) SetTenLoaiVuKhi(v string) *LoaiVuKhiUpdateOne {
	_u.mutation.SetTenLoaiVuKhi(v)
	return _u
}

// SetNillableTenLoaiVuKhi sets the "ten_loai_vu_khi" field if the given value is not nil.
func (_u *LoaiVuKhiUpdateOne) SetNillableTenLoaiVuKhi(v *string) *LoaiVuKhiUpdateOne {
	if v != nil {
		_u.SetTenLoaiVuKhi(*v)
	}
	return _u
}

// SetMoTa sets the "mo_ta" field.
func (_u *LoaiVuKhiUpdateOne) SetMoTa(v string) *LoaiVuKhiUpdateOne {
	_u.mutation.SetMoTa(v)
	return _u
}

// SetNillableMoTa sets the "mo_ta" field if the given value is not nil.
func (_u *LoaiVuKhiUpdateOne) SetNillableMoTa(v *string) *LoaiVuKhiUpdateOne {
	if v != nil {
		_u.SetMoTa(*v)
	}
	return _u
}

// ClearMoTa clears the value of the "mo_ta" field.
func (_u *LoaiVuKhiUpdateOne) ClearMoTa() *LoaiVuKhiUpdateOne {
	_u.mutation.ClearMoTa()
	return _u
}

// AddVuKhiIDs adds the "vu_khi" edge to the VuKhi entity by IDs.
func (_u *LoaiVuKhiUpdateOne) AddVuKhiIDs(ids ...int) *LoaiVuKhiUpdateOne {
	_u.mutation.AddVuKhiIDs(ids...)
	return _u
}

// AddVuKhi adds the "vu_khi" edges to the VuKhi entity.
func (_u *LoaiVuKhiUpdateOne) AddVuKhi(v ...*VuKhi) *LoaiVuKhiUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVuKhiIDs(ids...)
}

// Mutation returns the LoaiVuKhiMutation object of the builder.
func (_u *LoaiVuKhiUpdateOne) Mutation() *LoaiVuKhiMutation {
	return _u.mutation
}

// ClearVuKhi clears all "vu_khi" edges to the VuKhi entity.
func (_u *LoaiVuKhiUpdateOne) ClearVuKhi() *LoaiVuKhiUpdateOne {
	_u.mutation.ClearVuKhi()
	return _u
}

// RemoveVuKhiIDs removes the "vu_khi" edge to VuKhi entities by IDs.
func (_u *LoaiVuKhiUpdateOne) RemoveVuKhiIDs(ids ...int) *LoaiVuKhiUpdateOne {
	_u.mutation.RemoveVuKhiIDs(ids...)
	return _u
}

// RemoveVuKhi removes "vu_khi" edges to VuKhi entities.
func (_u *LoaiVuKhiUpdateOne) RemoveVuKhi(v ...*VuKhi) *LoaiVuKhiUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVuKhiIDs(ids...)
}

// Where appends a list predicates to the LoaiVuKhiUpdate builder.
func (_u *LoaiVuKhiUpdateOne) Where(ps ...predicate.LoaiVuKhi) *LoaiVuKhiUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoaiVuKhiUpdateOne) Select(field string, fields ...string) *LoaiVuKhiUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoaiVuKhi entity.
func (_u *LoaiVuKhiUpdateOne) Save(ctx context.Context) (*LoaiVuKhi, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoaiVuKhiUpdateOne) SaveX(ctx context.Context) *LoaiVuKhi {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoaiVuKhiUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoaiVuKhiUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoaiVuKhiUpdateOne) check() error {
	if v, ok := _u.mutation.TenLoaiVuKhi(); ok {
		if err := loaivukhi.TenLoaiVuKhiValidator(v); err != nil {
			return &ValidationError{Name: "ten_loai_vu_khi", err: fmt.Errorf(`ent: validator failed for field "LoaiVuKhi.ten_loai_vu_khi": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MoTa(); ok {
		if err := loaivukhi.MoTaValidator(v); err != nil {
			return &ValidationError{Name: "mo_ta", err: fmt.Errorf(`ent: validator failed for field "LoaiVuKhi.mo_ta": %w`, err)}
		}
	}
	return nil
}

func (_u *LoaiVuKhiUpdateOne) sqlSave(ctx context.Context) (_node *LoaiVuKhi, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loaivukhi.Table, loaivukhi.Columns, sqlgraph.NewFieldSpec(loaivukhi.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoaiVuKhi.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loaivukhi.FieldID)
		for _, f := range fields {
			if !loaivukhi.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loaivukhi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenLoaiVuKhi(); ok {
		_spec.SetField(loaivukhi.FieldTenLoaiVuKhi, field.TypeString, value)
	}
	if value, ok := _u.mutation.MoTa(); ok {
		_spec.SetField(loaivukhi.FieldMoTa, field.TypeString, value)
	}
	if _u.mutation.MoTaCleared() {
		_spec.ClearField(loaivukhi.FieldMoTa, field.TypeString)
	}
	if _u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loaivukhi.VuKhiTable,
			Columns: []string{loaivukhi.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVuKhiIDs(); len(nodes) > 0 && !_u.mutation.VuKhiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loaivukhi.VuKhiTable,
			Columns: []string{loaivukhi.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VuKhiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loaivukhi.VuKhiTable,
			Columns: []string{loaivukhi.VuKhiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LoaiVuKhi{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loaivukhi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
