// Code generated by ent, DO NOT EDIT.

package ent

import (
	"game/ent/dohiem"
	"game/ent/he"
	"game/ent/loaivukhi"
	"game/ent/schema"
	"game/ent/vukhi"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dohiemFields := schema.DoHiem{}.Fields()
	_ = dohiemFields
	// dohiemDescTenDoHiem is the schema descriptor for ten_do_hiem field.
	dohiemDescTenDoHiem := dohiemFields[1].Descriptor()
	// dohiem.TenDoHiemValidator is a validator for the "ten_do_hiem" field. It is called by the builders before save.
	dohiem.TenDoHiemValidator = func() func(string) error {
		validators := dohiemDescTenDoHiem.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ten_do_hiem string) error {
			for _, fn := range fns {
				if err := fn(ten_do_hiem); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dohiemDescSoLuong is the schema descriptor for so_luong field.
	dohiemDescSoLuong := dohiemFields[2].Descriptor()
	// dohiem.DefaultSoLuong holds the default value on creation for the so_luong field.
	dohiem.DefaultSoLuong = dohiemDescSoLuong.Default.(int)
	// dohiemDescMauSac is the schema descriptor for mau_sac field.
	dohiemDescMauSac := dohiemFields[3].Descriptor()
	// dohiem.MauSacValidator is a validator for the "mau_sac" field. It is called by the builders before save.
	dohiem.MauSacValidator = dohiemDescMauSac.Validators[0].(func(string) error)
	// dohiemDescSatThuongBonus is the schema descriptor for sat_thuong_bonus field.
	dohiemDescSatThuongBonus := dohiemFields[4].Descriptor()
	// dohiem.DefaultSatThuongBonus holds the default value on creation for the sat_thuong_bonus field.
	dohiem.DefaultSatThuongBonus = dohiemDescSatThuongBonus.Default.(float64)
	// dohiemDescTocDoDanhBonus is the schema descriptor for toc_do_danh_bonus field.
	dohiemDescTocDoDanhBonus := dohiemFields[5].Descriptor()
	// dohiem.DefaultTocDoDanhBonus holds the default value on creation for the toc_do_danh_bonus field.
	dohiem.DefaultTocDoDanhBonus = dohiemDescTocDoDanhBonus.Default.(float64)
	heFields := schema.He{}.Fields()
	_ = heFields
	// heDescTenHe is the schema descriptor for ten_he field.
	heDescTenHe := heFields[1].Descriptor()
	// he.TenHeValidator is a validator for the "ten_he" field. It is called by the builders before save.
	he.TenHeValidator = func() func(string) error {
		validators := heDescTenHe.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ten_he string) error {
			for _, fn := range fns {
				if err := fn(ten_he); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// heDescMoTa is the schema descriptor for mo_ta field.
	heDescMoTa := heFields[2].Descriptor()
	// he.MoTaValidator is a validator for the "mo_ta" field. It is called by the builders before save.
	he.MoTaValidator = heDescMoTa.Validators[0].(func(string) error)
	loaivukhiFields := schema.LoaiVuKhi{}.Fields()
	_ = loaivukhiFields
	// loaivukhiDescTenLoai is the schema descriptor for ten_loai field.
	loaivukhiDescTenLoai := loaivukhiFields[1].Descriptor()
	// loaivukhi.TenLoaiValidator is a validator for the "ten_loai" field. It is called by the builders before save.
	loaivukhi.TenLoaiValidator = func() func(string) error {
		validators := loaivukhiDescTenLoai.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ten_loai string) error {
			for _, fn := range fns {
				if err := fn(ten_loai); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// loaivukhiDescMoTa is the schema descriptor for mo_ta field.
	loaivukhiDescMoTa := loaivukhiFields[2].Descriptor()
	// loaivukhi.MoTaValidator is a validator for the "mo_ta" field. It is called by the builders before save.
	loaivukhi.MoTaValidator = loaivukhiDescMoTa.Validators[0].(func(string) error)
	vukhiFields := schema.VuKhi{}.Fields()
	_ = vukhiFields
	// vukhiDescTenVuKhi is the schema descriptor for ten_vu_khi field.
	vukhiDescTenVuKhi := vukhiFields[1].Descriptor()
	// vukhi.TenVuKhiValidator is a validator for the "ten_vu_khi" field. It is called by the builders before save.
	vukhi.TenVuKhiValidator = func() func(string) error {
		validators := vukhiDescTenVuKhi.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ten_vu_khi string) error {
			for _, fn := range fns {
				if err := fn(ten_vu_khi); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// vukhiDescSatThuongCoBan is the schema descriptor for sat_thuong_co_ban field.
	vukhiDescSatThuongCoBan := vukhiFields[2].Descriptor()
	// vukhi.DefaultSatThuongCoBan holds the default value on creation for the sat_thuong_co_ban field.
	vukhi.DefaultSatThuongCoBan = vukhiDescSatThuongCoBan.Default.(int)
	// vukhiDescTocDoDanh is the schema descriptor for toc_do_danh field.
	vukhiDescTocDoDanh := vukhiFields[3].Descriptor()
	// vukhi.DefaultTocDoDanh holds the default value on creation for the toc_do_danh field.
	vukhi.DefaultTocDoDanh = vukhiDescTocDoDanh.Default.(float64)
	// vukhiDescTamDanh is the schema descriptor for tam_danh field.
	vukhiDescTamDanh := vukhiFields[4].Descriptor()
	// vukhi.DefaultTamDanh holds the default value on creation for the tam_danh field.
	vukhi.DefaultTamDanh = vukhiDescTamDanh.Default.(int)
	// vukhiDescMoTa is the schema descriptor for mo_ta field.
	vukhiDescMoTa := vukhiFields[5].Descriptor()
	// vukhi.MoTaValidator is a validator for the "mo_ta" field. It is called by the builders before save.
	vukhi.MoTaValidator = vukhiDescMoTa.Validators[0].(func(string) error)
}
