// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"game/ent/dohiem"
	"game/ent/he"
	"game/ent/loaivukhi"
	"game/ent/predicate"
	"game/ent/vukhi"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VuKhiUpdate is the builder for updating VuKhi entities.
type VuKhiUpdate struct {
	config
	hooks     []Hook
	mutation  *VuKhiMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the VuKhiUpdate builder.
func (_u *VuKhiUpdate) Where(ps ...predicate.VuKhi) *VuKhiUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenVuKhi sets the "ten_vu_khi" field.
func (_u *VuKhiUpdate) SetTenVuKhi(v string) *VuKhiUpdate {
	_u.mutation.SetTenVuKhi(v)
	return _u
}

// SetNillableTenVuKhi sets the "ten_vu_khi" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableTenVuKhi(v *string) *VuKhiUpdate {
	if v != nil {
		_u.SetTenVuKhi(*v)
	}
	return _u
}

// SetSatThuongCoBan sets the "sat_thuong_co_ban" field.
func (_u *VuKhiUpdate) SetSatThuongCoBan(v int) *VuKhiUpdate {
	_u.mutation.ResetSatThuongCoBan()
	_u.mutation.SetSatThuongCoBan(v)
	return _u
}

// SetNillableSatThuongCoBan sets the "sat_thuong_co_ban" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableSatThuongCoBan(v *int) *VuKhiUpdate {
	if v != nil {
		_u.SetSatThuongCoBan(*v)
	}
	return _u
}

// AddSatThuongCoBan adds value to the "sat_thuong_co_ban" field.
func (_u *VuKhiUpdate) AddSatThuongCoBan(v int) *VuKhiUpdate {
	_u.mutation.AddSatThuongCoBan(v)
	return _u
}

// SetTocDoDanh sets the "toc_do_danh" field.
func (_u *VuKhiUpdate) SetTocDoDanh(v float64) *VuKhiUpdate {
	_u.mutation.ResetTocDoDanh()
	_u.mutation.SetTocDoDanh(v)
	return _u
}

// SetNillableTocDoDanh sets the "toc_do_danh" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableTocDoDanh(v *float64) *VuKhiUpdate {
	if v != nil {
		_u.SetTocDoDanh(*v)
	}
	return _u
}

// AddTocDoDanh adds value to the "toc_do_danh" field.
func (_u *VuKhiUpdate) AddTocDoDanh(v float64) *VuKhiUpdate {
	_u.mutation.AddTocDoDanh(v)
	return _u
}

// SetTamDanh sets the "tam_danh" field.
func (_u *VuKhiUpdate) SetTamDanh(v int) *VuKhiUpdate {
	_u.mutation.ResetTamDanh()
	_u.mutation.SetTamDanh(v)
	return _u
}

// SetNillableTamDanh sets the "tam_danh" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableTamDanh(v *int) *VuKhiUpdate {
	if v != nil {
		_u.SetTamDanh(*v)
	}
	return _u
}

// AddTamDanh adds value to the "tam_danh" field.
func (_u *VuKhiUpdate) AddTamDanh(v int) *VuKhiUpdate {
	_u.mutation.AddTamDanh(v)
	return _u
}

// SetMoTa sets the "mo_ta" field.
func (_u *VuKhiUpdate) SetMoTa(v string) *VuKhiUpdate {
	_u.mutation.SetMoTa(v)
	return _u
}

// SetNillableMoTa sets the "mo_ta" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableMoTa(v *string) *VuKhiUpdate {
	if v != nil {
		_u.SetMoTa(*v)
	}
	return _u
}

// ClearMoTa clears the value of the "mo_ta" field.
func (_u *VuKhiUpdate) ClearMoTa() *VuKhiUpdate {
	_u.mutation.ClearMoTa()
	return _u
}

// SetVersion sets the "version" field.
func (_u *VuKhiUpdate) SetVersion(v int64) *VuKhiUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableVersion(v *int64) *VuKhiUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *VuKhiUpdate) AddVersion(v int64) *VuKhiUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetMaLoai sets the "ma_loai" field.
func (_u *VuKhiUpdate) SetMaLoai(v int) *VuKhiUpdate {
	_u.mutation.SetMaLoai(v)
	return _u
}

// SetNillableMaLoai sets the "ma_loai" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableMaLoai(v *int) *VuKhiUpdate {
	if v != nil {
		_u.SetMaLoai(*v)
	}
	return _u
}

// SetMaDoHiem sets the "ma_do_hiem" field.
func (_u *VuKhiUpdate) SetMaDoHiem(v int) *VuKhiUpdate {
	_u.mutation.SetMaDoHiem(v)
	return _u
}

// SetNillableMaDoHiem sets the "ma_do_hiem" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableMaDoHiem(v *int) *VuKhiUpdate {
	if v != nil {
		_u.SetMaDoHiem(*v)
	}
	return _u
}

// SetMaHe sets the "ma_he" field.
func (_u *VuKhiUpdate) SetMaHe(v int) *VuKhiUpdate {
	_u.mutation.SetMaHe(v)
	return _u
}

// SetNillableMaHe sets the "ma_he" field if the given value is not nil.
func (_u *VuKhiUpdate) SetNillableMaHe(v *int) *VuKhiUpdate {
	if v != nil {
		_u.SetMaHe(*v)
	}
	return _u
}

// SetLoaiID sets the "loai" edge to the LoaiVuKhi entity by ID.
func (_u *VuKhiUpdate) SetLoaiID(id int) *VuKhiUpdate {
	_u.mutation.SetLoaiID(id)
	return _u
}

// SetLoai sets the "loai" edge to the LoaiVuKhi entity.
func (_u *VuKhiUpdate) SetLoai(v *LoaiVuKhi) *VuKhiUpdate {
	return _u.SetLoaiID(v.ID)
}

// SetDoHiemID sets the "do_hiem" edge to the DoHiem entity by ID.
func (_u *VuKhiUpdate) SetDoHiemID(id int) *VuKhiUpdate {
	_u.mutation.SetDoHiemID(id)
	return _u
}

// SetDoHiem sets the "do_hiem" edge to the DoHiem entity.
func (_u *VuKhiUpdate) SetDoHiem(v *DoHiem) *VuKhiUpdate {
	return _u.SetDoHiemID(v.ID)
}

// SetHeID sets the "he" edge to the He entity by ID.
func (_u *VuKhiUpdate) SetHeID(id int) *VuKhiUpdate {
	_u.mutation.SetHeID(id)
	return _u
}

// SetHe sets the "he" edge to the He entity.
func (_u *VuKhiUpdate) SetHe(v *He) *VuKhiUpdate {
	return _u.SetHeID(v.ID)
}

// Mutation returns the VuKhiMutation object of the builder.
func (_u *VuKhiUpdate) Mutation() *VuKhiMutation {
	return _u.mutation
}

// ClearLoai clears the "loai" edge to the LoaiVuKhi entity.
func (_u *VuKhiUpdate) ClearLoai() *VuKhiUpdate {
	_u.mutation.ClearLoai()
	return _u
}

// ClearDoHiem clears the "do_hiem" edge to the DoHiem entity.
func (_u *VuKhiUpdate) ClearDoHiem() *VuKhiUpdate {
	_u.mutation.ClearDoHiem()
	return _u
}

// ClearHe clears the "he" edge to the He entity.
func (_u *VuKhiUpdate) ClearHe() *VuKhiUpdate {
	_u.mutation.ClearHe()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VuKhiUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VuKhiUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VuKhiUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VuKhiUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VuKhiUpdate) check() error {
	if v, ok := _u.mutation.TenVuKhi(); ok {
		if err := vukhi.TenVuKhiValidator(v); err != nil {
			return &ValidationError{Name: "ten_vu_khi", err: fmt.Errorf(`ent: validator failed for field "VuKhi.ten_vu_khi": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MoTa(); ok {
		if err := vukhi.MoTaValidator(v); err != nil {
			return &ValidationError{Name: "mo_ta", err: fmt.Errorf(`ent: validator failed for field "VuKhi.mo_ta": %w`, err)}
		}
	}
	if _u.mutation.LoaiCleared() && len(_u.mutation.LoaiIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VuKhi.loai"`)
	}
	if _u.mutation.DoHiemCleared() && len(_u.mutation.DoHiemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VuKhi.do_hiem"`)
	}
	if _u.mutation.HeCleared() && len(_u.mutation.HeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VuKhi.he"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *VuKhiUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VuKhiUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *VuKhiUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vukhi.Table, vukhi.Columns, sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenVuKhi(); ok {
		_spec.SetField(vukhi.FieldTenVuKhi, field.TypeString, value)
	}
	if value, ok := _u.mutation.SatThuongCoBan(); ok {
		_spec.SetField(vukhi.FieldSatThuongCoBan, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSatThuongCoBan(); ok {
		_spec.AddField(vukhi.FieldSatThuongCoBan, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TocDoDanh(); ok {
		_spec.SetField(vukhi.FieldTocDoDanh, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTocDoDanh(); ok {
		_spec.AddField(vukhi.FieldTocDoDanh, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TamDanh(); ok {
		_spec.SetField(vukhi.FieldTamDanh, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTamDanh(); ok {
		_spec.AddField(vukhi.FieldTamDanh, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MoTa(); ok {
		_spec.SetField(vukhi.FieldMoTa, field.TypeString, value)
	}
	if _u.mutation.MoTaCleared() {
		_spec.ClearField(vukhi.FieldMoTa, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(vukhi.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(vukhi.FieldVersion, field.TypeInt64, value)
	}
	if _u.mutation.LoaiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.LoaiTable,
			Columns: []string{vukhi.LoaiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loaivukhi.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LoaiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.LoaiTable,
			Columns: []string{vukhi.LoaiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loaivukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DoHiemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.DoHiemTable,
			Columns: []string{vukhi.DoHiemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dohiem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DoHiemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.DoHiemTable,
			Columns: []string{vukhi.DoHiemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dohiem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.HeTable,
			Columns: []string{vukhi.HeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(he.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.HeTable,
			Columns: []string{vukhi.HeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(he.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vukhi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VuKhiUpdateOne is the builder for updating a single VuKhi entity.
type VuKhiUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *VuKhiMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTenVuKhi sets the "ten_vu_khi" field.
func (_u *VuKhiUpdateOne) SetTenVuKhi(v string) *VuKhiUpdateOne {
	_u.mutation.SetTenVuKhi(v)
	return _u
}

// SetNillableTenVuKhi sets the "ten_vu_khi" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableTenVuKhi(v *string) *VuKhiUpdateOne {
	if v != nil {
		_u.SetTenVuKhi(*v)
	}
	return _u
}

// SetSatThuongCoBan sets the "sat_thuong_co_ban" field.
func (_u *VuKhiUpdateOne) SetSatThuongCoBan(v int) *VuKhiUpdateOne {
	_u.mutation.ResetSatThuongCoBan()
	_u.mutation.SetSatThuongCoBan(v)
	return _u
}

// SetNillableSatThuongCoBan sets the "sat_thuong_co_ban" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableSatThuongCoBan(v *int) *VuKhiUpdateOne {
	if v != nil {
		_u.SetSatThuongCoBan(*v)
	}
	return _u
}

// AddSatThuongCoBan adds value to the "sat_thuong_co_ban" field.
func (_u *VuKhiUpdateOne) AddSatThuongCoBan(v int) *VuKhiUpdateOne {
	_u.mutation.AddSatThuongCoBan(v)
	return _u
}

// SetTocDoDanh sets the "toc_do_danh" field.
func (_u *VuKhiUpdateOne) SetTocDoDanh(v float64) *VuKhiUpdateOne {
	_u.mutation.ResetTocDoDanh()
	_u.mutation.SetTocDoDanh(v)
	return _u
}

// SetNillableTocDoDanh sets the "toc_do_danh" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableTocDoDanh(v *float64) *VuKhiUpdateOne {
	if v != nil {
		_u.SetTocDoDanh(*v)
	}
	return _u
}

// AddTocDoDanh adds value to the "toc_do_danh" field.
func (_u *VuKhiUpdateOne) AddTocDoDanh(v float64) *VuKhiUpdateOne {
	_u.mutation.AddTocDoDanh(v)
	return _u
}

// SetTamDanh sets the "tam_danh" field.
func (_u *VuKhiUpdateOne) SetTamDanh(v int) *VuKhiUpdateOne {
	_u.mutation.ResetTamDanh()
	_u.mutation.SetTamDanh(v)
	return _u
}

// SetNillableTamDanh sets the "tam_danh" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableTamDanh(v *int) *VuKhiUpdateOne {
	if v != nil {
		_u.SetTamDanh(*v)
	}
	return _u
}

// AddTamDanh adds value to the "tam_danh" field.
func (_u *VuKhiUpdateOne) AddTamDanh(v int) *VuKhiUpdateOne {
	_u.mutation.AddTamDanh(v)
	return _u
}

// SetMoTa sets the "mo_ta" field.
func (_u *VuKhiUpdateOne) SetMoTa(v string) *VuKhiUpdateOne {
	_u.mutation.SetMoTa(v)
	return _u
}

// SetNillableMoTa sets the "mo_ta" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableMoTa(v *string) *VuKhiUpdateOne {
	if v != nil {
		_u.SetMoTa(*v)
	}
	return _u
}

// ClearMoTa clears the value of the "mo_ta" field.
func (_u *VuKhiUpdateOne) ClearMoTa() *VuKhiUpdateOne {
	_u.mutation.ClearMoTa()
	return _u
}

// SetVersion sets the "version" field.
func (_u *VuKhiUpdateOne) SetVersion(v int64) *VuKhiUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableVersion(v *int64) *VuKhiUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *VuKhiUpdateOne) AddVersion(v int64) *VuKhiUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetMaLoai sets the "ma_loai" field.
func (_u *VuKhiUpdateOne) SetMaLoai(v int) *VuKhiUpdateOne {
	_u.mutation.SetMaLoai(v)
	return _u
}

// SetNillableMaLoai sets the "ma_loai" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableMaLoai(v *int) *VuKhiUpdateOne {
	if v != nil {
		_u.SetMaLoai(*v)
	}
	return _u
}

// SetMaDoHiem sets the "ma_do_hiem" field.
func (_u *VuKhiUpdateOne) SetMaDoHiem(v int) *VuKhiUpdateOne {
	_u.mutation.SetMaDoHiem(v)
	return _u
}

// SetNillableMaDoHiem sets the "ma_do_hiem" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableMaDoHiem(v *int) *VuKhiUpdateOne {
	if v != nil {
		_u.SetMaDoHiem(*v)
	}
	return _u
}

// SetMaHe sets the "ma_he" field.
func (_u *VuKhiUpdateOne) SetMaHe(v int) *VuKhiUpdateOne {
	_u.mutation.SetMaHe(v)
	return _u
}

// SetNillableMaHe sets the "ma_he" field if the given value is not nil.
func (_u *VuKhiUpdateOne) SetNillableMaHe(v *int) *VuKhiUpdateOne {
	if v != nil {
		_u.SetMaHe(*v)
	}
	return _u
}

// SetLoaiID sets the "loai" edge to the LoaiVuKhi entity by ID.
func (_u *VuKhiUpdateOne) SetLoaiID(id int) *VuKhiUpdateOne {
	_u.mutation.SetLoaiID(id)
	return _u
}

// SetLoai sets the "loai" edge to the LoaiVuKhi entity.
func (_u *VuKhiUpdateOne) SetLoai(v *LoaiVuKhi) *VuKhiUpdateOne {
	return _u.SetLoaiID(v.ID)
}

// SetDoHiemID sets the "do_hiem" edge to the DoHiem entity by ID.
func (_u *VuKhiUpdateOne) SetDoHiemID(id int) *VuKhiUpdateOne {
	_u.mutation.SetDoHiemID(id)
	return _u
}

// SetDoHiem sets the "do_hiem" edge to the DoHiem entity.
func (_u *VuKhiUpdateOne) SetDoHiem(v *DoHiem) *VuKhiUpdateOne {
	return _u.SetDoHiemID(v.ID)
}

// SetHeID sets the "he" edge to the He entity by ID.
func (_u *VuKhiUpdateOne) SetHeID(id int) *VuKhiUpdateOne {
	_u.mutation.SetHeID(id)
	return _u
}

// SetHe sets the "he" edge to the He entity.
func (_u *VuKhiUpdateOne) SetHe(v *He) *VuKhiUpdateOne {
	return _u.SetHeID(v.ID)
}

// Mutation returns the VuKhiMutation object of the builder.
func (_u *VuKhiUpdateOne) Mutation() *VuKhiMutation {
	return _u.mutation
}

// ClearLoai clears the "loai" edge to the LoaiVuKhi entity.
func (_u *VuKhiUpdateOne) ClearLoai() *VuKhiUpdateOne {
	_u.mutation.ClearLoai()
	return _u
}

// ClearDoHiem clears the "do_hiem" edge to the DoHiem entity.
func (_u *VuKhiUpdateOne) ClearDoHiem() *VuKhiUpdateOne {
	_u.mutation.ClearDoHiem()
	return _u
}

// ClearHe clears the "he" edge to the He entity.
func (_u *VuKhiUpdateOne) ClearHe() *VuKhiUpdateOne {
	_u.mutation.ClearHe()
	return _u
}

// Where appends a list predicates to the VuKhiUpdate builder.
func (_u *VuKhiUpdateOne) Where(ps ...predicate.VuKhi) *VuKhiUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VuKhiUpdateOne) Select(field string, fields ...string) *VuKhiUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VuKhi entity.
func (_u *VuKhiUpdateOne) Save(ctx context.Context) (*VuKhi, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VuKhiUpdateOne) SaveX(ctx context.Context) *VuKhi {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VuKhiUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VuKhiUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VuKhiUpdateOne) check() error {
	if v, ok := _u.mutation.TenVuKhi(); ok {
		if err := vukhi.TenVuKhiValidator(v); err != nil {
			return &ValidationError{Name: "ten_vu_khi", err: fmt.Errorf(`ent: validator failed for field "VuKhi.ten_vu_khi": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MoTa(); ok {
		if err := vukhi.MoTaValidator(v); err != nil {
			return &ValidationError{Name: "mo_ta", err: fmt.Errorf(`ent: validator failed for field "VuKhi.mo_ta": %w`, err)}
		}
	}
	if _u.mutation.LoaiCleared() && len(_u.mutation.LoaiIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VuKhi.loai"`)
	}
	if _u.mutation.DoHiemCleared() && len(_u.mutation.DoHiemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VuKhi.do_hiem"`)
	}
	if _u.mutation.HeCleared() && len(_u.mutation.HeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VuKhi.he"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *VuKhiUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VuKhiUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *VuKhiUpdateOne) sqlSave(ctx context.Context) (_node *VuKhi, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vukhi.Table, vukhi.Columns, sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VuKhi.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vukhi.FieldID)
		for _, f := range fields {
			if !vukhi.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vukhi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenVuKhi(); ok {
		_spec.SetField(vukhi.FieldTenVuKhi, field.TypeString, value)
	}
	if value, ok := _u.mutation.SatThuongCoBan(); ok {
		_spec.SetField(vukhi.FieldSatThuongCoBan, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSatThuongCoBan(); ok {
		_spec.AddField(vukhi.FieldSatThuongCoBan, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TocDoDanh(); ok {
		_spec.SetField(vukhi.FieldTocDoDanh, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTocDoDanh(); ok {
		_spec.AddField(vukhi.FieldTocDoDanh, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TamDanh(); ok {
		_spec.SetField(vukhi.FieldTamDanh, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTamDanh(); ok {
		_spec.AddField(vukhi.FieldTamDanh, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MoTa(); ok {
		_spec.SetField(vukhi.FieldMoTa, field.TypeString, value)
	}
	if _u.mutation.MoTaCleared() {
		_spec.ClearField(vukhi.FieldMoTa, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(vukhi.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(vukhi.FieldVersion, field.TypeInt64, value)
	}
	if _u.mutation.LoaiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.LoaiTable,
			Columns: []string{vukhi.LoaiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loaivukhi.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LoaiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.LoaiTable,
			Columns: []string{vukhi.LoaiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loaivukhi.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DoHiemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.DoHiemTable,
			Columns: []string{vukhi.DoHiemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dohiem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DoHiemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.DoHiemTable,
			Columns: []string{vukhi.DoHiemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dohiem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.HeTable,
			Columns: []string{vukhi.HeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(he.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vukhi.HeTable,
			Columns: []string{vukhi.HeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(he.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &VuKhi{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vukhi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
