// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"game/ent/predicate"
	"game/ent/vukhi"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VuKhiDelete is the builder for deleting a VuKhi entity.
type VuKhiDelete struct {
	config
	hooks    []Hook
	mutation *VuKhiMutation
}

// Where appends a list predicates to the VuKhiDelete builder.
func (_d *VuKhiDelete) Where(ps ...predicate.VuKhi) *VuKhiDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VuKhiDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VuKhiDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VuKhiDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(vukhi.Table, sqlgraph.NewFieldSpec(vukhi.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VuKhiDeleteOne is the builder for deleting a single VuKhi entity.
type VuKhiDeleteOne struct {
	_d *VuKhiDelete
}

// Where appends a list predicates to the VuKhiDelete builder.
func (_d *VuKhiDeleteOne) Where(ps ...predicate.VuKhi) *VuKhiDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VuKhiDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{vukhi.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VuKhiDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
