// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"game/ent/dohiem"
	"game/ent/he"
	"game/ent/loaivukhi"
	"game/ent/vukhi"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// VuKhi is the model entity for the VuKhi schema.
type VuKhi struct {
	config `json:"-"`
	// ID of the ent.
	// Mã vũ khí
	ID int `json:"id,omitempty"`
	// TenVuKhi holds the value of the "ten_vu_khi" field.
	TenVuKhi string `json:"ten_vu_khi,omitempty"`
	// SatThuongCoBan holds the value of the "sat_thuong_co_ban" field.
	SatThuongCoBan int `json:"sat_thuong_co_ban,omitempty"`
	// TocDoDanh holds the value of the "toc_do_danh" field.
	TocDoDanh float64 `json:"toc_do_danh,omitempty"`
	// TamDanh holds the value of the "tam_danh" field.
	TamDanh int `json:"tam_danh,omitempty"`
	// MoTa holds the value of the "mo_ta" field.
	MoTa string `json:"mo_ta,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// FK -> loai_vu_khis.ma_loai_vu_khi
	MaLoaiVuKhi int `json:"ma_loai_vu_khi,omitempty"`
	// FK -> do_hiems.ma_do_hiem
	MaDoHiem int `json:"ma_do_hiem,omitempty"`
	// FK -> hes.ma_he
	MaHe int `json:"ma_he,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VuKhiQuery when eager-loading is set.
	Edges        VuKhiEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VuKhiEdges holds the relations/edges for other nodes in the graph.
type VuKhiEdges struct {
	// Loai holds the value of the loai edge.
	Loai *LoaiVuKhi `json:"loai,omitempty"`
	// DoHiem holds the value of the do_hiem edge.
	DoHiem *DoHiem `json:"do_hiem,omitempty"`
	// He holds the value of the he edge.
	He *He `json:"he,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// LoaiOrErr returns the Loai value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VuKhiEdges) LoaiOrErr() (*LoaiVuKhi, error) {
	if e.Loai != nil {
		return e.Loai, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: loaivukhi.Label}
	}
	return nil, &NotLoadedError{edge: "loai"}
}

// DoHiemOrErr returns the DoHiem value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VuKhiEdges) DoHiemOrErr() (*DoHiem, error) {
	if e.DoHiem != nil {
		return e.DoHiem, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: dohiem.Label}
	}
	return nil, &NotLoadedError{edge: "do_hiem"}
}

// HeOrErr returns the He value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VuKhiEdges) HeOrErr() (*He, error) {
	if e.He != nil {
		return e.He, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: he.Label}
	}
	return nil, &NotLoadedError{edge: "he"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VuKhi) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vukhi.FieldTocDoDanh:
			values[i] = new(sql.NullFloat64)
		case vukhi.FieldID, vukhi.FieldSatThuongCoBan, vukhi.FieldTamDanh, vukhi.FieldVersion, vukhi.FieldMaLoaiVuKhi, vukhi.FieldMaDoHiem, vukhi.FieldMaHe:
			values[i] = new(sql.NullInt64)
		case vukhi.FieldTenVuKhi, vukhi.FieldMoTa:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VuKhi fields.
func (_m *VuKhi) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vukhi.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case vukhi.FieldTenVuKhi:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ten_vu_khi", values[i])
			} else if value.Valid {
				_m.TenVuKhi = value.String
			}
		case vukhi.FieldSatThuongCoBan:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sat_thuong_co_ban", values[i])
			} else if value.Valid {
				_m.SatThuongCoBan = int(value.Int64)
			}
		case vukhi.FieldTocDoDanh:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field toc_do_danh", values[i])
			} else if value.Valid {
				_m.TocDoDanh = value.Float64
			}
		case vukhi.FieldTamDanh:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tam_danh", values[i])
			} else if value.Valid {
				_m.TamDanh = int(value.Int64)
			}
		case vukhi.FieldMoTa:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mo_ta", values[i])
			} else if value.Valid {
				_m.MoTa = value.String
			}
		case vukhi.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case vukhi.FieldMaLoaiVuKhi:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ma_loai_vu_khi", values[i])
			} else if value.Valid {
				_m.MaLoaiVuKhi = int(value.Int64)
			}
		case vukhi.FieldMaDoHiem:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ma_do_hiem", values[i])
			} else if value.Valid {
				_m.MaDoHiem = int(value.Int64)
			}
		case vukhi.FieldMaHe:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ma_he", values[i])
			} else if value.Valid {
				_m.MaHe = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VuKhi.
// This includes values selected through modifiers, order, etc.
func (_m *VuKhi) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLoai queries the "loai" edge of the VuKhi entity.
func (_m *VuKhi) QueryLoai() *LoaiVuKhiQuery {
	return NewVuKhiClient(_m.config).QueryLoai(_m)
}

// QueryDoHiem queries the "do_hiem" edge of the VuKhi entity.
func (_m *VuKhi) QueryDoHiem() *DoHiemQuery {
	return NewVuKhiClient(_m.config).QueryDoHiem(_m)
}

// QueryHe queries the "he" edge of the VuKhi entity.
func (_m *VuKhi) QueryHe() *HeQuery {
	return NewVuKhiClient(_m.config).QueryHe(_m)
}

// Update returns a builder for updating this VuKhi.
// Note that you need to call VuKhi.Unwrap() before calling this method if this VuKhi
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VuKhi) Update() *VuKhiUpdateOne {
	return NewVuKhiClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VuKhi entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VuKhi) Unwrap() *VuKhi {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VuKhi is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VuKhi) String() string {
	var builder strings.Builder
	builder.WriteString("VuKhi(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ten_vu_khi=")
	builder.WriteString(_m.TenVuKhi)
	builder.WriteString(", ")
	builder.WriteString("sat_thuong_co_ban=")
	builder.WriteString(fmt.Sprintf("%v", _m.SatThuongCoBan))
	builder.WriteString(", ")
	builder.WriteString("toc_do_danh=")
	builder.WriteString(fmt.Sprintf("%v", _m.TocDoDanh))
	builder.WriteString(", ")
	builder.WriteString("tam_danh=")
	builder.WriteString(fmt.Sprintf("%v", _m.TamDanh))
	builder.WriteString(", ")
	builder.WriteString("mo_ta=")
	builder.WriteString(_m.MoTa)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("ma_loai_vu_khi=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaLoaiVuKhi))
	builder.WriteString(", ")
	builder.WriteString("ma_do_hiem=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaDoHiem))
	builder.WriteString(", ")
	builder.WriteString("ma_he=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaHe))
	builder.WriteByte(')')
	return builder.String()
}

// VuKhis is a parsable slice of VuKhi.
type VuKhis []*VuKhi
