// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/he.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type He struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaHe          int32                  `protobuf:"varint,1,opt,name=ma_he,json=maHe,proto3" json:"ma_he,omitempty"`
	TenHe         string                 `protobuf:"bytes,2,opt,name=ten_he,json=tenHe,proto3" json:"ten_he,omitempty"`
	MoTa          string                 `protobuf:"bytes,3,opt,name=mo_ta,json=moTa,proto3" json:"mo_ta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *He) Reset() {
	*x = He{}
	mi := &file_proto_he_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *He) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*He) ProtoMessage() {}

func (x *He) ProtoReflect() protoreflect.Message {
	mi := &file_proto_he_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use He.ProtoReflect.Descriptor instead.
func (*He) Descriptor() ([]byte, []int) {
	return file_proto_he_proto_rawDescGZIP(), []int{0}
}

func (x *He) GetMaHe() int32 {
	if x != nil {
		return x.MaHe
	}
	return 0
}

func (x *He) GetTenHe() string {
	if x != nil {
		return x.TenHe
	}
	return ""
}

func (x *He) GetMoTa() string {
	if x != nil {
		return x.MoTa
	}
	return ""
}

type TaoHeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaHe          int32                  `protobuf:"varint,1,opt,name=ma_he,json=maHe,proto3" json:"ma_he,omitempty"`
	TenHe         string                 `protobuf:"bytes,2,opt,name=ten_he,json=tenHe,proto3" json:"ten_he,omitempty"`
	MoTa          string                 `protobuf:"bytes,3,opt,name=mo_ta,json=moTa,proto3" json:"mo_ta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaoHeRequest) Reset() {
	*x = TaoHeRequest{}
	mi := &file_proto_he_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaoHeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoHeRequest) ProtoMessage() {}

func (x *TaoHeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_he_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoHeRequest.ProtoReflect.Descriptor instead.
func (*TaoHeRequest) Descriptor() ([]byte, []int) {
	return file_proto_he_proto_rawDescGZIP(), []int{1}
}

func (x *TaoHeRequest) GetMaHe() int32 {
	if x != nil {
		return x.MaHe
	}
	return 0
}

func (x *TaoHeRequest) GetTenHe() string {
	if x != nil {
		return x.TenHe
	}
	return ""
}

func (x *TaoHeRequest) GetMoTa() string {
	if x != nil {
		return x.MoTa
	}
	return ""
}

type CapNhatTheoTenHeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenHeNew      string                 `protobuf:"bytes,1,opt,name=ten_he_new,json=tenHeNew,proto3" json:"ten_he_new,omitempty"`
	TenHe         string                 `protobuf:"bytes,2,opt,name=ten_he,json=tenHe,proto3" json:"ten_he,omitempty"`
	MoTa          string                 `protobuf:"bytes,3,opt,name=mo_ta,json=moTa,proto3" json:"mo_ta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapNhatTheoTenHeRequest) Reset() {
	*x = CapNhatTheoTenHeRequest{}
	mi := &file_proto_he_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapNhatTheoTenHeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapNhatTheoTenHeRequest) ProtoMessage() {}

func (x *CapNhatTheoTenHeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_he_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapNhatTheoTenHeRequest.ProtoReflect.Descriptor instead.
func (*CapNhatTheoTenHeRequest) Descriptor() ([]byte, []int) {
	return file_proto_he_proto_rawDescGZIP(), []int{2}
}

func (x *CapNhatTheoTenHeRequest) GetTenHeNew() string {
	if x != nil {
		return x.TenHeNew
	}
	return ""
}

func (x *CapNhatTheoTenHeRequest) GetTenHe() string {
	if x != nil {
		return x.TenHe
	}
	return ""
}

func (x *CapNhatTheoTenHeRequest) GetMoTa() string {
	if x != nil {
		return x.MoTa
	}
	return ""
}

type XoaTheoTenHeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenHe         string                 `protobuf:"bytes,1,opt,name=ten_he,json=tenHe,proto3" json:"ten_he,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XoaTheoTenHeRequest) Reset() {
	*x = XoaTheoTenHeRequest{}
	mi := &file_proto_he_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XoaTheoTenHeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XoaTheoTenHeRequest) ProtoMessage() {}

func (x *XoaTheoTenHeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_he_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XoaTheoTenHeRequest.ProtoReflect.Descriptor instead.
func (*XoaTheoTenHeRequest) Descriptor() ([]byte, []int) {
	return file_proto_he_proto_rawDescGZIP(), []int{3}
}

func (x *XoaTheoTenHeRequest) GetTenHe() string {
	if x != nil {
		return x.TenHe
	}
	return ""
}

type XoaTheoTenHeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedName   string                 `protobuf:"bytes,1,opt,name=deleted_name,json=deletedName,proto3" json:"deleted_name,omitempty"`
	MaHe          int32                  `protobuf:"varint,2,opt,name=ma_he,json=maHe,proto3" json:"ma_he,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XoaTheoTenHeResponse) Reset() {
	*x = XoaTheoTenHeResponse{}
	mi := &file_proto_he_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XoaTheoTenHeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XoaTheoTenHeResponse) ProtoMessage() {}

func (x *XoaTheoTenHeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_he_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XoaTheoTenHeResponse.ProtoReflect.Descriptor instead.
func (*XoaTheoTenHeResponse) Descriptor() ([]byte, []int) {
	return file_proto_he_proto_rawDescGZIP(), []int{4}
}

func (x *XoaTheoTenHeResponse) GetDeletedName() string {
	if x != nil {
		return x.DeletedName
	}
	return ""
}

func (x *XoaTheoTenHeResponse) GetMaHe() int32 {
	if x != nil {
		return x.MaHe
	}
	return 0
}

type DanhSachHe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	ItemCount     int32                  `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	Items         []*He                  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanhSachHe) Reset() {
	*x = DanhSachHe{}
	mi := &file_proto_he_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanhSachHe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanhSachHe) ProtoMessage() {}

func (x *DanhSachHe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_he_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanhSachHe.ProtoReflect.Descriptor instead.
func (*DanhSachHe) Descriptor() ([]byte, []int) {
	return file_proto_he_proto_rawDescGZIP(), []int{5}
}

func (x *DanhSachHe) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DanhSachHe) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *DanhSachHe) GetItems() []*He {
	if x != nil {
		return x.Items
	}
	return nil
}

type DanhSachStringHe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanhSachStringHe) Reset() {
	*x = DanhSachStringHe{}
	mi := &file_proto_he_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanhSachStringHe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanhSachStringHe) ProtoMessage() {}

func (x *DanhSachStringHe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_he_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanhSachStringHe.ProtoReflect.Descriptor instead.
func (*DanhSachStringHe) Descriptor() ([]byte, []int) {
	return file_proto_he_proto_rawDescGZIP(), []int{6}
}

func (x *DanhSachStringHe) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DanhSachStringHe) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type TimKiemHeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ---- Tìm kiếm theo giá trị chính xác (Exact Match) ----
	MaHe  *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=ma_he,json=maHe,proto3" json:"ma_he,omitempty"`
	TenHe string                 `protobuf:"bytes,2,opt,name=ten_he,json=tenHe,proto3" json:"ten_he,omitempty"`
	MoTa  string                 `protobuf:"bytes,3,opt,name=mo_ta,json=moTa,proto3" json:"mo_ta,omitempty"`
	// ---- Tìm kiếm theo chuỗi (Like/Contains) ----
	Q string `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
	// ---- Range Search (Dành cho ID hoặc các thuộc tính số nếu có) ----
	MinMaHe *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=min_ma_he,json=minMaHe,proto3" json:"min_ma_he,omitempty"`
	MaxMaHe *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=max_ma_he,json=maxMaHe,proto3" json:"max_ma_he,omitempty"`
	// ---- Phân trang (Pagination) ----
	Limit  int32  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor string `protobuf:"bytes,11,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// ---- Sắp xếp (Ordering) ----
	ArrangeAsc    string `protobuf:"bytes,12,opt,name=arrange_asc,json=arrangeAsc,proto3" json:"arrange_asc,omitempty"`
	ArrangeDesc   string `protobuf:"bytes,13,opt,name=arrange_desc,json=arrangeDesc,proto3" json:"arrange_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimKiemHeRequest) Reset() {
	*x = TimKiemHeRequest{}
	mi := &file_proto_he_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimKiemHeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimKiemHeRequest) ProtoMessage() {}

func (x *TimKiemHeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_he_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimKiemHeRequest.ProtoReflect.Descriptor instead.
func (*TimKiemHeRequest) Descriptor() ([]byte, []int) {
	return file_proto_he_proto_rawDescGZIP(), []int{7}
}

func (x *TimKiemHeRequest) GetMaHe() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaHe
	}
	return nil
}

func (x *TimKiemHeRequest) GetTenHe() string {
	if x != nil {
		return x.TenHe
	}
	return ""
}

func (x *TimKiemHeRequest) GetMoTa() string {
	if x != nil {
		return x.MoTa
	}
	return ""
}

func (x *TimKiemHeRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *TimKiemHeRequest) GetMinMaHe() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinMaHe
	}
	return nil
}

func (x *TimKiemHeRequest) GetMaxMaHe() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxMaHe
	}
	return nil
}

func (x *TimKiemHeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TimKiemHeRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *TimKiemHeRequest) GetArrangeAsc() string {
	if x != nil {
		return x.ArrangeAsc
	}
	return ""
}

func (x *TimKiemHeRequest) GetArrangeDesc() string {
	if x != nil {
		return x.ArrangeDesc
	}
	return ""
}

var File_proto_he_proto protoreflect.FileDescriptor

const file_proto_he_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/he.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"E\n" +
	"\x02He\x12\x13\n" +
	"\x05ma_he\x18\x01 \x01(\x05R\x04maHe\x12\x15\n" +
	"\x06ten_he\x18\x02 \x01(\tR\x05tenHe\x12\x13\n" +
	"\x05mo_ta\x18\x03 \x01(\tR\x04moTa\"O\n" +
	"\fTaoHeRequest\x12\x13\n" +
	"\x05ma_he\x18\x01 \x01(\x05R\x04maHe\x12\x15\n" +
	"\x06ten_he\x18\x02 \x01(\tR\x05tenHe\x12\x13\n" +
	"\x05mo_ta\x18\x03 \x01(\tR\x04moTa\"c\n" +
	"\x17CapNhatTheoTenHeRequest\x12\x1c\n" +
	"\n" +
	"ten_he_new\x18\x01 \x01(\tR\btenHeNew\x12\x15\n" +
	"\x06ten_he\x18\x02 \x01(\tR\x05tenHe\x12\x13\n" +
	"\x05mo_ta\x18\x03 \x01(\tR\x04moTa\",\n" +
	"\x13XoaTheoTenHeRequest\x12\x15\n" +
	"\x06ten_he\x18\x01 \x01(\tR\x05tenHe\"N\n" +
	"\x14XoaTheoTenHeResponse\x12!\n" +
	"\fdeleted_name\x18\x01 \x01(\tR\vdeletedName\x12\x13\n" +
	"\x05ma_he\x18\x02 \x01(\x05R\x04maHe\"_\n" +
	"\n" +
	"DanhSachHe\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1d\n" +
	"\n" +
	"item_count\x18\x02 \x01(\x05R\titemCount\x12\x1c\n" +
	"\x05items\x18\x03 \x03(\v2\x06.v1.HeR\x05items\">\n" +
	"\x10DanhSachStringHe\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\"\xe2\x02\n" +
	"\x10TimKiemHeRequest\x120\n" +
	"\x05ma_he\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04maHe\x12\x15\n" +
	"\x06ten_he\x18\x02 \x01(\tR\x05tenHe\x12\x13\n" +
	"\x05mo_ta\x18\x03 \x01(\tR\x04moTa\x12\f\n" +
	"\x01q\x18\x04 \x01(\tR\x01q\x127\n" +
	"\tmin_ma_he\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\aminMaHe\x127\n" +
	"\tmax_ma_he\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\amaxMaHe\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\v \x01(\tR\x06cursor\x12\x1f\n" +
	"\varrange_asc\x18\f \x01(\tR\n" +
	"arrangeAsc\x12!\n" +
	"\farrange_desc\x18\r \x01(\tR\varrangeDesc2\xdb\x04\n" +
	"\tHeService\x12=\n" +
	"\bCreateHe\x12\x10.v1.TaoHeRequest\x1a\x06.v1.He\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/he/ent/post\x12b\n" +
	"\x0eUpdateByNameHe\x12\x1b.v1.CapNhatTheoTenHeRequest\x1a\x06.v1.He\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /he/ent/put-by-name/{ten_he_new}\x12l\n" +
	"\x0eDeleteByNameHe\x12\x17.v1.XoaTheoTenHeRequest\x1a\x18.v1.XoaTheoTenHeResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/he/ent/delete-by-name/{ten_he}\x12J\n" +
	"\bGetAllHe\x12\x16.google.protobuf.Empty\x1a\x0e.v1.DanhSachHe\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/he/ent/getall\x12P\n" +
	"\vGetAllTenHe\x12\x16.google.protobuf.Empty\x1a\x14.v1.DanhSachStringHe\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/he/ent/ten\x12R\n" +
	"\fGetAllMoTaHe\x12\x16.google.protobuf.Empty\x1a\x14.v1.DanhSachStringHe\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/he/ent/mota\x12K\n" +
	"\bSearchHe\x12\x14.v1.TimKiemHeRequest\x1a\x0e.v1.DanhSachHe\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/he/ent/searchB\x12Z\x10game/proto/v1;v1b\x06proto3"

var (
	file_proto_he_proto_rawDescOnce sync.Once
	file_proto_he_proto_rawDescData []byte
)

func file_proto_he_proto_rawDescGZIP() []byte {
	file_proto_he_proto_rawDescOnce.Do(func() {
		file_proto_he_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_he_proto_rawDesc), len(file_proto_he_proto_rawDesc)))
	})
	return file_proto_he_proto_rawDescData
}

var file_proto_he_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_he_proto_goTypes = []any{
	(*He)(nil),                      // 0: v1.He
	(*TaoHeRequest)(nil),            // 1: v1.TaoHeRequest
	(*CapNhatTheoTenHeRequest)(nil), // 2: v1.CapNhatTheoTenHeRequest
	(*XoaTheoTenHeRequest)(nil),     // 3: v1.XoaTheoTenHeRequest
	(*XoaTheoTenHeResponse)(nil),    // 4: v1.XoaTheoTenHeResponse
	(*DanhSachHe)(nil),              // 5: v1.DanhSachHe
	(*DanhSachStringHe)(nil),        // 6: v1.DanhSachStringHe
	(*TimKiemHeRequest)(nil),        // 7: v1.TimKiemHeRequest
	(*wrapperspb.Int32Value)(nil),   // 8: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),           // 9: google.protobuf.Empty
}
var file_proto_he_proto_depIdxs = []int32{
	0,  // 0: v1.DanhSachHe.items:type_name -> v1.He
	8,  // 1: v1.TimKiemHeRequest.ma_he:type_name -> google.protobuf.Int32Value
	8,  // 2: v1.TimKiemHeRequest.min_ma_he:type_name -> google.protobuf.Int32Value
	8,  // 3: v1.TimKiemHeRequest.max_ma_he:type_name -> google.protobuf.Int32Value
	1,  // 4: v1.HeService.CreateHe:input_type -> v1.TaoHeRequest
	2,  // 5: v1.HeService.UpdateByNameHe:input_type -> v1.CapNhatTheoTenHeRequest
	3,  // 6: v1.HeService.DeleteByNameHe:input_type -> v1.XoaTheoTenHeRequest
	9,  // 7: v1.HeService.GetAllHe:input_type -> google.protobuf.Empty
	9,  // 8: v1.HeService.GetAllTenHe:input_type -> google.protobuf.Empty
	9,  // 9: v1.HeService.GetAllMoTaHe:input_type -> google.protobuf.Empty
	7,  // 10: v1.HeService.SearchHe:input_type -> v1.TimKiemHeRequest
	0,  // 11: v1.HeService.CreateHe:output_type -> v1.He
	0,  // 12: v1.HeService.UpdateByNameHe:output_type -> v1.He
	4,  // 13: v1.HeService.DeleteByNameHe:output_type -> v1.XoaTheoTenHeResponse
	5,  // 14: v1.HeService.GetAllHe:output_type -> v1.DanhSachHe
	6,  // 15: v1.HeService.GetAllTenHe:output_type -> v1.DanhSachStringHe
	6,  // 16: v1.HeService.GetAllMoTaHe:output_type -> v1.DanhSachStringHe
	5,  // 17: v1.HeService.SearchHe:output_type -> v1.DanhSachHe
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_he_proto_init() }
func file_proto_he_proto_init() {
	if File_proto_he_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_he_proto_rawDesc), len(file_proto_he_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_he_proto_goTypes,
		DependencyIndexes: file_proto_he_proto_depIdxs,
		MessageInfos:      file_proto_he_proto_msgTypes,
	}.Build()
	File_proto_he_proto = out.File
	file_proto_he_proto_goTypes = nil
	file_proto_he_proto_depIdxs = nil
}
