// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/loaivukhi.proto

/*
Package v1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package v1

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_LoaiVuKhiService_CreateLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, client LoaiVuKhiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq TaoLoaiVuKhiRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.CreateLoaiVuKhi(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_LoaiVuKhiService_CreateLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, server LoaiVuKhiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq TaoLoaiVuKhiRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.CreateLoaiVuKhi(ctx, &protoReq)
	return msg, metadata, err
}

func request_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, client LoaiVuKhiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq CapNhatTheoTenLoaiVuKhiRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	val, ok := pathParams["ten_loai_vu_khi_new"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ten_loai_vu_khi_new")
	}
	protoReq.TenLoaiVuKhiNew, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ten_loai_vu_khi_new", err)
	}
	msg, err := client.UpdateByNameLoaiVuKhi(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, server LoaiVuKhiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq CapNhatTheoTenLoaiVuKhiRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	val, ok := pathParams["ten_loai_vu_khi_new"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ten_loai_vu_khi_new")
	}
	protoReq.TenLoaiVuKhiNew, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ten_loai_vu_khi_new", err)
	}
	msg, err := server.UpdateByNameLoaiVuKhi(ctx, &protoReq)
	return msg, metadata, err
}

func request_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, client LoaiVuKhiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq XoaTheoTenLoaiVuKhiRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	val, ok := pathParams["ten_loai_vu_khi"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ten_loai_vu_khi")
	}
	protoReq.TenLoaiVuKhi, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ten_loai_vu_khi", err)
	}
	msg, err := client.DeleteByNameLoaiVuKhi(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, server LoaiVuKhiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq XoaTheoTenLoaiVuKhiRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["ten_loai_vu_khi"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "ten_loai_vu_khi")
	}
	protoReq.TenLoaiVuKhi, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "ten_loai_vu_khi", err)
	}
	msg, err := server.DeleteByNameLoaiVuKhi(ctx, &protoReq)
	return msg, metadata, err
}

func request_LoaiVuKhiService_GetAllLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, client LoaiVuKhiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq emptypb.Empty
		metadata runtime.ServerMetadata
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.GetAllLoaiVuKhi(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_LoaiVuKhiService_GetAllLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, server LoaiVuKhiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq emptypb.Empty
		metadata runtime.ServerMetadata
	)
	msg, err := server.GetAllLoaiVuKhi(ctx, &protoReq)
	return msg, metadata, err
}

func request_LoaiVuKhiService_GetAllTenLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, client LoaiVuKhiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq emptypb.Empty
		metadata runtime.ServerMetadata
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.GetAllTenLoaiVuKhi(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_LoaiVuKhiService_GetAllTenLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, server LoaiVuKhiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq emptypb.Empty
		metadata runtime.ServerMetadata
	)
	msg, err := server.GetAllTenLoaiVuKhi(ctx, &protoReq)
	return msg, metadata, err
}

func request_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, client LoaiVuKhiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq emptypb.Empty
		metadata runtime.ServerMetadata
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.GetAllMoTaLoaiVuKhi(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, server LoaiVuKhiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq emptypb.Empty
		metadata runtime.ServerMetadata
	)
	msg, err := server.GetAllMoTaLoaiVuKhi(ctx, &protoReq)
	return msg, metadata, err
}

func request_LoaiVuKhiService_SearchLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, client LoaiVuKhiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq TimKiemLoaiVuKhiRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.SearchLoaiVuKhi(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_LoaiVuKhiService_SearchLoaiVuKhi_0(ctx context.Context, marshaler runtime.Marshaler, server LoaiVuKhiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq TimKiemLoaiVuKhiRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.SearchLoaiVuKhi(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterLoaiVuKhiServiceHandlerServer registers the http handlers for service LoaiVuKhiService to "mux".
// UnaryRPC     :call LoaiVuKhiServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterLoaiVuKhiServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterLoaiVuKhiServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server LoaiVuKhiServiceServer) error {
	mux.Handle(http.MethodPost, pattern_LoaiVuKhiService_CreateLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/v1.LoaiVuKhiService/CreateLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/post"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LoaiVuKhiService_CreateLoaiVuKhi_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_CreateLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPut, pattern_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/v1.LoaiVuKhiService/UpdateByNameLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/put-by-name/{ten_loai_vu_khi_new}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodDelete, pattern_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/v1.LoaiVuKhiService/DeleteByNameLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/delete-by-name/{ten_loai_vu_khi}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_LoaiVuKhiService_GetAllLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/v1.LoaiVuKhiService/GetAllLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/getall"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LoaiVuKhiService_GetAllLoaiVuKhi_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_GetAllLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_LoaiVuKhiService_GetAllTenLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/v1.LoaiVuKhiService/GetAllTenLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/ten"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LoaiVuKhiService_GetAllTenLoaiVuKhi_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_GetAllTenLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/v1.LoaiVuKhiService/GetAllMoTaLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/mota"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_LoaiVuKhiService_SearchLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/v1.LoaiVuKhiService/SearchLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/search"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LoaiVuKhiService_SearchLoaiVuKhi_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_SearchLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterLoaiVuKhiServiceHandlerFromEndpoint is same as RegisterLoaiVuKhiServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterLoaiVuKhiServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterLoaiVuKhiServiceHandler(ctx, mux, conn)
}

// RegisterLoaiVuKhiServiceHandler registers the http handlers for service LoaiVuKhiService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterLoaiVuKhiServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterLoaiVuKhiServiceHandlerClient(ctx, mux, NewLoaiVuKhiServiceClient(conn))
}

// RegisterLoaiVuKhiServiceHandlerClient registers the http handlers for service LoaiVuKhiService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "LoaiVuKhiServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "LoaiVuKhiServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "LoaiVuKhiServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterLoaiVuKhiServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client LoaiVuKhiServiceClient) error {
	mux.Handle(http.MethodPost, pattern_LoaiVuKhiService_CreateLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/v1.LoaiVuKhiService/CreateLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/post"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LoaiVuKhiService_CreateLoaiVuKhi_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_CreateLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPut, pattern_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/v1.LoaiVuKhiService/UpdateByNameLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/put-by-name/{ten_loai_vu_khi_new}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodDelete, pattern_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/v1.LoaiVuKhiService/DeleteByNameLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/delete-by-name/{ten_loai_vu_khi}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_LoaiVuKhiService_GetAllLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/v1.LoaiVuKhiService/GetAllLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/getall"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LoaiVuKhiService_GetAllLoaiVuKhi_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_GetAllLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_LoaiVuKhiService_GetAllTenLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/v1.LoaiVuKhiService/GetAllTenLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/ten"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LoaiVuKhiService_GetAllTenLoaiVuKhi_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_GetAllTenLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/v1.LoaiVuKhiService/GetAllMoTaLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/mota"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_LoaiVuKhiService_SearchLoaiVuKhi_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/v1.LoaiVuKhiService/SearchLoaiVuKhi", runtime.WithHTTPPathPattern("/loaivukhi/ent/search"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LoaiVuKhiService_SearchLoaiVuKhi_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LoaiVuKhiService_SearchLoaiVuKhi_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_LoaiVuKhiService_CreateLoaiVuKhi_0       = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"loaivukhi", "ent", "post"}, ""))
	pattern_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"loaivukhi", "ent", "put-by-name", "ten_loai_vu_khi_new"}, ""))
	pattern_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"loaivukhi", "ent", "delete-by-name", "ten_loai_vu_khi"}, ""))
	pattern_LoaiVuKhiService_GetAllLoaiVuKhi_0       = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"loaivukhi", "ent", "getall"}, ""))
	pattern_LoaiVuKhiService_GetAllTenLoaiVuKhi_0    = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"loaivukhi", "ent", "ten"}, ""))
	pattern_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0   = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"loaivukhi", "ent", "mota"}, ""))
	pattern_LoaiVuKhiService_SearchLoaiVuKhi_0       = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"loaivukhi", "ent", "search"}, ""))
)

var (
	forward_LoaiVuKhiService_CreateLoaiVuKhi_0       = runtime.ForwardResponseMessage
	forward_LoaiVuKhiService_UpdateByNameLoaiVuKhi_0 = runtime.ForwardResponseMessage
	forward_LoaiVuKhiService_DeleteByNameLoaiVuKhi_0 = runtime.ForwardResponseMessage
	forward_LoaiVuKhiService_GetAllLoaiVuKhi_0       = runtime.ForwardResponseMessage
	forward_LoaiVuKhiService_GetAllTenLoaiVuKhi_0    = runtime.ForwardResponseMessage
	forward_LoaiVuKhiService_GetAllMoTaLoaiVuKhi_0   = runtime.ForwardResponseMessage
	forward_LoaiVuKhiService_SearchLoaiVuKhi_0       = runtime.ForwardResponseMessage
)
