// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/loaivukhi.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoaiVuKhi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaLoaiVuKhi   int32                  `protobuf:"varint,1,opt,name=ma_loai_vu_khi,json=maLoaiVuKhi,proto3" json:"ma_loai_vu_khi,omitempty"`
	TenLoaiVuKhi  string                 `protobuf:"bytes,2,opt,name=ten_loai_vu_khi,json=tenLoaiVuKhi,proto3" json:"ten_loai_vu_khi,omitempty"`
	MoTa          string                 `protobuf:"bytes,3,opt,name=mo_ta,json=moTa,proto3" json:"mo_ta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoaiVuKhi) Reset() {
	*x = LoaiVuKhi{}
	mi := &file_proto_loaivukhi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoaiVuKhi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoaiVuKhi) ProtoMessage() {}

func (x *LoaiVuKhi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loaivukhi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoaiVuKhi.ProtoReflect.Descriptor instead.
func (*LoaiVuKhi) Descriptor() ([]byte, []int) {
	return file_proto_loaivukhi_proto_rawDescGZIP(), []int{0}
}

func (x *LoaiVuKhi) GetMaLoaiVuKhi() int32 {
	if x != nil {
		return x.MaLoaiVuKhi
	}
	return 0
}

func (x *LoaiVuKhi) GetTenLoaiVuKhi() string {
	if x != nil {
		return x.TenLoaiVuKhi
	}
	return ""
}

func (x *LoaiVuKhi) GetMoTa() string {
	if x != nil {
		return x.MoTa
	}
	return ""
}

type TaoLoaiVuKhiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaLoaiVuKhi   int32                  `protobuf:"varint,1,opt,name=ma_loai_vu_khi,json=maLoaiVuKhi,proto3" json:"ma_loai_vu_khi,omitempty"`
	TenLoaiVuKhi  string                 `protobuf:"bytes,2,opt,name=ten_loai_vu_khi,json=tenLoaiVuKhi,proto3" json:"ten_loai_vu_khi,omitempty"`
	MoTa          string                 `protobuf:"bytes,3,opt,name=mo_ta,json=moTa,proto3" json:"mo_ta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaoLoaiVuKhiRequest) Reset() {
	*x = TaoLoaiVuKhiRequest{}
	mi := &file_proto_loaivukhi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaoLoaiVuKhiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaoLoaiVuKhiRequest) ProtoMessage() {}

func (x *TaoLoaiVuKhiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loaivukhi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaoLoaiVuKhiRequest.ProtoReflect.Descriptor instead.
func (*TaoLoaiVuKhiRequest) Descriptor() ([]byte, []int) {
	return file_proto_loaivukhi_proto_rawDescGZIP(), []int{1}
}

func (x *TaoLoaiVuKhiRequest) GetMaLoaiVuKhi() int32 {
	if x != nil {
		return x.MaLoaiVuKhi
	}
	return 0
}

func (x *TaoLoaiVuKhiRequest) GetTenLoaiVuKhi() string {
	if x != nil {
		return x.TenLoaiVuKhi
	}
	return ""
}

func (x *TaoLoaiVuKhiRequest) GetMoTa() string {
	if x != nil {
		return x.MoTa
	}
	return ""
}

type CapNhatTheoTenLoaiVuKhiRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenLoaiVuKhiNew string                 `protobuf:"bytes,1,opt,name=ten_loai_vu_khi_new,json=tenLoaiVuKhiNew,proto3" json:"ten_loai_vu_khi_new,omitempty"`
	TenLoaiVuKhi    string                 `protobuf:"bytes,2,opt,name=ten_loai_vu_khi,json=tenLoaiVuKhi,proto3" json:"ten_loai_vu_khi,omitempty"`
	MoTa            string                 `protobuf:"bytes,3,opt,name=mo_ta,json=moTa,proto3" json:"mo_ta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapNhatTheoTenLoaiVuKhiRequest) Reset() {
	*x = CapNhatTheoTenLoaiVuKhiRequest{}
	mi := &file_proto_loaivukhi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapNhatTheoTenLoaiVuKhiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapNhatTheoTenLoaiVuKhiRequest) ProtoMessage() {}

func (x *CapNhatTheoTenLoaiVuKhiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loaivukhi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapNhatTheoTenLoaiVuKhiRequest.ProtoReflect.Descriptor instead.
func (*CapNhatTheoTenLoaiVuKhiRequest) Descriptor() ([]byte, []int) {
	return file_proto_loaivukhi_proto_rawDescGZIP(), []int{2}
}

func (x *CapNhatTheoTenLoaiVuKhiRequest) GetTenLoaiVuKhiNew() string {
	if x != nil {
		return x.TenLoaiVuKhiNew
	}
	return ""
}

func (x *CapNhatTheoTenLoaiVuKhiRequest) GetTenLoaiVuKhi() string {
	if x != nil {
		return x.TenLoaiVuKhi
	}
	return ""
}

func (x *CapNhatTheoTenLoaiVuKhiRequest) GetMoTa() string {
	if x != nil {
		return x.MoTa
	}
	return ""
}

type XoaTheoTenLoaiVuKhiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenLoaiVuKhi  string                 `protobuf:"bytes,1,opt,name=ten_loai_vu_khi,json=tenLoaiVuKhi,proto3" json:"ten_loai_vu_khi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XoaTheoTenLoaiVuKhiRequest) Reset() {
	*x = XoaTheoTenLoaiVuKhiRequest{}
	mi := &file_proto_loaivukhi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XoaTheoTenLoaiVuKhiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XoaTheoTenLoaiVuKhiRequest) ProtoMessage() {}

func (x *XoaTheoTenLoaiVuKhiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loaivukhi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XoaTheoTenLoaiVuKhiRequest.ProtoReflect.Descriptor instead.
func (*XoaTheoTenLoaiVuKhiRequest) Descriptor() ([]byte, []int) {
	return file_proto_loaivukhi_proto_rawDescGZIP(), []int{3}
}

func (x *XoaTheoTenLoaiVuKhiRequest) GetTenLoaiVuKhi() string {
	if x != nil {
		return x.TenLoaiVuKhi
	}
	return ""
}

type XoaTheoTenLoaiVuKhiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedName   string                 `protobuf:"bytes,1,opt,name=deleted_name,json=deletedName,proto3" json:"deleted_name,omitempty"`
	MaLoaiVuKhi   int32                  `protobuf:"varint,2,opt,name=ma_loai_vu_khi,json=maLoaiVuKhi,proto3" json:"ma_loai_vu_khi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XoaTheoTenLoaiVuKhiResponse) Reset() {
	*x = XoaTheoTenLoaiVuKhiResponse{}
	mi := &file_proto_loaivukhi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XoaTheoTenLoaiVuKhiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XoaTheoTenLoaiVuKhiResponse) ProtoMessage() {}

func (x *XoaTheoTenLoaiVuKhiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loaivukhi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XoaTheoTenLoaiVuKhiResponse.ProtoReflect.Descriptor instead.
func (*XoaTheoTenLoaiVuKhiResponse) Descriptor() ([]byte, []int) {
	return file_proto_loaivukhi_proto_rawDescGZIP(), []int{4}
}

func (x *XoaTheoTenLoaiVuKhiResponse) GetDeletedName() string {
	if x != nil {
		return x.DeletedName
	}
	return ""
}

func (x *XoaTheoTenLoaiVuKhiResponse) GetMaLoaiVuKhi() int32 {
	if x != nil {
		return x.MaLoaiVuKhi
	}
	return 0
}

type DanhSachLoaiVuKhi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	ItemCount     int32                  `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	Items         []*LoaiVuKhi           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanhSachLoaiVuKhi) Reset() {
	*x = DanhSachLoaiVuKhi{}
	mi := &file_proto_loaivukhi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanhSachLoaiVuKhi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanhSachLoaiVuKhi) ProtoMessage() {}

func (x *DanhSachLoaiVuKhi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loaivukhi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanhSachLoaiVuKhi.ProtoReflect.Descriptor instead.
func (*DanhSachLoaiVuKhi) Descriptor() ([]byte, []int) {
	return file_proto_loaivukhi_proto_rawDescGZIP(), []int{5}
}

func (x *DanhSachLoaiVuKhi) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DanhSachLoaiVuKhi) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *DanhSachLoaiVuKhi) GetItems() []*LoaiVuKhi {
	if x != nil {
		return x.Items
	}
	return nil
}

type DanhSachStringLoaiVuKhi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanhSachStringLoaiVuKhi) Reset() {
	*x = DanhSachStringLoaiVuKhi{}
	mi := &file_proto_loaivukhi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanhSachStringLoaiVuKhi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanhSachStringLoaiVuKhi) ProtoMessage() {}

func (x *DanhSachStringLoaiVuKhi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loaivukhi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanhSachStringLoaiVuKhi.ProtoReflect.Descriptor instead.
func (*DanhSachStringLoaiVuKhi) Descriptor() ([]byte, []int) {
	return file_proto_loaivukhi_proto_rawDescGZIP(), []int{6}
}

func (x *DanhSachStringLoaiVuKhi) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DanhSachStringLoaiVuKhi) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type TimKiemLoaiVuKhiRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MaLoaiVuKhi  *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=ma_loai_vu_khi,json=maLoaiVuKhi,proto3" json:"ma_loai_vu_khi,omitempty"`
	TenLoaiVuKhi string                 `protobuf:"bytes,2,opt,name=ten_loai_vu_khi,json=tenLoaiVuKhi,proto3" json:"ten_loai_vu_khi,omitempty"`
	MoTa         string                 `protobuf:"bytes,3,opt,name=mo_ta,json=moTa,proto3" json:"mo_ta,omitempty"`
	// Pagination
	Limit          int32                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor         string                 `protobuf:"bytes,11,opt,name=cursor,proto3" json:"cursor,omitempty"`
	MinMaLoaiVuKhi *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=min_ma_loai_vu_khi,json=minMaLoaiVuKhi,proto3" json:"min_ma_loai_vu_khi,omitempty"`
	MaxMaLoaiVuKhi *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=max_ma_loai_vu_khi,json=maxMaLoaiVuKhi,proto3" json:"max_ma_loai_vu_khi,omitempty"`
	// Ordering
	ArrangeAsc    string `protobuf:"bytes,20,opt,name=arrange_asc,json=arrangeAsc,proto3" json:"arrange_asc,omitempty"`
	ArrangeDesc   string `protobuf:"bytes,21,opt,name=arrange_desc,json=arrangeDesc,proto3" json:"arrange_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimKiemLoaiVuKhiRequest) Reset() {
	*x = TimKiemLoaiVuKhiRequest{}
	mi := &file_proto_loaivukhi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimKiemLoaiVuKhiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimKiemLoaiVuKhiRequest) ProtoMessage() {}

func (x *TimKiemLoaiVuKhiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loaivukhi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimKiemLoaiVuKhiRequest.ProtoReflect.Descriptor instead.
func (*TimKiemLoaiVuKhiRequest) Descriptor() ([]byte, []int) {
	return file_proto_loaivukhi_proto_rawDescGZIP(), []int{7}
}

func (x *TimKiemLoaiVuKhiRequest) GetMaLoaiVuKhi() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaLoaiVuKhi
	}
	return nil
}

func (x *TimKiemLoaiVuKhiRequest) GetTenLoaiVuKhi() string {
	if x != nil {
		return x.TenLoaiVuKhi
	}
	return ""
}

func (x *TimKiemLoaiVuKhiRequest) GetMoTa() string {
	if x != nil {
		return x.MoTa
	}
	return ""
}

func (x *TimKiemLoaiVuKhiRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TimKiemLoaiVuKhiRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *TimKiemLoaiVuKhiRequest) GetMinMaLoaiVuKhi() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinMaLoaiVuKhi
	}
	return nil
}

func (x *TimKiemLoaiVuKhiRequest) GetMaxMaLoaiVuKhi() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxMaLoaiVuKhi
	}
	return nil
}

func (x *TimKiemLoaiVuKhiRequest) GetArrangeAsc() string {
	if x != nil {
		return x.ArrangeAsc
	}
	return ""
}

func (x *TimKiemLoaiVuKhiRequest) GetArrangeDesc() string {
	if x != nil {
		return x.ArrangeDesc
	}
	return ""
}

var File_proto_loaivukhi_proto protoreflect.FileDescriptor

const file_proto_loaivukhi_proto_rawDesc = "" +
	"\n" +
	"\x15proto/loaivukhi.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"l\n" +
	"\tLoaiVuKhi\x12#\n" +
	"\x0ema_loai_vu_khi\x18\x01 \x01(\x05R\vmaLoaiVuKhi\x12%\n" +
	"\x0ften_loai_vu_khi\x18\x02 \x01(\tR\ftenLoaiVuKhi\x12\x13\n" +
	"\x05mo_ta\x18\x03 \x01(\tR\x04moTa\"v\n" +
	"\x13TaoLoaiVuKhiRequest\x12#\n" +
	"\x0ema_loai_vu_khi\x18\x01 \x01(\x05R\vmaLoaiVuKhi\x12%\n" +
	"\x0ften_loai_vu_khi\x18\x02 \x01(\tR\ftenLoaiVuKhi\x12\x13\n" +
	"\x05mo_ta\x18\x03 \x01(\tR\x04moTa\"\x8a\x01\n" +
	"\x1eCapNhatTheoTenLoaiVuKhiRequest\x12,\n" +
	"\x13ten_loai_vu_khi_new\x18\x01 \x01(\tR\x0ftenLoaiVuKhiNew\x12%\n" +
	"\x0ften_loai_vu_khi\x18\x02 \x01(\tR\ftenLoaiVuKhi\x12\x13\n" +
	"\x05mo_ta\x18\x03 \x01(\tR\x04moTa\"C\n" +
	"\x1aXoaTheoTenLoaiVuKhiRequest\x12%\n" +
	"\x0ften_loai_vu_khi\x18\x01 \x01(\tR\ftenLoaiVuKhi\"e\n" +
	"\x1bXoaTheoTenLoaiVuKhiResponse\x12!\n" +
	"\fdeleted_name\x18\x01 \x01(\tR\vdeletedName\x12#\n" +
	"\x0ema_loai_vu_khi\x18\x02 \x01(\x05R\vmaLoaiVuKhi\"m\n" +
	"\x11DanhSachLoaiVuKhi\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1d\n" +
	"\n" +
	"item_count\x18\x02 \x01(\x05R\titemCount\x12#\n" +
	"\x05items\x18\x03 \x03(\v2\r.v1.LoaiVuKhiR\x05items\"E\n" +
	"\x17DanhSachStringLoaiVuKhi\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\"\x9b\x03\n" +
	"\x17TimKiemLoaiVuKhiRequest\x12@\n" +
	"\x0ema_loai_vu_khi\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\vmaLoaiVuKhi\x12%\n" +
	"\x0ften_loai_vu_khi\x18\x02 \x01(\tR\ftenLoaiVuKhi\x12\x13\n" +
	"\x05mo_ta\x18\x03 \x01(\tR\x04moTa\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\v \x01(\tR\x06cursor\x12G\n" +
	"\x12min_ma_loai_vu_khi\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0eminMaLoaiVuKhi\x12G\n" +
	"\x12max_ma_loai_vu_khi\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0emaxMaLoaiVuKhi\x12\x1f\n" +
	"\varrange_asc\x18\x14 \x01(\tR\n" +
	"arrangeAsc\x12!\n" +
	"\farrange_desc\x18\x15 \x01(\tR\varrangeDesc2\xa5\x06\n" +
	"\x10LoaiVuKhiService\x12Y\n" +
	"\x0fCreateLoaiVuKhi\x12\x17.v1.TaoLoaiVuKhiRequest\x1a\r.v1.LoaiVuKhi\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/loaivukhi/ent/post\x12\x87\x01\n" +
	"\x15UpdateByNameLoaiVuKhi\x12\".v1.CapNhatTheoTenLoaiVuKhiRequest\x1a\r.v1.LoaiVuKhi\";\x82\xd3\xe4\x93\x025:\x01*\x1a0/loaivukhi/ent/put-by-name/{ten_loai_vu_khi_new}\x12\x91\x01\n" +
	"\x15DeleteByNameLoaiVuKhi\x12\x1e.v1.XoaTheoTenLoaiVuKhiRequest\x1a\x1f.v1.XoaTheoTenLoaiVuKhiResponse\"7\x82\xd3\xe4\x93\x021*//loaivukhi/ent/delete-by-name/{ten_loai_vu_khi}\x12_\n" +
	"\x0fGetAllLoaiVuKhi\x12\x16.google.protobuf.Empty\x1a\x15.v1.DanhSachLoaiVuKhi\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/loaivukhi/ent/getall\x12e\n" +
	"\x12GetAllTenLoaiVuKhi\x12\x16.google.protobuf.Empty\x1a\x1b.v1.DanhSachStringLoaiVuKhi\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/loaivukhi/ent/ten\x12g\n" +
	"\x13GetAllMoTaLoaiVuKhi\x12\x16.google.protobuf.Empty\x1a\x1b.v1.DanhSachStringLoaiVuKhi\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/loaivukhi/ent/mota\x12g\n" +
	"\x0fSearchLoaiVuKhi\x12\x1b.v1.TimKiemLoaiVuKhiRequest\x1a\x15.v1.DanhSachLoaiVuKhi\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/loaivukhi/ent/searchB\x12Z\x10game/proto/v1;v1b\x06proto3"

var (
	file_proto_loaivukhi_proto_rawDescOnce sync.Once
	file_proto_loaivukhi_proto_rawDescData []byte
)

func file_proto_loaivukhi_proto_rawDescGZIP() []byte {
	file_proto_loaivukhi_proto_rawDescOnce.Do(func() {
		file_proto_loaivukhi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_loaivukhi_proto_rawDesc), len(file_proto_loaivukhi_proto_rawDesc)))
	})
	return file_proto_loaivukhi_proto_rawDescData
}

var file_proto_loaivukhi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_loaivukhi_proto_goTypes = []any{
	(*LoaiVuKhi)(nil),                      // 0: v1.LoaiVuKhi
	(*TaoLoaiVuKhiRequest)(nil),            // 1: v1.TaoLoaiVuKhiRequest
	(*CapNhatTheoTenLoaiVuKhiRequest)(nil), // 2: v1.CapNhatTheoTenLoaiVuKhiRequest
	(*XoaTheoTenLoaiVuKhiRequest)(nil),     // 3: v1.XoaTheoTenLoaiVuKhiRequest
	(*XoaTheoTenLoaiVuKhiResponse)(nil),    // 4: v1.XoaTheoTenLoaiVuKhiResponse
	(*DanhSachLoaiVuKhi)(nil),              // 5: v1.DanhSachLoaiVuKhi
	(*DanhSachStringLoaiVuKhi)(nil),        // 6: v1.DanhSachStringLoaiVuKhi
	(*TimKiemLoaiVuKhiRequest)(nil),        // 7: v1.TimKiemLoaiVuKhiRequest
	(*wrapperspb.Int32Value)(nil),          // 8: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),                  // 9: google.protobuf.Empty
}
var file_proto_loaivukhi_proto_depIdxs = []int32{
	0,  // 0: v1.DanhSachLoaiVuKhi.items:type_name -> v1.LoaiVuKhi
	8,  // 1: v1.TimKiemLoaiVuKhiRequest.ma_loai_vu_khi:type_name -> google.protobuf.Int32Value
	8,  // 2: v1.TimKiemLoaiVuKhiRequest.min_ma_loai_vu_khi:type_name -> google.protobuf.Int32Value
	8,  // 3: v1.TimKiemLoaiVuKhiRequest.max_ma_loai_vu_khi:type_name -> google.protobuf.Int32Value
	1,  // 4: v1.LoaiVuKhiService.CreateLoaiVuKhi:input_type -> v1.TaoLoaiVuKhiRequest
	2,  // 5: v1.LoaiVuKhiService.UpdateByNameLoaiVuKhi:input_type -> v1.CapNhatTheoTenLoaiVuKhiRequest
	3,  // 6: v1.LoaiVuKhiService.DeleteByNameLoaiVuKhi:input_type -> v1.XoaTheoTenLoaiVuKhiRequest
	9,  // 7: v1.LoaiVuKhiService.GetAllLoaiVuKhi:input_type -> google.protobuf.Empty
	9,  // 8: v1.LoaiVuKhiService.GetAllTenLoaiVuKhi:input_type -> google.protobuf.Empty
	9,  // 9: v1.LoaiVuKhiService.GetAllMoTaLoaiVuKhi:input_type -> google.protobuf.Empty
	7,  // 10: v1.LoaiVuKhiService.SearchLoaiVuKhi:input_type -> v1.TimKiemLoaiVuKhiRequest
	0,  // 11: v1.LoaiVuKhiService.CreateLoaiVuKhi:output_type -> v1.LoaiVuKhi
	0,  // 12: v1.LoaiVuKhiService.UpdateByNameLoaiVuKhi:output_type -> v1.LoaiVuKhi
	4,  // 13: v1.LoaiVuKhiService.DeleteByNameLoaiVuKhi:output_type -> v1.XoaTheoTenLoaiVuKhiResponse
	5,  // 14: v1.LoaiVuKhiService.GetAllLoaiVuKhi:output_type -> v1.DanhSachLoaiVuKhi
	6,  // 15: v1.LoaiVuKhiService.GetAllTenLoaiVuKhi:output_type -> v1.DanhSachStringLoaiVuKhi
	6,  // 16: v1.LoaiVuKhiService.GetAllMoTaLoaiVuKhi:output_type -> v1.DanhSachStringLoaiVuKhi
	5,  // 17: v1.LoaiVuKhiService.SearchLoaiVuKhi:output_type -> v1.DanhSachLoaiVuKhi
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_loaivukhi_proto_init() }
func file_proto_loaivukhi_proto_init() {
	if File_proto_loaivukhi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_loaivukhi_proto_rawDesc), len(file_proto_loaivukhi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_loaivukhi_proto_goTypes,
		DependencyIndexes: file_proto_loaivukhi_proto_depIdxs,
		MessageInfos:      file_proto_loaivukhi_proto_msgTypes,
	}.Build()
	File_proto_loaivukhi_proto = out.File
	file_proto_loaivukhi_proto_goTypes = nil
	file_proto_loaivukhi_proto_depIdxs = nil
}
