// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/vukhi.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VuKhiService_CreateVuKhi_FullMethodName                    = "/v1.VuKhiService/CreateVuKhi"
	VuKhiService_UpdateByNameVuKhi_FullMethodName              = "/v1.VuKhiService/UpdateByNameVuKhi"
	VuKhiService_DeleteByNameVuKhi_FullMethodName              = "/v1.VuKhiService/DeleteByNameVuKhi"
	VuKhiService_GetAllVuKhi_FullMethodName                    = "/v1.VuKhiService/GetAllVuKhi"
	VuKhiService_GetAllTenVuKhi_FullMethodName                 = "/v1.VuKhiService/GetAllTenVuKhi"
	VuKhiService_GetAllSatThuongCoBan_FullMethodName           = "/v1.VuKhiService/GetAllSatThuongCoBan"
	VuKhiService_GetAllTocDoDanh_FullMethodName                = "/v1.VuKhiService/GetAllTocDoDanh"
	VuKhiService_GetAllTamDanh_FullMethodName                  = "/v1.VuKhiService/GetAllTamDanh"
	VuKhiService_SearchVuKhi_FullMethodName                    = "/v1.VuKhiService/SearchVuKhi"
	VuKhiService_LayVersion_FullMethodName                     = "/v1.VuKhiService/LayVersion"
	VuKhiService_StreamServerSideGetVuKhi_FullMethodName       = "/v1.VuKhiService/StreamServerSideGetVuKhi"
	VuKhiService_StreamClientSideUpdateVuKhi_FullMethodName    = "/v1.VuKhiService/StreamClientSideUpdateVuKhi"
	VuKhiService_StreamBidirectionalUpdateVuKhi_FullMethodName = "/v1.VuKhiService/StreamBidirectionalUpdateVuKhi"
)

// VuKhiServiceClient is the client API for VuKhiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VuKhiService quản lý các thao tác CRUD và tìm kiếm Vũ Khí
type VuKhiServiceClient interface {
	// POST /vukhi/ent/post
	CreateVuKhi(ctx context.Context, in *TaoVuKhiRequest, opts ...grpc.CallOption) (*VuKhi, error)
	// PUT /vukhi/ent/put-by-name/{name}
	UpdateByNameVuKhi(ctx context.Context, in *CapNhatTheoTenVuKhiRequest, opts ...grpc.CallOption) (*VuKhi, error)
	// DELETE /vukhi/ent/delete-by-name/{name}
	DeleteByNameVuKhi(ctx context.Context, in *XoaTheoTenVuKhiRequest, opts ...grpc.CallOption) (*XoaTheoTenVuKhiResponse, error)
	// GET /vukhi/ent/getall?q=...
	GetAllVuKhi(ctx context.Context, in *LayTatCaRequest, opts ...grpc.CallOption) (*DanhSachVuKhi, error)
	// GET /vukhi/ent/ten
	GetAllTenVuKhi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachStringVuKhi, error)
	// GET /vukhi/ent/satthuongcoban
	GetAllSatThuongCoBan(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachIntVuKhi, error)
	// GET /vukhi/ent/tocdo
	GetAllTocDoDanh(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachDoubleVuKhi, error)
	// GET /vukhi/ent/tamdanh
	GetAllTamDanh(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachIntVuKhi, error)
	// POST /vukhi/ent/search
	SearchVuKhi(ctx context.Context, in *TimKiemVuKhiRequest, opts ...grpc.CallOption) (*DanhSachVuKhi, error)
	// service VuKhiService {
	LayVersion(ctx context.Context, in *LayVersionRequest, opts ...grpc.CallOption) (*LayVersionResponse, error)
	//
	StreamServerSideGetVuKhi(ctx context.Context, in *LayTatCaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DanhSachVuKhiStream], error)
	//
	StreamClientSideUpdateVuKhi(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CapNhatTheoTenVuKhiRequest, BatchUpdateResult], error)
	//
	StreamBidirectionalUpdateVuKhi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CapNhatTheoTenVuKhiRequest, UpdateItemResult], error)
}

type vuKhiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVuKhiServiceClient(cc grpc.ClientConnInterface) VuKhiServiceClient {
	return &vuKhiServiceClient{cc}
}

func (c *vuKhiServiceClient) CreateVuKhi(ctx context.Context, in *TaoVuKhiRequest, opts ...grpc.CallOption) (*VuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VuKhi)
	err := c.cc.Invoke(ctx, VuKhiService_CreateVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) UpdateByNameVuKhi(ctx context.Context, in *CapNhatTheoTenVuKhiRequest, opts ...grpc.CallOption) (*VuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VuKhi)
	err := c.cc.Invoke(ctx, VuKhiService_UpdateByNameVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) DeleteByNameVuKhi(ctx context.Context, in *XoaTheoTenVuKhiRequest, opts ...grpc.CallOption) (*XoaTheoTenVuKhiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XoaTheoTenVuKhiResponse)
	err := c.cc.Invoke(ctx, VuKhiService_DeleteByNameVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) GetAllVuKhi(ctx context.Context, in *LayTatCaRequest, opts ...grpc.CallOption) (*DanhSachVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachVuKhi)
	err := c.cc.Invoke(ctx, VuKhiService_GetAllVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) GetAllTenVuKhi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachStringVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachStringVuKhi)
	err := c.cc.Invoke(ctx, VuKhiService_GetAllTenVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) GetAllSatThuongCoBan(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachIntVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachIntVuKhi)
	err := c.cc.Invoke(ctx, VuKhiService_GetAllSatThuongCoBan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) GetAllTocDoDanh(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachDoubleVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachDoubleVuKhi)
	err := c.cc.Invoke(ctx, VuKhiService_GetAllTocDoDanh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) GetAllTamDanh(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DanhSachIntVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachIntVuKhi)
	err := c.cc.Invoke(ctx, VuKhiService_GetAllTamDanh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) SearchVuKhi(ctx context.Context, in *TimKiemVuKhiRequest, opts ...grpc.CallOption) (*DanhSachVuKhi, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanhSachVuKhi)
	err := c.cc.Invoke(ctx, VuKhiService_SearchVuKhi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) LayVersion(ctx context.Context, in *LayVersionRequest, opts ...grpc.CallOption) (*LayVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayVersionResponse)
	err := c.cc.Invoke(ctx, VuKhiService_LayVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vuKhiServiceClient) StreamServerSideGetVuKhi(ctx context.Context, in *LayTatCaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DanhSachVuKhiStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VuKhiService_ServiceDesc.Streams[0], VuKhiService_StreamServerSideGetVuKhi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LayTatCaRequest, DanhSachVuKhiStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VuKhiService_StreamServerSideGetVuKhiClient = grpc.ServerStreamingClient[DanhSachVuKhiStream]

func (c *vuKhiServiceClient) StreamClientSideUpdateVuKhi(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CapNhatTheoTenVuKhiRequest, BatchUpdateResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VuKhiService_ServiceDesc.Streams[1], VuKhiService_StreamClientSideUpdateVuKhi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CapNhatTheoTenVuKhiRequest, BatchUpdateResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VuKhiService_StreamClientSideUpdateVuKhiClient = grpc.ClientStreamingClient[CapNhatTheoTenVuKhiRequest, BatchUpdateResult]

func (c *vuKhiServiceClient) StreamBidirectionalUpdateVuKhi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CapNhatTheoTenVuKhiRequest, UpdateItemResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VuKhiService_ServiceDesc.Streams[2], VuKhiService_StreamBidirectionalUpdateVuKhi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CapNhatTheoTenVuKhiRequest, UpdateItemResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VuKhiService_StreamBidirectionalUpdateVuKhiClient = grpc.BidiStreamingClient[CapNhatTheoTenVuKhiRequest, UpdateItemResult]

// VuKhiServiceServer is the server API for VuKhiService service.
// All implementations must embed UnimplementedVuKhiServiceServer
// for forward compatibility.
//
// VuKhiService quản lý các thao tác CRUD và tìm kiếm Vũ Khí
type VuKhiServiceServer interface {
	// POST /vukhi/ent/post
	CreateVuKhi(context.Context, *TaoVuKhiRequest) (*VuKhi, error)
	// PUT /vukhi/ent/put-by-name/{name}
	UpdateByNameVuKhi(context.Context, *CapNhatTheoTenVuKhiRequest) (*VuKhi, error)
	// DELETE /vukhi/ent/delete-by-name/{name}
	DeleteByNameVuKhi(context.Context, *XoaTheoTenVuKhiRequest) (*XoaTheoTenVuKhiResponse, error)
	// GET /vukhi/ent/getall?q=...
	GetAllVuKhi(context.Context, *LayTatCaRequest) (*DanhSachVuKhi, error)
	// GET /vukhi/ent/ten
	GetAllTenVuKhi(context.Context, *emptypb.Empty) (*DanhSachStringVuKhi, error)
	// GET /vukhi/ent/satthuongcoban
	GetAllSatThuongCoBan(context.Context, *emptypb.Empty) (*DanhSachIntVuKhi, error)
	// GET /vukhi/ent/tocdo
	GetAllTocDoDanh(context.Context, *emptypb.Empty) (*DanhSachDoubleVuKhi, error)
	// GET /vukhi/ent/tamdanh
	GetAllTamDanh(context.Context, *emptypb.Empty) (*DanhSachIntVuKhi, error)
	// POST /vukhi/ent/search
	SearchVuKhi(context.Context, *TimKiemVuKhiRequest) (*DanhSachVuKhi, error)
	// service VuKhiService {
	LayVersion(context.Context, *LayVersionRequest) (*LayVersionResponse, error)
	//
	StreamServerSideGetVuKhi(*LayTatCaRequest, grpc.ServerStreamingServer[DanhSachVuKhiStream]) error
	//
	StreamClientSideUpdateVuKhi(grpc.ClientStreamingServer[CapNhatTheoTenVuKhiRequest, BatchUpdateResult]) error
	//
	StreamBidirectionalUpdateVuKhi(grpc.BidiStreamingServer[CapNhatTheoTenVuKhiRequest, UpdateItemResult]) error
	mustEmbedUnimplementedVuKhiServiceServer()
}

// UnimplementedVuKhiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVuKhiServiceServer struct{}

func (UnimplementedVuKhiServiceServer) CreateVuKhi(context.Context, *TaoVuKhiRequest) (*VuKhi, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) UpdateByNameVuKhi(context.Context, *CapNhatTheoTenVuKhiRequest) (*VuKhi, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateByNameVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) DeleteByNameVuKhi(context.Context, *XoaTheoTenVuKhiRequest) (*XoaTheoTenVuKhiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByNameVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) GetAllVuKhi(context.Context, *LayTatCaRequest) (*DanhSachVuKhi, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) GetAllTenVuKhi(context.Context, *emptypb.Empty) (*DanhSachStringVuKhi, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTenVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) GetAllSatThuongCoBan(context.Context, *emptypb.Empty) (*DanhSachIntVuKhi, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSatThuongCoBan not implemented")
}
func (UnimplementedVuKhiServiceServer) GetAllTocDoDanh(context.Context, *emptypb.Empty) (*DanhSachDoubleVuKhi, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTocDoDanh not implemented")
}
func (UnimplementedVuKhiServiceServer) GetAllTamDanh(context.Context, *emptypb.Empty) (*DanhSachIntVuKhi, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTamDanh not implemented")
}
func (UnimplementedVuKhiServiceServer) SearchVuKhi(context.Context, *TimKiemVuKhiRequest) (*DanhSachVuKhi, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) LayVersion(context.Context, *LayVersionRequest) (*LayVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LayVersion not implemented")
}
func (UnimplementedVuKhiServiceServer) StreamServerSideGetVuKhi(*LayTatCaRequest, grpc.ServerStreamingServer[DanhSachVuKhiStream]) error {
	return status.Error(codes.Unimplemented, "method StreamServerSideGetVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) StreamClientSideUpdateVuKhi(grpc.ClientStreamingServer[CapNhatTheoTenVuKhiRequest, BatchUpdateResult]) error {
	return status.Error(codes.Unimplemented, "method StreamClientSideUpdateVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) StreamBidirectionalUpdateVuKhi(grpc.BidiStreamingServer[CapNhatTheoTenVuKhiRequest, UpdateItemResult]) error {
	return status.Error(codes.Unimplemented, "method StreamBidirectionalUpdateVuKhi not implemented")
}
func (UnimplementedVuKhiServiceServer) mustEmbedUnimplementedVuKhiServiceServer() {}
func (UnimplementedVuKhiServiceServer) testEmbeddedByValue()                      {}

// UnsafeVuKhiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VuKhiServiceServer will
// result in compilation errors.
type UnsafeVuKhiServiceServer interface {
	mustEmbedUnimplementedVuKhiServiceServer()
}

func RegisterVuKhiServiceServer(s grpc.ServiceRegistrar, srv VuKhiServiceServer) {
	// If the following call panics, it indicates UnimplementedVuKhiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VuKhiService_ServiceDesc, srv)
}

func _VuKhiService_CreateVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaoVuKhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).CreateVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_CreateVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).CreateVuKhi(ctx, req.(*TaoVuKhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_UpdateByNameVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapNhatTheoTenVuKhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).UpdateByNameVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_UpdateByNameVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).UpdateByNameVuKhi(ctx, req.(*CapNhatTheoTenVuKhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_DeleteByNameVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XoaTheoTenVuKhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).DeleteByNameVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_DeleteByNameVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).DeleteByNameVuKhi(ctx, req.(*XoaTheoTenVuKhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_GetAllVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayTatCaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).GetAllVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_GetAllVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).GetAllVuKhi(ctx, req.(*LayTatCaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_GetAllTenVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).GetAllTenVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_GetAllTenVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).GetAllTenVuKhi(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_GetAllSatThuongCoBan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).GetAllSatThuongCoBan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_GetAllSatThuongCoBan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).GetAllSatThuongCoBan(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_GetAllTocDoDanh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).GetAllTocDoDanh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_GetAllTocDoDanh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).GetAllTocDoDanh(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_GetAllTamDanh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).GetAllTamDanh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_GetAllTamDanh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).GetAllTamDanh(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_SearchVuKhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimKiemVuKhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).SearchVuKhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_SearchVuKhi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).SearchVuKhi(ctx, req.(*TimKiemVuKhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_LayVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VuKhiServiceServer).LayVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VuKhiService_LayVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VuKhiServiceServer).LayVersion(ctx, req.(*LayVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VuKhiService_StreamServerSideGetVuKhi_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LayTatCaRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VuKhiServiceServer).StreamServerSideGetVuKhi(m, &grpc.GenericServerStream[LayTatCaRequest, DanhSachVuKhiStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VuKhiService_StreamServerSideGetVuKhiServer = grpc.ServerStreamingServer[DanhSachVuKhiStream]

func _VuKhiService_StreamClientSideUpdateVuKhi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VuKhiServiceServer).StreamClientSideUpdateVuKhi(&grpc.GenericServerStream[CapNhatTheoTenVuKhiRequest, BatchUpdateResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VuKhiService_StreamClientSideUpdateVuKhiServer = grpc.ClientStreamingServer[CapNhatTheoTenVuKhiRequest, BatchUpdateResult]

func _VuKhiService_StreamBidirectionalUpdateVuKhi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VuKhiServiceServer).StreamBidirectionalUpdateVuKhi(&grpc.GenericServerStream[CapNhatTheoTenVuKhiRequest, UpdateItemResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VuKhiService_StreamBidirectionalUpdateVuKhiServer = grpc.BidiStreamingServer[CapNhatTheoTenVuKhiRequest, UpdateItemResult]

// VuKhiService_ServiceDesc is the grpc.ServiceDesc for VuKhiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VuKhiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VuKhiService",
	HandlerType: (*VuKhiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVuKhi",
			Handler:    _VuKhiService_CreateVuKhi_Handler,
		},
		{
			MethodName: "UpdateByNameVuKhi",
			Handler:    _VuKhiService_UpdateByNameVuKhi_Handler,
		},
		{
			MethodName: "DeleteByNameVuKhi",
			Handler:    _VuKhiService_DeleteByNameVuKhi_Handler,
		},
		{
			MethodName: "GetAllVuKhi",
			Handler:    _VuKhiService_GetAllVuKhi_Handler,
		},
		{
			MethodName: "GetAllTenVuKhi",
			Handler:    _VuKhiService_GetAllTenVuKhi_Handler,
		},
		{
			MethodName: "GetAllSatThuongCoBan",
			Handler:    _VuKhiService_GetAllSatThuongCoBan_Handler,
		},
		{
			MethodName: "GetAllTocDoDanh",
			Handler:    _VuKhiService_GetAllTocDoDanh_Handler,
		},
		{
			MethodName: "GetAllTamDanh",
			Handler:    _VuKhiService_GetAllTamDanh_Handler,
		},
		{
			MethodName: "SearchVuKhi",
			Handler:    _VuKhiService_SearchVuKhi_Handler,
		},
		{
			MethodName: "LayVersion",
			Handler:    _VuKhiService_LayVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamServerSideGetVuKhi",
			Handler:       _VuKhiService_StreamServerSideGetVuKhi_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamClientSideUpdateVuKhi",
			Handler:       _VuKhiService_StreamClientSideUpdateVuKhi_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamBidirectionalUpdateVuKhi",
			Handler:       _VuKhiService_StreamBidirectionalUpdateVuKhi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/vukhi.proto",
}
