syntax = "proto3";

package v1;
option go_package = "game/v1;v1";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";


message He {
  int32  ma_he     = 1; 
  string ten_he = 2;
  string mo_ta  = 3;
}

message TaoHeRequest{
    int32 ma_he = 1;
    string ten_he = 2;
    string mo_ta = 3;
}

message CapNhatTheoTenHeRequest {
  string name               = 1;

  string ten_he  = 2;
  string mo_ta       = 3;
}

message XoaTheoTenHeRequest {
  string name = 1;
}

message XoaTheoTenHeResponse {
  string deleted_name = 1;
}

message DanhSachHe {
  int32 total = 1;
  repeated He items = 2;
}

message DanhSachStringHe {
  int32 total          = 1;
  repeated string items = 2;
}

message TimKiemHeRequest {
  google.protobuf.Int32Value ma_he   = 1;
  string                     ten_he  = 2; 
  string                     mo_ta   = 3; 
  string                     q       = 4;  
}

service HeService {
  // POST /he/ent/post
  rpc CreateHe (TaoHeRequest) returns (He){
  option (google.api.http) = {
      post: "/he/ent/post"
      body: "*"
    };
  }

  // PUT /he/ent/put-by-name/{name}
  rpc UpdateByNameHe (CapNhatTheoTenHeRequest) returns (He) {
    option (google.api.http) = {
      put: "/he/ent/put-by-name/{name}"
      body: "*"
    };
  }

  // DELETE /he/ent/delete-by-name/{name}
  rpc DeleteByNameHe (XoaTheoTenHeRequest) returns (XoaTheoTenHeResponse) {
    option (google.api.http) = {
      delete: "/he/ent/delete-by-name/{name}"
    };
  }

  // GET /he/ent/getall
  rpc GetAllHe (google.protobuf.Empty) returns (DanhSachHe) {
    option (google.api.http) = {
      get: "/he/ent/getall"
    };
  }

  // GET /he/ent/ten
  rpc GetAllTenHe (google.protobuf.Empty) returns (DanhSachStringHe) {
    option (google.api.http) = {
      get: "/he/ent/ten"
    };
  }

  // GET /he/ent/mota
  rpc GetAllMoTaHe (google.protobuf.Empty) returns (DanhSachStringHe) {
    option (google.api.http) = {
      get: "/he/ent/mota"
    };
  }
  // POST /he/ent/search
  rpc SearchHe (TimKiemHeRequest) returns (DanhSachHe) {
    option (google.api.http) = {
      post: "/he/ent/search"
      body: "*"
    };
  }
}
