// Code generated by ent, DO NOT EDIT.

package loaivukhi

import (
	"game/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLTE(FieldID, id))
}

// TenLoai applies equality check predicate on the "ten_loai" field. It's identical to TenLoaiEQ.
func TenLoai(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldTenLoai, v))
}

// MoTa applies equality check predicate on the "mo_ta" field. It's identical to MoTaEQ.
func MoTa(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldMoTa, v))
}

// TenLoaiEQ applies the EQ predicate on the "ten_loai" field.
func TenLoaiEQ(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldTenLoai, v))
}

// TenLoaiNEQ applies the NEQ predicate on the "ten_loai" field.
func TenLoaiNEQ(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNEQ(FieldTenLoai, v))
}

// TenLoaiIn applies the In predicate on the "ten_loai" field.
func TenLoaiIn(vs ...string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldIn(FieldTenLoai, vs...))
}

// TenLoaiNotIn applies the NotIn predicate on the "ten_loai" field.
func TenLoaiNotIn(vs ...string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNotIn(FieldTenLoai, vs...))
}

// TenLoaiGT applies the GT predicate on the "ten_loai" field.
func TenLoaiGT(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGT(FieldTenLoai, v))
}

// TenLoaiGTE applies the GTE predicate on the "ten_loai" field.
func TenLoaiGTE(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGTE(FieldTenLoai, v))
}

// TenLoaiLT applies the LT predicate on the "ten_loai" field.
func TenLoaiLT(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLT(FieldTenLoai, v))
}

// TenLoaiLTE applies the LTE predicate on the "ten_loai" field.
func TenLoaiLTE(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLTE(FieldTenLoai, v))
}

// TenLoaiContains applies the Contains predicate on the "ten_loai" field.
func TenLoaiContains(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldContains(FieldTenLoai, v))
}

// TenLoaiHasPrefix applies the HasPrefix predicate on the "ten_loai" field.
func TenLoaiHasPrefix(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldHasPrefix(FieldTenLoai, v))
}

// TenLoaiHasSuffix applies the HasSuffix predicate on the "ten_loai" field.
func TenLoaiHasSuffix(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldHasSuffix(FieldTenLoai, v))
}

// TenLoaiEqualFold applies the EqualFold predicate on the "ten_loai" field.
func TenLoaiEqualFold(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEqualFold(FieldTenLoai, v))
}

// TenLoaiContainsFold applies the ContainsFold predicate on the "ten_loai" field.
func TenLoaiContainsFold(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldContainsFold(FieldTenLoai, v))
}

// MoTaEQ applies the EQ predicate on the "mo_ta" field.
func MoTaEQ(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldMoTa, v))
}

// MoTaNEQ applies the NEQ predicate on the "mo_ta" field.
func MoTaNEQ(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNEQ(FieldMoTa, v))
}

// MoTaIn applies the In predicate on the "mo_ta" field.
func MoTaIn(vs ...string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldIn(FieldMoTa, vs...))
}

// MoTaNotIn applies the NotIn predicate on the "mo_ta" field.
func MoTaNotIn(vs ...string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNotIn(FieldMoTa, vs...))
}

// MoTaGT applies the GT predicate on the "mo_ta" field.
func MoTaGT(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGT(FieldMoTa, v))
}

// MoTaGTE applies the GTE predicate on the "mo_ta" field.
func MoTaGTE(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGTE(FieldMoTa, v))
}

// MoTaLT applies the LT predicate on the "mo_ta" field.
func MoTaLT(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLT(FieldMoTa, v))
}

// MoTaLTE applies the LTE predicate on the "mo_ta" field.
func MoTaLTE(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLTE(FieldMoTa, v))
}

// MoTaContains applies the Contains predicate on the "mo_ta" field.
func MoTaContains(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldContains(FieldMoTa, v))
}

// MoTaHasPrefix applies the HasPrefix predicate on the "mo_ta" field.
func MoTaHasPrefix(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldHasPrefix(FieldMoTa, v))
}

// MoTaHasSuffix applies the HasSuffix predicate on the "mo_ta" field.
func MoTaHasSuffix(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldHasSuffix(FieldMoTa, v))
}

// MoTaIsNil applies the IsNil predicate on the "mo_ta" field.
func MoTaIsNil() predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldIsNull(FieldMoTa))
}

// MoTaNotNil applies the NotNil predicate on the "mo_ta" field.
func MoTaNotNil() predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNotNull(FieldMoTa))
}

// MoTaEqualFold applies the EqualFold predicate on the "mo_ta" field.
func MoTaEqualFold(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEqualFold(FieldMoTa, v))
}

// MoTaContainsFold applies the ContainsFold predicate on the "mo_ta" field.
func MoTaContainsFold(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldContainsFold(FieldMoTa, v))
}

// HasVuKhi applies the HasEdge predicate on the "vu_khi" edge.
func HasVuKhi() predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VuKhiTable, VuKhiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVuKhiWith applies the HasEdge predicate on the "vu_khi" edge with a given conditions (other predicates).
func HasVuKhiWith(preds ...predicate.VuKhi) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(func(s *sql.Selector) {
		step := newVuKhiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoaiVuKhi) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoaiVuKhi) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoaiVuKhi) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.NotPredicates(p))
}
