// Code generated by ent, DO NOT EDIT.

package loaivukhi

import (
	"game/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLTE(FieldID, id))
}

// TenLoaiVuKhi applies equality check predicate on the "ten_loai_vu_khi" field. It's identical to TenLoaiVuKhiEQ.
func TenLoaiVuKhi(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldTenLoaiVuKhi, v))
}

// MoTa applies equality check predicate on the "mo_ta" field. It's identical to MoTaEQ.
func MoTa(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldMoTa, v))
}

// TenLoaiVuKhiEQ applies the EQ predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiEQ(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiNEQ applies the NEQ predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiNEQ(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNEQ(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiIn applies the In predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiIn(vs ...string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldIn(FieldTenLoaiVuKhi, vs...))
}

// TenLoaiVuKhiNotIn applies the NotIn predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiNotIn(vs ...string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNotIn(FieldTenLoaiVuKhi, vs...))
}

// TenLoaiVuKhiGT applies the GT predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiGT(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGT(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiGTE applies the GTE predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiGTE(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGTE(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiLT applies the LT predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiLT(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLT(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiLTE applies the LTE predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiLTE(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLTE(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiContains applies the Contains predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiContains(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldContains(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiHasPrefix applies the HasPrefix predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiHasPrefix(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldHasPrefix(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiHasSuffix applies the HasSuffix predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiHasSuffix(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldHasSuffix(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiEqualFold applies the EqualFold predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiEqualFold(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEqualFold(FieldTenLoaiVuKhi, v))
}

// TenLoaiVuKhiContainsFold applies the ContainsFold predicate on the "ten_loai_vu_khi" field.
func TenLoaiVuKhiContainsFold(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldContainsFold(FieldTenLoaiVuKhi, v))
}

// MoTaEQ applies the EQ predicate on the "mo_ta" field.
func MoTaEQ(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEQ(FieldMoTa, v))
}

// MoTaNEQ applies the NEQ predicate on the "mo_ta" field.
func MoTaNEQ(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNEQ(FieldMoTa, v))
}

// MoTaIn applies the In predicate on the "mo_ta" field.
func MoTaIn(vs ...string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldIn(FieldMoTa, vs...))
}

// MoTaNotIn applies the NotIn predicate on the "mo_ta" field.
func MoTaNotIn(vs ...string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNotIn(FieldMoTa, vs...))
}

// MoTaGT applies the GT predicate on the "mo_ta" field.
func MoTaGT(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGT(FieldMoTa, v))
}

// MoTaGTE applies the GTE predicate on the "mo_ta" field.
func MoTaGTE(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldGTE(FieldMoTa, v))
}

// MoTaLT applies the LT predicate on the "mo_ta" field.
func MoTaLT(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLT(FieldMoTa, v))
}

// MoTaLTE applies the LTE predicate on the "mo_ta" field.
func MoTaLTE(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldLTE(FieldMoTa, v))
}

// MoTaContains applies the Contains predicate on the "mo_ta" field.
func MoTaContains(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldContains(FieldMoTa, v))
}

// MoTaHasPrefix applies the HasPrefix predicate on the "mo_ta" field.
func MoTaHasPrefix(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldHasPrefix(FieldMoTa, v))
}

// MoTaHasSuffix applies the HasSuffix predicate on the "mo_ta" field.
func MoTaHasSuffix(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldHasSuffix(FieldMoTa, v))
}

// MoTaIsNil applies the IsNil predicate on the "mo_ta" field.
func MoTaIsNil() predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldIsNull(FieldMoTa))
}

// MoTaNotNil applies the NotNil predicate on the "mo_ta" field.
func MoTaNotNil() predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldNotNull(FieldMoTa))
}

// MoTaEqualFold applies the EqualFold predicate on the "mo_ta" field.
func MoTaEqualFold(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldEqualFold(FieldMoTa, v))
}

// MoTaContainsFold applies the ContainsFold predicate on the "mo_ta" field.
func MoTaContainsFold(v string) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.FieldContainsFold(FieldMoTa, v))
}

// HasVuKhi applies the HasEdge predicate on the "vu_khi" edge.
func HasVuKhi() predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VuKhiTable, VuKhiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVuKhiWith applies the HasEdge predicate on the "vu_khi" edge with a given conditions (other predicates).
func HasVuKhiWith(preds ...predicate.VuKhi) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(func(s *sql.Selector) {
		step := newVuKhiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoaiVuKhi) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoaiVuKhi) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoaiVuKhi) predicate.LoaiVuKhi {
	return predicate.LoaiVuKhi(sql.NotPredicates(p))
}
